Repository the-events-calendar/tribe-common, pull requests merged in 2018-07, with the labels that each got.

#731 Lots of mb_string functions to the rescue!
  composer.lock
  src/Tribe/Main.php
  src/Tribe/Utils/Post_Root_Pool.php
  src/functions/multibyte.php
  tests/wpunit/_bootstrap.php
Labels: merge

#733 Try to handle urlencoded strings
  src/Tribe/Utils/Post_Root_Pool.php
  src/functions/multibyte.php
Labels: code review, merge

#736 Add stuck queue detection and garbage collection
  src/Tribe/Process/Queue.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Process/QueueTest.php
Labels: merge

#737 Add `target="_blank"` to repository links in the Help Page
  readme.txt
  src/Tribe/Admin/Help_Page.php
  src/admin-views/app-shop.php
Labels: merge

#730 Tribe ORM Read repository first draft
  .travis.yml
  composer.lock
  src/Tribe/Repository.php
  src/Tribe/Repository/Implementation_Error.php
  src/Tribe/Repository/Interface.php
  src/Tribe/Repository/Query_Filters.php
  src/Tribe/Repository/Read.php
  src/Tribe/Repository/Read_Interface.php
  src/Tribe/Repository/Specialized_Base.php
  src/Tribe/Repository/Usage_Error.php
  src/Tribe/Repository/VoidQuery_Exception.php
  tests/_data/classes/Repository/Book_Repository.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Repository/ReadTest.php
  tests/wpunit/Tribe/RepositoryTest.php
  vendor/autoload_52.php
  vendor/composer/ClassLoader.php
  vendor/composer/LICENSE
  vendor/composer/autoload_commands_classmap.php
  vendor/composer/autoload_framework_classmap.php
  vendor/composer/autoload_real_52.php
  vendor/composer/installed.json
Labels: merge

#738 Update code to support Attendee queries
  src/Tribe/Repository/Query_Filters.php
  src/Tribe/Repository/Read.php
  src/Tribe/Utils/Array.php
  tests/wpunit/Tribe/Utils/ArrayTest.php
Labels: code review, merge

#740 #63144 - modify load_plugin_textdomain() to use relative path not fil…
  readme.txt
  src/Tribe/Main.php
Labels: merge

#657 Deprecated usage of The Events Calendar old Asset Loading methods
  readme.txt
  src/Tribe/Assets.php
  src/Tribe/Template_Factory.php
Labels: merge

#739 More work on ORM code
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Formatter_Interface.php
  src/Tribe/Repository/Interface.php
  src/Tribe/Repository/Query_Filters.php
  src/Tribe/Repository/Read.php
  src/Tribe/Repository/Read_Interface.php
  src/Tribe/Repository/Specialized_Base.php
  src/Tribe/Repository/Update_Interface.php
  src/Tribe/Repository/Usage_Error.php
  src/Tribe/Repository/Void_Query_Exception.php
  src/Tribe/Utils/Array.php
  src/Tribe/Validator/Base.php
  tests/wpunit/Tribe/Repository/ReadTest.php
  tests/wpunit/Tribe/Repository/UpdateTest.php
  tests/wpunit/Tribe/RepositoryTest.php
Labels: code review

#741 Add and update Array and Validator methods
  src/Tribe/REST/Headers/Base_Interface.php
  src/Tribe/Utils/Array.php
  src/Tribe/Validator/Base.php
  src/Tribe/Validator/Interface.php
Labels: merge

#742 Revert #741
  src/Tribe/REST/Headers/Base_Interface.php
  src/Tribe/Utils/Array.php
  src/Tribe/Validator/Base.php
  src/Tribe/Validator/Interface.php
Labels: code review, merge

#744 Cherry pick pull request #741 code
  src/Tribe/REST/Headers/Base_Interface.php
  src/Tribe/Utils/Array.php
  src/Tribe/Validator/Base.php
  src/Tribe/Validator/Interface.php
Labels: merge

#745 Correct logic when enqueueing with multiple conditionals
  src/Tribe/Assets.php
  src/functions/utils.php
Labels: merge

#746 M18.11 Release tasks
  lang/tribe-common-de_DE.mo
  lang/tribe-common-de_DE.po
  lang/tribe-common-pt_BR.mo
  lang/tribe-common-pt_BR.po
  readme.txt
  src/Tribe/Plugins.php
  src/Tribe/Process/Queue.php
  src/Tribe/Template_Factory.php
  src/Tribe/Utils/Array.php
  src/Tribe/Utils/Post_Root_Pool.php
  src/functions/multibyte.php
Labels: merge
