Repository the-events-calendar/tribe-common, pull requests merged in 2018-02, with the labels that each got.

#611 Create a way for fields to be Displayed but Disabled by dependency
  src/resources/js/dependency.js
  src/resources/js/dependency.min.js
Labels: code review, merge

#609 Update function declarations to use no conflict version of underscore
  readme.txt
  src/Tribe/Assets_Pipeline.php
  src/Tribe/Main.php
  src/resources/js/bumpdown.js
  src/resources/js/bumpdown.min.js
  src/resources/js/buttonset.js
  src/resources/js/buttonset.min.js
  src/resources/js/dependency.js
  src/resources/js/dependency.min.js
  src/resources/js/dropdowns.js
  src/resources/js/dropdowns.min.js
  src/resources/js/underscore-after.js
  src/resources/js/underscore-before.js
  src/resources/js/utils-camelcase.js
  src/resources/js/utils-camelcase.min.js
  src/resources/js/validation.js
  src/resources/js/validation.min.js
Labels: code review, merge

#613 Prevent running operations twice in the same object.
  src/resources/js/dependency.js
Labels: merge

#612 Prevent DST on UTC conversion of date times
  readme.txt
  src/Tribe/Timezones.php
Labels: merge

#615 Use currency symbol and position parameters when provided
  composer.lock
  readme.txt
  src/Tribe/Main.php
  src/functions/template-tags/general.php
  tests/_support/_generated/MuwpunitTesterActions.php
  tests/wpunit/Tribe/functions/templateTags/generalTest.php
  vendor/autoload_52.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_real_52.php
  vendor/composer/autoload_static.php
Labels: merge

#616 Bump Version Numbers to Create M18.04 Release Branch
  package.json
  readme.txt
  src/Tribe/Main.php
  tribe-common.php
Labels: merge

#618 Remove the dependency check in order to avoid EventAgreggator issues
  src/resources/js/dependency.js
Labels: code review

#619 Make sure element is present
  src/resources/js/dependency.js
Labels: code review, merge

#620 more robust checks on the context
  src/Tribe/Context.php
  src/Tribe/Utils/Array.php
Labels: code review, merge

#621 allow the use of data attr to avoid disabling field
  src/resources/js/dependency.js
  src/resources/js/dependency.min.js
  src/resources/js/underscore-after.min.js
  src/resources/js/underscore-before.min.js
Labels: code review, merge

#622 Rollback changes from DST
  readme.txt
  src/Tribe/Timezones.php
Labels: code review, merge

#617 #99183 Update Example Image
  src/admin-views/tribe-options-general.php
  src/resources/images/donate-link-pro-screenshot.jpg
  src/resources/images/donate-link-screenshot.jpg
  src/resources/images/donate-link-screenshot.png
Labels: code review, merge

#625 Fix queue processing callbacks
  src/Tribe/Main.php
Labels: merge

#624 Allow to hook into the cost before is returned
  src/functions/template-tags/general.php
Labels: merge

#627 Add better extending for Dropdown.js
  src/resources/js/dropdowns.js
  src/resources/js/dropdowns.min.js
Labels: code review, merge

#629 Fix validation of multi options if it cannot be empty
  src/Tribe/Validate.php
Labels: merge

#630 97344 Show Correct Timezone Abbreviation Regardless of Timezone Mode
  composer.json
  readme.txt
  src/Tribe/Timezones.php
Labels: code review, merge

#628 100199 Add Function for "Safely" Accessing the $wp_query Global
  readme.txt
  src/functions/utils.php
Labels: code review, merge
