Repository the-events-calendar/tribe-common, pull requests merged in 2018-04, with the labels that each got.

#660 Add base for async request handling and post thumbnail handler
  .travis.yml
  composer.json
  composer.lock
  readme.txt
  src/Tribe/Admin/Helpers.php
  src/Tribe/Admin/Notices.php
  src/Tribe/Context.php
  src/Tribe/Main.php
  src/Tribe/Process/Handler.php
  src/Tribe/Process/Post_Thumbnail_Setter.php
  src/Tribe/Service_Providers/Processes.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Process/Post_Thumbnail_SetterTest.php
Labels: merge

#662 Add missing async request library files
  .gitignore
  package-whitelist.json
  src/Tribe/Timezones.php
  vendor/a5hleyrich/wp-background-processing/.gitignore
  vendor/a5hleyrich/wp-background-processing/README.md
  vendor/a5hleyrich/wp-background-processing/classes/wp-async-request.php
  vendor/a5hleyrich/wp-background-processing/classes/wp-background-process.php
  vendor/a5hleyrich/wp-background-processing/composer.json
  vendor/a5hleyrich/wp-background-processing/license.txt
  vendor/a5hleyrich/wp-background-processing/wp-background-processing.php
  vendor/autoload_52.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_real_52.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
Labels: enhance, merge

#661 ⌗103167 Restore Type Attr to Some Inline Script Tags
  readme.txt
  src/Tribe/Customizer.php
Labels: merge

#664 Feature/103577 - Select2 maximumSelectionSize
  readme.txt
  src/resources/js/dropdowns.js
  src/resources/js/dropdowns.min.js
Labels: code review, merge

#665 Make sure to return the new value instead of the variable
  src/Tribe/Context.php
Labels: code review

#666 call the action method in a PHP 5.2 compatible way
  src/Tribe/Service_Providers/Processes.php
Labels: merge

#667 Add filters to allow customization on countries names
  readme.txt
  src/Tribe/Languages/Locations.php
Labels: merge

#668 Add more comprehensive Timezones::abbr() support
  readme.txt
  src/Tribe/Timezones.php
Labels: merge

#671 Make a soft deprecation of the method instead.
  src/Tribe/Main.php
Labels: merge

#673 Pass timezone when we have it
  src/functions/template-tags/date.php
Labels: merge

#675 Spotfix/sync branches
  lang/tribe-common-af.mo
  lang/tribe-common-bg_BG.po
  lang/tribe-common-da_DK.mo
  lang/tribe-common-es_ES.po
  lang/tribe-common-fr_CA.mo
  lang/tribe-common-it_IT.mo
  lang/tribe-common-it_IT.po
  lang/tribe-common-sl_SI.mo
  lang/tribe-common-sv_SE.mo
  lang/tribe-common.pot
  readme.txt
  src/resources/css/datatables.css
  src/resources/css/datatables.min.css
  src/resources/css/datepicker.css
  src/resources/css/datepicker.min.css
  src/resources/css/tribe-common-admin.css
  src/resources/css/tribe-common-admin.min.css
Labels: merge

#672 Replace Queue implementation with the new async one
  src/Tribe/Db.php
  src/Tribe/Main.php
  src/Tribe/Meta/Chunker.php
  src/Tribe/Process/Handler.php
  src/Tribe/Process/Queue.php
  src/Tribe/Queue.php
  src/Tribe/Queue/Worker.php
  src/Tribe/Service_Providers/Processes.php
  tests/_data/classes/Dummy_Queue.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Process/QueueTest.php
  tests/wpunit/Tribe/Queue/WorkerTest.php
  tests/wpunit/Tribe/QueueTest.php
Labels: merge

#677 Add the Queue class and tests
  readme.txt
  src/Tribe/Db.php
  src/Tribe/Main.php
  src/Tribe/Meta/Chunker.php
  src/Tribe/Process/Handler.php
  src/Tribe/Process/Queue.php
  src/Tribe/Service_Providers/Processes.php
  tests/_data/classes/Dummy_Queue.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Process/QueueTest.php
Labels: code review, merge

#679 Hook the queueing system before (as in the `bucket/instance-engine` branch)
  src/Tribe/Main.php
Labels: merge

#680 Fix/104561 help change forum for help desk
  readme.txt
  src/admin-views/tribe-options-help.php
Labels: code review, merge

#681 Fix cases where $global_id is entity encoded
  src/Tribe/Utils/Global_ID.php
Labels: merge

#682 Accurate Times for different timezones
  src/Tribe/Date_Utils.php
  src/Tribe/Timezones.php
Labels: merge
