Repository the-events-calendar/tribe-common, pull requests merged in 2018-06, with the labels that each got.

#714 Fix/106751 merge etr into 18.09
  .gitignore
  lang/tribe-common-af.po
  lang/tribe-common-ar.po
  lang/tribe-common-bg_BG.po
  lang/tribe-common-ca.po
  lang/tribe-common-cs_CZ.po
  lang/tribe-common-da_DK.po
  lang/tribe-common-de_DE.mo
  lang/tribe-common-de_DE.po
  lang/tribe-common-el.po
  lang/tribe-common-en_GB.po
  lang/tribe-common-es_ES.po
  lang/tribe-common-et.po
  lang/tribe-common-fi.po
  lang/tribe-common-fr_CA.po
  lang/tribe-common-fr_FR.po
  lang/tribe-common-hu_HU.po
  lang/tribe-common-id_ID.po
  lang/tribe-common-is_IS.po
  lang/tribe-common-it_IT.po
  lang/tribe-common-lt_LT.po
  lang/tribe-common-lv.po
  lang/tribe-common-nb_NO.po
  lang/tribe-common-nl_NL.po
  lang/tribe-common-pl_PL.po
  lang/tribe-common-pt_BR.mo
  lang/tribe-common-pt_BR.po
  lang/tribe-common-pt_PT.po
  lang/tribe-common-ro_RO.po
  lang/tribe-common-ru_RU.po
  lang/tribe-common-sk_SK.po
  lang/tribe-common-sl_SI.po
  lang/tribe-common-sr_RS.po
  lang/tribe-common-sv_SE.po
  lang/tribe-common-tr_TR.po
  lang/tribe-common-zh_CN.po
  lang/tribe-common-zh_TW.po
  lang/tribe-common.pot
  package.json
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Plugins_API.php
  src/Tribe/Utils/Global_ID.php
  src/resources/images/spirit-animal.png
  src/resources/js/dependency.js
  src/resources/js/dependency.min.js
  src/resources/js/dropdowns.js
  src/resources/js/dropdowns.min.js
  src/resources/js/validation.js
  src/resources/js/validation.min.js
  tests/wpunit/Tribe/Utils/Global_ID_Test.php
  tribe-common.php
  vendor/tooltipster/tooltipster.bundle.css
  vendor/tooltipster/tooltipster.bundle.js
  vendor/tooltipster/tooltipster.bundle.min.css
  vendor/tooltipster/tooltipster.bundle.min.js
  vendor/tooltipster/tooltipster.main.css
  vendor/tooltipster/tooltipster.main.js
  vendor/tooltipster/tooltipster.main.min.css
  vendor/tooltipster/tooltipster.main.min.js
Labels: merge

#715 Fix PHP warning in Help page
  readme.txt
  src/Tribe/Admin/Help_Page.php
Labels: merge

#718 Allow more empty validation handling
  readme.txt
  src/Tribe/Validator/Base.php
  tests/wpunit/Tribe/Validator/BaseTest.php
Labels: merge

#717 Add notices related to PHP minimum versions
  readme.txt
  src/Tribe/Admin/Notice/Php_Version.php
  src/Tribe/Main.php
Labels: code review, enhance

#721 Bump release date
  readme.txt
  src/Tribe/Admin/Notice/Php_Version.php
Labels: merge

#722 Handle the case where post_date and post_date_gmt are not coherent
  src/Tribe/Change_Authority/Post_Base.php
Labels: merge

#724 #106000 - move method to common to sanitize a multidimensional array
  readme.txt
  src/Tribe/Utils/Array.php
Labels: code review, merge

#716 Add base REST API repository class
  src/Tribe/REST/Post_Repository.php
  src/Tribe/Utils/Global_ID.php
Labels: merge

#720 Change how we handle uc_first_letter()
  src/Tribe/Utils/Post_Root_Pool.php
Labels: merge

#726 Version Bump for QA
  src/Tribe/Main.php
Labels: merge

#725 Add filter for tribe plugins get list function in Tribe__Plugins
  readme.txt
  src/Tribe/Plugins.php
Labels: merge

#727 Cherry pick is_not_null and some other things from RER to allow empty rest api args usage
  readme.txt
  src/Tribe/Validator/Base.php
  tests/wpunit/Tribe/Validator/BaseTest.php
Labels: merge

#728 add a `list_to_array` conversion function
  src/Tribe/Validator/Base.php
Labels: merge
