Repository the-events-calendar/tribe-common, pull requests merged in 2018-11, with the labels that each got.

#796 ⌗114903 Black Friday 2018 Admin Notice
  readme.txt
  src/Tribe/Admin/Notice/Marketing.php
  src/Tribe/Admin/Notices.php
  src/Tribe/Main.php
  src/admin-views/notices/tribe-bf-2018-et.php
  src/admin-views/notices/tribe-bf-2018-general.php
  src/admin-views/notices/tribe-bf-2018-tec.php
  src/resources/css/tribe-common-admin.css
  src/resources/css/tribe-common-admin.min.css
  src/resources/postcss/tribe-common-admin.pcss
Labels: code review, merge

#804 ⌗115286 Datepicker i18n Support
  readme.txt
  src/Tribe/Main.php
Labels: code review, merge

#802 Add support for update and delete operations, promises
  src/Tribe/Process/Queue.php
  src/Tribe/Promise.php
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Interface.php
  src/Tribe/Repository/Read_Interface.php
  src/Tribe/Repository/Update_Interface.php
  src/Tribe/Service_Providers/Processes.php
  src/Tribe/Utils/Callback.php
  tests/_data/classes/Test_Class.php
  tests/_data/test-functions.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/PromiseTest.php
  tests/wpunit/Tribe/Repository/DeleteTest.php
  tests/wpunit/Tribe/Repository/UpdateTest.php
Labels: merge

#805 ⌗117208 Gutenberg Release Admin Notice
  src/Tribe/Admin/Notice/Marketing.php
  src/admin-views/notices/tribe-gutenberg-release.php
  src/resources/images/gutenberg-admin-notice-TEC.png
  src/resources/images/gutenberg-admin-notice-tickets.png
Labels: merge

#809 Add Array utility methods.
  src/Tribe/Repository/Update_Interface.php
  src/Tribe/Utils/Array.php
Labels: merge

#810 M18.16: Fix Typo
  src/Tribe/Admin/Notice/Marketing.php
Labels: merge

#812 More save / set args handling, plus tests
  src/Tribe/Image/Uploader.php
  src/Tribe/Repository.php
  tests/wpunit/Tribe/Repository/UpdateTest.php
Labels: merge

#814 Fix/externals
  src/modules/data/index.js
  src/modules/store/index.js
  webpack.config.js
Labels: merge

#813 Support render and display context
  src/Tribe/Date_Utils.php
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Read_Interface.php
Labels: merge

#816 Feature/116745 tsm tooltips
  src/resources/css/tribe-common-admin.css
  src/resources/js/tribe-common.js
  src/resources/js/tribe-common.min.js
  src/resources/postcss/tribe-common-admin.pcss
Labels: merge

#817 Update WPRest function and toMoment function
  src/modules/utils/api.js
  src/modules/utils/moment.js
Labels: merge

#819 Add tribe_cache_expiration filter
  readme.txt
  src/Tribe/Cache.php
Labels: merge

#823 Add new plugins constants for tickets and tickets+
  src/modules/data/plugins/constants.js
Labels: merge

#830 Expose API as part of the utils from `common`
  src/modules/utils/index.js
Labels: merge

#829 Add missing functions from merge
  src/Tribe/Editor.php
Labels: merge

#828 Tickets block Clean Up
  src/modules/elements/image-upload/style.pcss
  src/modules/elements/input/style.pcss
  src/modules/elements/select/style.pcss
  src/modules/elements/time-picker/style.pcss
  src/modules/utils/globals.js
Labels: merge

#826 Add methods required to support ical-tec implementation
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Read_Interface.php
  tests/wpunit/Tribe/Repository/ReadTest.php
Labels: merge

#832 fix blue shadow for creatable select
  readme.txt
  src/modules/elements/creatable-select/style.pcss
Labels: merge

#831 ⌗116124 Only Invalidate Cache When Tribe Options are Updated
  readme.txt
  src/Tribe/Cache_Listener.php
Labels: merge

#838 Revert "Add tribe_cache_expiration filter"
  readme.txt
  src/Tribe/Cache.php
Labels: merge

#839 Fix/118379 recurrence child sidebar
  src/modules/components/plugin-block-hooks/component.js
  src/modules/components/plugin-block-hooks/style.pcss
Labels: merge

#840 Merge Hotfix into M18.17 Staging Branch
  package.json
  readme.txt
  src/Tribe/Context.php
  src/Tribe/Main.php
  tribe-common.php
Labels: code review

#843 Update snapshot tests
  src/modules/components/plugin-block-hooks/__tests__/__snapshots__/plugin-block-hooks.spec.js.snap
Labels: merge

#845 Import styles from time picker into `common` instead of TEC
  src/modules/elements/day-picker-input/element.js
Labels: code review

#836 Fix: Remove the invalid license key notice for Products with empty keys
  readme.txt
  src/Tribe/PUE/Notices.php
Labels: merge

#844 Localize variables used in the editor in `common` instead of TEC
  src/Tribe/Editor.php
  src/Tribe/Editor/Assets.php
  src/Tribe/Editor/Configuration.php
  src/Tribe/Editor/Configuration_Interface.php
  src/Tribe/Editor/Provider.php
  src/modules/store/middlewares/request/wp-request.js
  src/modules/utils/__tests__/__snapshots__/globals.test.js.snap
  src/modules/utils/__tests__/globals.test.js
  src/modules/utils/globals.js
Labels: merge

#848 Updating the mascot
  src/resources/images/mascot.png
Labels: merge

#846 Spotfix/sync mr
  readme.txt
  src/Tribe/Cache_Listener.php
  src/Tribe/PUE/Notices.php
Labels: merge

#849 Fix/rsvp tickets styles
  src/modules/elements/button/style.pcss
  src/modules/elements/image-upload/style.pcss
  src/modules/elements/label-with-link/style.pcss
Labels: merge

#847 Add tribe_cache_expiration filter
  readme.txt
  src/Tribe/Cache.php
Labels: merge

#850 Fix tec global
  src/modules/utils/globals.js
Labels: merge

#851 Set release version number
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Main.php
  tribe-common.php
Labels: merge

#842 Allow repositories and decorators to get/set query controller
  src/Tribe/Date_Utils.php
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Interface.php
  src/Tribe/Timezones.php
Labels: merge

#853 Update i18n files
  lang/tribe-common-af.po
  lang/tribe-common-ar.po
  lang/tribe-common-bg_BG.po
  lang/tribe-common-ca.po
  lang/tribe-common-cs_CZ.po
  lang/tribe-common-da_DK.po
  lang/tribe-common-de_DE.mo
  lang/tribe-common-de_DE.po
  lang/tribe-common-el.po
  lang/tribe-common-en_GB.po
  lang/tribe-common-es_ES.mo
  lang/tribe-common-es_ES.po
  lang/tribe-common-et.po
  lang/tribe-common-fi.po
  lang/tribe-common-fr_CA.mo
  lang/tribe-common-fr_CA.po
  lang/tribe-common-fr_FR.mo
  lang/tribe-common-fr_FR.po
  lang/tribe-common-hu_HU.mo
  lang/tribe-common-hu_HU.po
  lang/tribe-common-id_ID.po
  lang/tribe-common-is_IS.po
  lang/tribe-common-it_IT.mo
  lang/tribe-common-it_IT.po
  lang/tribe-common-ja.mo
  lang/tribe-common-ja.po
  lang/tribe-common-lt_LT.po
  lang/tribe-common-lv.po
  lang/tribe-common-nb_NO.po
  lang/tribe-common-nl_NL.po
  lang/tribe-common-pl_PL.po
  lang/tribe-common-pt_BR.mo
  lang/tribe-common-pt_BR.po
  lang/tribe-common-pt_PT.po
  lang/tribe-common-ro_RO.po
  lang/tribe-common-ru_RU.po
  lang/tribe-common-sk_SK.po
  lang/tribe-common-sl_SI.po
  lang/tribe-common-sr_RS.po
  lang/tribe-common-sv_SE.po
  lang/tribe-common-tr_TR.po
  lang/tribe-common-zh_CN.po
  lang/tribe-common-zh_TW.po
  package-lock.json
  package.json
  readme.txt
Labels: merge

#824 Removed closing parentheses
  src/Tribe/Field.php
Labels: merge

#859 Fix > Add rule/Add exception blocks interfere with series end dropdown
  src/modules/elements/select/style.pcss
Labels: merge

#858 Fix/117446 tec date format
  src/modules/utils/globals.js
Labels: code review

#862 Fix/119044 is plugin active for network
  readme.txt
  src/Tribe/PUE/Checker.php
Labels: code review, merge

#863 Fix font family for time picker
  src/modules/elements/time-picker/style.pcss
Labels: merge

#856 Add in recurrence icon
  src/modules/icons/recurrence.svg
Labels: merge

#865 Sync hotfix with master
  lang/tribe-common-af.po
  lang/tribe-common-ar.po
  lang/tribe-common-bg_BG.po
  lang/tribe-common-ca.po
  lang/tribe-common-cs_CZ.po
  lang/tribe-common-da_DK.po
  lang/tribe-common-de_DE.po
  lang/tribe-common-el.po
  lang/tribe-common-en_GB.po
  lang/tribe-common-es_ES.po
  lang/tribe-common-et.po
  lang/tribe-common-fi.po
  lang/tribe-common-fr_CA.po
  lang/tribe-common-fr_FR.po
  lang/tribe-common-hu_HU.po
  lang/tribe-common-id_ID.po
  lang/tribe-common-is_IS.po
  lang/tribe-common-it_IT.po
  lang/tribe-common-ja.po
  lang/tribe-common-lt_LT.po
  lang/tribe-common-lv.po
  lang/tribe-common-nb_NO.po
  lang/tribe-common-nl_NL.po
  lang/tribe-common-pl_PL.po
  lang/tribe-common-pt_BR.po
  lang/tribe-common-pt_PT.po
  lang/tribe-common-ro_RO.po
  lang/tribe-common-ru_RU.po
  lang/tribe-common-sk_SK.po
  lang/tribe-common-sl_SI.po
  lang/tribe-common-sr_RS.po
  lang/tribe-common-sv_SE.po
  lang/tribe-common-tr_TR.po
  lang/tribe-common-zh_CN.po
  lang/tribe-common-zh_TW.po
  lang/tribe-common.pot
  readme.txt
  src/Tribe/Main.php
  src/Tribe/PUE/Checker.php
  src/Tribe/PUE/Notices.php
  tribe-common.php
Labels: code review, merge

#864 Sync hotfixes with MR18.17
  lang/tribe-common-af.po
  lang/tribe-common-ar.po
  lang/tribe-common-bg_BG.po
  lang/tribe-common-ca.po
  lang/tribe-common-cs_CZ.po
  lang/tribe-common-da_DK.po
  lang/tribe-common-de_DE.po
  lang/tribe-common-el.po
  lang/tribe-common-en_GB.po
  lang/tribe-common-es_ES.po
  lang/tribe-common-et.po
  lang/tribe-common-fi.po
  lang/tribe-common-fr_CA.po
  lang/tribe-common-fr_FR.po
  lang/tribe-common-hu_HU.po
  lang/tribe-common-id_ID.po
  lang/tribe-common-is_IS.po
  lang/tribe-common-it_IT.po
  lang/tribe-common-ja.po
  lang/tribe-common-lt_LT.po
  lang/tribe-common-lv.po
  lang/tribe-common-nb_NO.po
  lang/tribe-common-nl_NL.po
  lang/tribe-common-pl_PL.po
  lang/tribe-common-pt_BR.po
  lang/tribe-common-pt_PT.po
  lang/tribe-common-ro_RO.po
  lang/tribe-common-ru_RU.po
  lang/tribe-common-sk_SK.po
  lang/tribe-common-sl_SI.po
  lang/tribe-common-sr_RS.po
  lang/tribe-common-sv_SE.po
  lang/tribe-common-tr_TR.po
  lang/tribe-common-zh_CN.po
  lang/tribe-common-zh_TW.po
  lang/tribe-common.pot
  readme.txt
  src/Tribe/PUE/Checker.php
  src/Tribe/PUE/Notices.php
Labels: code review, merge
