Repository the-events-calendar/tribe-common, pull requests merged in 2018-12, with the labels that each got.

#857 Clear the cache if the permalink structure is updated
  src/Tribe/Cache_Listener.php
Labels: code review, merge

#866 set cursor to default when button disabled
  src/modules/elements/button/style.pcss
Labels: merge

#867 add default times to globals
  src/modules/utils/globals.js
Labels: merge

#868 Sync `master`
  lang/tribe-common-af.po
  lang/tribe-common-ar.po
  lang/tribe-common-bg_BG.po
  lang/tribe-common-ca.po
  lang/tribe-common-cs_CZ.po
  lang/tribe-common-da_DK.po
  lang/tribe-common-de_DE.po
  lang/tribe-common-el.po
  lang/tribe-common-en_GB.po
  lang/tribe-common-es_ES.po
  lang/tribe-common-et.po
  lang/tribe-common-fi.po
  lang/tribe-common-fr_CA.po
  lang/tribe-common-fr_FR.po
  lang/tribe-common-hu_HU.po
  lang/tribe-common-id_ID.po
  lang/tribe-common-is_IS.po
  lang/tribe-common-it_IT.po
  lang/tribe-common-ja.po
  lang/tribe-common-lt_LT.po
  lang/tribe-common-lv.po
  lang/tribe-common-nb_NO.po
  lang/tribe-common-nl_NL.po
  lang/tribe-common-pl_PL.po
  lang/tribe-common-pt_BR.po
  lang/tribe-common-pt_PT.po
  lang/tribe-common-ro_RO.po
  lang/tribe-common-ru_RU.po
  lang/tribe-common-sk_SK.po
  lang/tribe-common-sl_SI.po
  lang/tribe-common-sr_RS.po
  lang/tribe-common-sv_SE.po
  lang/tribe-common-tr_TR.po
  lang/tribe-common-zh_CN.po
  lang/tribe-common-zh_TW.po
  lang/tribe-common.pot
  readme.txt
  src/Tribe/Main.php
  src/Tribe/PUE/Checker.php
  src/Tribe/PUE/Notices.php
  tribe-common.php
Labels: merge

#869 Use `tribe_plugins_loaded` as hook to register assets
  readme.txt
  src/Tribe/Editor/Assets.php
Labels: merge

#871 Call Static method using `call_user_func` avoiding `T_PAAMAYIM_NEKUDOTAYIM`
  src/Tribe/Process/Handler.php
Labels: code review, merge

#874 Avoid boolval() as it was introduced in PHP 5.5
  src/Tribe/Editor/Meta.php
Labels: merge

#873 Release/m18.17
  package.json
  readme.txt
  src/Tribe/Feature_Detection.php
  src/Tribe/Field.php
  src/Tribe/Main.php
  src/Tribe/Process/Handler.php
  src/Tribe/Process/Tester.php
  tribe-common.php
Labels: merge

#875 Add in missing defaultTimes global
  src/modules/utils/globals.js
Labels: code review

#876 Prevent T_LIST errors
  src/Tribe/Repository/Query_Filters.php
Labels: merge

#878 Spotfix/merge m18.18
  lang/tribe-common-af.po
  lang/tribe-common-ar.po
  lang/tribe-common-bg_BG.po
  lang/tribe-common-ca.po
  lang/tribe-common-cs_CZ.po
  lang/tribe-common-da_DK.po
  lang/tribe-common-de_DE.po
  lang/tribe-common-el.po
  lang/tribe-common-en_GB.po
  lang/tribe-common-es_ES.po
  lang/tribe-common-et.po
  lang/tribe-common-fi.po
  lang/tribe-common-fr_CA.po
  lang/tribe-common-fr_FR.po
  lang/tribe-common-hu_HU.po
  lang/tribe-common-id_ID.po
  lang/tribe-common-is_IS.po
  lang/tribe-common-it_IT.po
  lang/tribe-common-ja.po
  lang/tribe-common-lt_LT.po
  lang/tribe-common-lv.po
  lang/tribe-common-nb_NO.po
  lang/tribe-common-nl_NL.po
  lang/tribe-common-pl_PL.po
  lang/tribe-common-pt_BR.po
  lang/tribe-common-pt_PT.po
  lang/tribe-common-ro_RO.po
  lang/tribe-common-ru_RU.po
  lang/tribe-common-sk_SK.po
  lang/tribe-common-sl_SI.po
  lang/tribe-common-sr_RS.po
  lang/tribe-common-sv_SE.po
  lang/tribe-common-tr_TR.po
  lang/tribe-common-zh_CN.po
  lang/tribe-common-zh_TW.po
  lang/tribe-common.pot
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Editor/Assets.php
  src/Tribe/Editor/Meta.php
  src/Tribe/Feature_Detection.php
  src/Tribe/Field.php
  src/Tribe/Main.php
  src/Tribe/PUE/Checker.php
  src/Tribe/PUE/Notices.php
  src/Tribe/Process/Handler.php
  src/Tribe/Process/Tester.php
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Query_Filters.php
  src/modules/utils/globals.js
  tribe-common.php
Labels: merge

#882 Prevent Tester from firing too many requests
  readme.txt
  src/Tribe/Feature_Detection.php
  src/Tribe/Service_Providers/Processes.php
Labels: merge

#884 use isMoment rather than instanceof
  src/modules/utils/moment.js
Labels: merge

#885 Remove version number from `tribe-common.php`
  tribe-common.php
Labels: code review, merge

#883 Register blocks in `common` instead of TEC
  readme.txt
  src/Tribe/Editor/Provider.php
Labels: code review, merge

#888 Make sure `array_combine` operates on non empty arrays
  readme.txt
  src/Tribe/Settings.php
Labels: merge

#881 Fix the tooltip taking the full witdh
  src/modules/elements/tooltip/element.js
  src/modules/elements/tooltip/style.pcss
Labels: merge

#889 Release/m18.18
  readme.txt
  src/Tribe/Editor/Provider.php
  src/Tribe/Settings.php
Labels: merge

#892 ⌗119452 Ensure Admin CSS is Always Loaded Along with Notices
  readme.txt
  src/Tribe/PUE/Notices.php
Labels: code review, merge

#894 Blocks Inactive on TEC deactivated
  readme.txt
  src/Tribe/Editor.php
  src/Tribe/Editor/Utils.php
Labels: merge

#890 ⌗117795 TEC and ET Welcome Page Refreshes
  readme.txt
  src/resources/css/tribe-common-admin.css
  src/resources/css/tribe-common-admin.min.css
  src/resources/postcss/tribe-common-admin.pcss
Labels: code review, merge

#895 Add the Array::add_prefixed_keys_to method
  src/Tribe/Utils/Array.php
Labels: merge

#896 Revert #881
  src/modules/elements/tooltip/element.js
  src/modules/elements/tooltip/style.pcss
Labels: merge

#897 Move id before save so save hook can reference it
  codeception.dist.yml
  src/Tribe/Process/Queue.php
Labels: merge

#898 Revert "⌗117795 TEC and ET Welcome Page Refreshes"
  readme.txt
  src/resources/css/tribe-common-admin.css
  src/resources/css/tribe-common-admin.min.css
  src/resources/postcss/tribe-common-admin.pcss
Labels: code review, merge

#899 WIP: support single instance edit/break-out
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Read_Interface.php
Labels: merge

#901 Add Promoter PUE handling
  src/Tribe/Main.php
  src/Tribe/PUE/Checker.php
  src/Tribe/Promoter/Connector.php
  src/Tribe/Promoter/PUE.php
  src/Tribe/Service_Providers/Promoter_Connector.php
Labels: merge

#903 Check edit.php too in Context::is_editing_post
  src/Tribe/Context.php
Labels: code review
