Repository the-events-calendar/tribe-common, pull requests merged in 2018-09, with the labels that each got.

#764 Add tribe_tracker_post_update_links hook for on_post_updated() link update handling
  src/Tribe/Tracker.php
Labels: merge

#765 Allow `tribeEventsCountries` to contain only one entry
  readme.txt
  src/Tribe/View_Helpers.php
Labels: merge

#766 pull terms from the data when propagating
  src/Tribe/Change_Authority/Post_Base.php
Labels: code review

#767 add and use more robust fallbacks to handle empty and UTC 0 offset timezones
  src/Tribe/Timezones.php
Labels: merge

#769 Excluded trash/autodraft post_status from Tribe__Duplicate__Post searches
  readme.txt
  src/Tribe/Duplicate/Post.php
  tests/wpunit/Tribe/Duplicate/PostTest.php
Labels: merge

#768 Fix/112127 customizer css
  readme.txt
  src/Tribe/Customizer.php
Labels: merge

#772 Release/m18.13
  package.json
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Template.php
  src/Tribe/Validator/Base.php
  src/Tribe/View_Helpers.php
  src/functions/utils.php
  tests/_data/images/featured-image2.jpg
  tests/wpunit/Tribe/Validator/BaseTest.php
  tribe-common.php
Labels: code review, merge

#770 ⌗113660 Add Readme Entry for Community PR
  readme.txt
  src/Tribe/PUE/Notices.php
Labels: merge

#773 Finalize the shift to "Mascot"
  readme.txt
  src/Tribe/PUE/Notices.php
  src/resources/images/mascot.png
  src/resources/postcss/tribe-common-admin.pcss
Labels: code review, merge

#774 Handle complex image URLs on upload
  readme.txt
  src/Tribe/Image/Uploader.php
Labels: code review, merge

#775 cherry pick the fix from release/M18.14 branch
  src/Tribe/Image/Uploader.php
Labels: merge

#776 Move fields tracker update actions to shutdown
  src/Tribe/Tracker.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/TrackerTest.php
Labels: merge

#777 Add filters for custom EA origins to Global_ID
  readme.txt
  src/Tribe/Utils/Global_ID.php
Labels: merge
