Repository the-events-calendar/tribe-common, pull requests merged in 2018-05, with the labels that each got.

#684 Trim the Featured Image URL before uploading
  src/Tribe/Process/Post_Thumbnail_Setter.php
Labels: merge

#685 Udate some code used in the fix
  src/Tribe/Change_Authority/Post_Base.php
  src/Tribe/Date_Utils.php
  src/Tribe/Formatter/Base.php
Labels: code review

#686 add the set_id method to the q
  src/Tribe/Process/Queue.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Process/QueueTest.php
Labels: merge

#689 ⌗103472 Readme Updates
  readme.txt
Labels: merge

#690 More fixes to the set and get ID methods
  src/Tribe/Process/Queue.php
Labels: merge

#692 Bump Version Numbers for M18.07 Release
  package.json
  src/Tribe/Main.php
  tribe-common.php
Labels: merge

#694 Update for new datatables
  package-whitelist.json
Labels: merge

#695 Fix css paths
  src/resources/css/datatables.css
  src/resources/css/datatables.min.css
  src/resources/css/datepicker.css
  src/resources/css/datepicker.min.css
  src/resources/css/tribe-common-admin.css
  src/resources/css/tribe-common-admin.min.css
  src/resources/postcss/datatables.pcss
Labels: merge

#696 Fix strict PHP standards compat issue
  src/Tribe/Process/Handler.php
  src/Tribe/Process/Queue.php
Labels: merge

#691 Add `tribe_set_time_limit()` wrapper function to prevent errors/warnings
  readme.txt
  src/functions/template-tags/general.php
Labels: merge

#698 PHP 5.2 Compatibility
  src/Tribe/Process/Queue.php
  src/Tribe/Utils/Global_ID.php
Labels: merge

#697 Adjust the `Tribe__PUE__Checker` $stats creation regarding WordPress multisite installs
  readme.txt
  src/Tribe/PUE/Checker.php
Labels: merge

#700 Hide any errors generated by servers that don't support `set_time_limit()`
  readme.txt
  src/Tribe/Abstract_Deactivation.php
Labels: merge

#699 Spotfix typo
  src/admin-views/tribe-options-help.php
Labels: code review, merge

#701 #106239 - update version numbers for etr
  package.json
  src/Tribe/Main.php
  tribe-common.php
Labels: merge

#705 Add tribe_register_rest_route and implement it for support endpoint
  src/Tribe/Support.php
  src/functions/utils.php
Labels: merge

#704 Implement is_string_not_empty validator method, let is_string handle empty strings
  src/Tribe/Validator/Base.php
  src/Tribe/Validator/Interface.php
  tests/wpunit/Tribe/Validator/BaseTest.php
Labels: merge

#706 Add filter_null Array utility method for filtering nulls out of an array
  src/Tribe/Utils/Array.php
  tests/wpunit/Tribe/Utils/ArrayTest.php
Labels: merge

#711 #103450 - update readme release date and language files
  lang/tribe-common-af.po
  lang/tribe-common-ar.po
  lang/tribe-common-bg_BG.po
  lang/tribe-common-ca.po
  lang/tribe-common-cs_CZ.po
  lang/tribe-common-da_DK.po
  lang/tribe-common-de_DE.mo
  lang/tribe-common-de_DE.po
  lang/tribe-common-el.po
  lang/tribe-common-en_GB.po
  lang/tribe-common-es_ES.po
  lang/tribe-common-et.po
  lang/tribe-common-fi.po
  lang/tribe-common-fr_CA.po
  lang/tribe-common-fr_FR.po
  lang/tribe-common-hu_HU.po
  lang/tribe-common-id_ID.po
  lang/tribe-common-is_IS.po
  lang/tribe-common-it_IT.po
  lang/tribe-common-lt_LT.po
  lang/tribe-common-lv.po
  lang/tribe-common-nb_NO.po
  lang/tribe-common-nl_NL.po
  lang/tribe-common-pl_PL.po
  lang/tribe-common-pt_BR.mo
  lang/tribe-common-pt_BR.po
  lang/tribe-common-pt_PT.po
  lang/tribe-common-ro_RO.po
  lang/tribe-common-ru_RU.po
  lang/tribe-common-sk_SK.po
  lang/tribe-common-sl_SI.po
  lang/tribe-common-sr_RS.po
  lang/tribe-common-sv_SE.po
  lang/tribe-common-tr_TR.po
  lang/tribe-common-zh_CN.po
  lang/tribe-common-zh_TW.po
  readme.txt
Labels: code review, merge

#710 spotfix | Fix typo
  src/Tribe/Languages/Locations.php
Labels: code review, merge

#712 #107610 - fix tribe-dropdown undefined error by loading tribe-common
  readme.txt
  src/Tribe/Main.php
Labels: merge
