Repository the-events-calendar/tribe-common, pull requests merged in 2018-03, with the labels that each got.

#632 update the version of common to 4.8
  package.json
  src/Tribe/Main.php
  tribe-common.php
Labels: code review

#631 Make sure JSON strings are single lines
  readme.txt
  src/functions/template-tags/general.php
Labels: code review, merge

#634 Merge Release/M18.04 into Master
  composer.json
  lang/tribe-common-ar.po
  lang/tribe-common-ca.mo
  lang/tribe-common-de_DE.mo
  lang/tribe-common-de_DE.po
  lang/tribe-common-el.mo
  lang/tribe-common-en_GB.po
  lang/tribe-common-es_ES.mo
  lang/tribe-common-et.mo
  lang/tribe-common-et.po
  lang/tribe-common-fi.mo
  lang/tribe-common-fr_CA.mo
  lang/tribe-common-fr_FR.mo
  lang/tribe-common-fr_FR.po
  lang/tribe-common-id_ID.mo
  lang/tribe-common-id_ID.po
  lang/tribe-common-is_IS.mo
  lang/tribe-common-lt_LT.mo
  lang/tribe-common-pl_PL.mo
  lang/tribe-common-pt_BR.mo
  lang/tribe-common-ro_RO.mo
  lang/tribe-common-ru_RU.mo
  lang/tribe-common-sk_SK.po
  lang/tribe-common-sl_SI.po
  lang/tribe-common-sr_RS.mo
  lang/tribe-common-sr_RS.po
  lang/tribe-common-sv_SE.po
  lang/tribe-common-tr_TR.mo
  lang/tribe-common-tr_TR.po
  lang/tribe-common-zh_CN.mo
  lang/tribe-common-zh_CN.po
  lang/tribe-common-zh_TW.po
  package.json
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Timezones.php
  src/admin-views/tribe-options-general.php
  src/functions/template-tags/general.php
  src/functions/utils.php
  src/resources/images/donate-link-pro-screenshot.jpg
  src/resources/images/donate-link-screenshot.jpg
  src/resources/images/donate-link-screenshot.png
  tribe-common.php
Labels: merge

#633 100944 Remove Unnecessary `type` Attrs
  src/Tribe/Asset/Data.php
  src/Tribe/Assets_Pipeline.php
  src/Tribe/Customizer.php
Labels: merge, needs release

#635 Spotfix: Bump Version Numbers to Create M18.05 Release Branch
  package.json
  readme.txt
  src/Tribe/Main.php
  tribe-common.php
Labels: merge

#636 Spotfix/update common
  composer.json
  lang/tribe-common-ar.po
  lang/tribe-common-ca.mo
  lang/tribe-common-de_DE.mo
  lang/tribe-common-de_DE.po
  lang/tribe-common-el.mo
  lang/tribe-common-en_GB.po
  lang/tribe-common-es_ES.mo
  lang/tribe-common-et.mo
  lang/tribe-common-et.po
  lang/tribe-common-fi.mo
  lang/tribe-common-fr_CA.mo
  lang/tribe-common-fr_FR.mo
  lang/tribe-common-fr_FR.po
  lang/tribe-common-id_ID.mo
  lang/tribe-common-id_ID.po
  lang/tribe-common-is_IS.mo
  lang/tribe-common-lt_LT.mo
  lang/tribe-common-pl_PL.mo
  lang/tribe-common-pt_BR.mo
  lang/tribe-common-ro_RO.mo
  lang/tribe-common-ru_RU.mo
  lang/tribe-common-sk_SK.po
  lang/tribe-common-sl_SI.po
  lang/tribe-common-sr_RS.mo
  lang/tribe-common-sr_RS.po
  lang/tribe-common-sv_SE.po
  lang/tribe-common-tr_TR.mo
  lang/tribe-common-tr_TR.po
  lang/tribe-common-zh_CN.mo
  lang/tribe-common-zh_CN.po
  lang/tribe-common-zh_TW.po
  readme.txt
  src/Tribe/Timezones.php
  src/admin-views/tribe-options-general.php
  src/functions/template-tags/general.php
  src/functions/utils.php
  src/resources/images/donate-link-pro-screenshot.jpg
  src/resources/images/donate-link-screenshot.jpg
  src/resources/images/donate-link-screenshot.png
Labels: merge

#637 Accessibility CSS
  src/Tribe/Main.php
  src/resources/css/accessibility.css
  src/resources/css/accessibility.min.css
  src/resources/postcss/accessibility.pcss
Labels: code review, merge

#626 Fix the order of run for cron schedule/hook code
  src/Tribe/Cron.php
  src/Tribe/Main.php
Labels: merge

#639 Merge Release 17.9 into Master
  lang/tribe-common-af.po
  lang/tribe-common-ar.po
  lang/tribe-common-bg_BG.po
  lang/tribe-common-ca.po
  lang/tribe-common-cs_CZ.po
  lang/tribe-common-da_DK.po
  lang/tribe-common-de_DE.po
  lang/tribe-common-el.po
  lang/tribe-common-en_GB.po
  lang/tribe-common-es_ES.po
  lang/tribe-common-et.po
  lang/tribe-common-fi.po
  lang/tribe-common-fr_CA.po
  lang/tribe-common-fr_FR.po
  lang/tribe-common-hu_HU.po
  lang/tribe-common-id_ID.po
  lang/tribe-common-is_IS.po
  lang/tribe-common-it_IT.po
  lang/tribe-common-lt_LT.po
  lang/tribe-common-lv.po
  lang/tribe-common-nb_NO.po
  lang/tribe-common-nl_NL.po
  lang/tribe-common-pl_PL.po
  lang/tribe-common-pt_BR.po
  lang/tribe-common-pt_PT.po
  lang/tribe-common-ro_RO.po
  lang/tribe-common-ru_RU.po
  lang/tribe-common-sk_SK.po
  lang/tribe-common-sl_SI.po
  lang/tribe-common-sr_RS.po
  lang/tribe-common-sv_SE.po
  lang/tribe-common-tr_TR.po
  lang/tribe-common-zh_CN.po
  lang/tribe-common-zh_TW.po
  lang/tribe-common.pot
  package.json
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Validate.php
  src/functions/template-tags/general.php
  src/resources/images/spirit-animal.png
  tribe-common.php
Labels: code review

#640 Add handlebars.js back to RER branch
  vendor/handlebars/handlebars.js
  vendor/handlebars/handlebars.min.js
Labels: merge

#641 99183 Remove PRO Conditional for Credit Image
  src/admin-views/tribe-options-general.php
Labels: merge

#644 Update app shop text | #101655
  readme.txt
  src/Tribe/Plugins_API.php
Labels: code review, merge

#642 Improve our Notice class to allow simpler registration calls
  src/Tribe/Admin/Notices.php
Labels: code review, merge

#645 Resolving some method and Dependency Injection problems for Main
  src/Tribe/Log/Admin.php
  src/Tribe/Main.php
  src/admin-views/tribe-options-help.php
Labels: code review, merge

#646 Avoid php errors with $work not returning because it's already been deleted
  src/Tribe/Queue.php
Labels: merge

#647 Makes sure we have proper Handlebars registred
  src/Tribe/Main.php
Labels: code review

#648 Allow skipping activation page welcome redirection with an option
  src/Tribe/Admin/Activation_Page.php
Labels: merge

#649 Missing dependency for Datatables
  src/Tribe/Main.php
Labels: merge

#650 Add wrapper function for tribe_events_get_the_excerpt
  readme.txt
  src/Tribe/JSON_LD/Abstract.php
  src/functions/utils.php
Labels: merge

#653 Make sure spacing is consistent on the headlines
  src/admin-views/app-shop.php
  src/resources/css/app-shop.css
  src/resources/css/app-shop.min.css
  src/resources/postcss/app-shop.pcss
Labels: merge

#654 Add yes_or_false conversion helper to Tribe Validator class
  src/Tribe/Validator/Base.php
Labels: merge

#655 Add support for allow_empty on formatter
  composer.lock
  src/Tribe/Formatter/Base.php
  tests/wpunit/Tribe/Formatter/BaseTest.php
  vendor/autoload_52.php
  vendor/composer/ClassLoader.php
  vendor/composer/LICENSE
  vendor/composer/autoload_framework_classmap.php
  vendor/composer/autoload_real_52.php
Labels: code review

#658 Skip when a key is not set but not required
  src/Tribe/Formatter/Base.php
Labels: merge

#659 Prevent alias php notices when passing empties
  src/Tribe/Formatter/Base.php
Labels: merge
