Repository the-events-calendar/tribe-common, pull requests merged in 2018-10, with the labels that each got.

#779 Add custom error handling in the image uploader
  src/Tribe/Image/Uploader.php
Labels: merge

#781 Update `Tribe__Admin__Help_Page::is_current_page()`
  readme.txt
  src/Tribe/Admin/Help_Page.php
Labels: code review, merge

#784 Add timezone and date utils needed for ORM.
  readme.txt
  src/Tribe/Date_Utils.php
  src/Tribe/Repository.php
  src/Tribe/Repository/Interface.php
  src/Tribe/Timezones.php
  src/functions/utils.php
Labels: code review, merge

#785 Spotfix: Replace TBDs
  src/Tribe/Image/Uploader.php
Labels: merge

#786 M18.15 Spotfix: Add Launch Date
  readme.txt
Labels: code review

#787 M18.15: Add i18n Changes
  lang/tribe-common-af.po
  lang/tribe-common-ar.po
  lang/tribe-common-bg_BG.po
  lang/tribe-common-ca.po
  lang/tribe-common-cs_CZ.po
  lang/tribe-common-da_DK.po
  lang/tribe-common-de_DE.mo
  lang/tribe-common-de_DE.po
  lang/tribe-common-el.po
  lang/tribe-common-en_GB.po
  lang/tribe-common-es_ES.mo
  lang/tribe-common-es_ES.po
  lang/tribe-common-et.po
  lang/tribe-common-fi.po
  lang/tribe-common-fr_CA.po
  lang/tribe-common-fr_FR.mo
  lang/tribe-common-fr_FR.po
  lang/tribe-common-hu_HU.mo
  lang/tribe-common-hu_HU.po
  lang/tribe-common-id_ID.po
  lang/tribe-common-is_IS.po
  lang/tribe-common-it_IT.mo
  lang/tribe-common-it_IT.po
  lang/tribe-common-ja.mo
  lang/tribe-common-ja.po
  lang/tribe-common-lt_LT.po
  lang/tribe-common-lv.po
  lang/tribe-common-nb_NO.po
  lang/tribe-common-nl_NL.po
  lang/tribe-common-pl_PL.po
  lang/tribe-common-pt_BR.mo
  lang/tribe-common-pt_BR.po
  lang/tribe-common-pt_PT.mo
  lang/tribe-common-pt_PT.po
  lang/tribe-common-ro_RO.po
  lang/tribe-common-ru_RU.po
  lang/tribe-common-sk_SK.po
  lang/tribe-common-sl_SI.po
  lang/tribe-common-sr_RS.po
  lang/tribe-common-sv_SE.po
  lang/tribe-common-tr_TR.po
  lang/tribe-common-zh_CN.po
  lang/tribe-common-zh_TW.po
  readme.txt
Labels: code review

#789 Release/m18.15
  lang/tribe-common-af.po
  lang/tribe-common-ar.po
  lang/tribe-common-bg_BG.po
  lang/tribe-common-ca.po
  lang/tribe-common-cs_CZ.po
  lang/tribe-common-da_DK.po
  lang/tribe-common-de_DE.mo
  lang/tribe-common-de_DE.po
  lang/tribe-common-el.po
  lang/tribe-common-en_GB.po
  lang/tribe-common-es_ES.mo
  lang/tribe-common-es_ES.po
  lang/tribe-common-et.po
  lang/tribe-common-fi.po
  lang/tribe-common-fr_CA.po
  lang/tribe-common-fr_FR.mo
  lang/tribe-common-fr_FR.po
  lang/tribe-common-hu_HU.mo
  lang/tribe-common-hu_HU.po
  lang/tribe-common-id_ID.po
  lang/tribe-common-is_IS.po
  lang/tribe-common-it_IT.mo
  lang/tribe-common-it_IT.po
  lang/tribe-common-ja.mo
  lang/tribe-common-ja.po
  lang/tribe-common-lt_LT.po
  lang/tribe-common-lv.po
  lang/tribe-common-nb_NO.po
  lang/tribe-common-nl_NL.po
  lang/tribe-common-pl_PL.po
  lang/tribe-common-pt_BR.mo
  lang/tribe-common-pt_BR.po
  lang/tribe-common-pt_PT.mo
  lang/tribe-common-pt_PT.po
  lang/tribe-common-ro_RO.po
  lang/tribe-common-ru_RU.po
  lang/tribe-common-sk_SK.po
  lang/tribe-common-sl_SI.po
  lang/tribe-common-sr_RS.po
  lang/tribe-common-sv_SE.po
  lang/tribe-common-tr_TR.po
  lang/tribe-common-zh_CN.po
  lang/tribe-common-zh_TW.po
  package.json
  readme.txt
  src/Tribe/Admin/Help_Page.php
  src/Tribe/Image/Uploader.php
  src/Tribe/Main.php
  tribe-common.php
Labels: merge

#788 Modify and add methods to support PRO ORM methods
  readme.txt
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Interface.php
  src/functions/utils.php
Labels: merge

#791 Fix 'relation' merging when using array_merge_recursive
  src/Tribe/Repository.php
Labels: merge

#794 Add meta_regexp_or_like and variations; Add current filter
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Read_Interface.php
  tests/wpunit/Tribe/Repository/ReadTest.php
Labels: merge

#795 Add simple meta schemas for Linked Posts for easy schema to meta filtering
  src/Tribe/Repository.php
  tests/wpunit/Tribe/Repository/ReadTest.php
Labels: merge

#792 Add cron-based fallback for handler and queue
  src/Tribe/Context.php
  src/Tribe/Feature_Detection.php
  src/Tribe/Main.php
  src/Tribe/Process/Handler.php
  src/Tribe/Process/Post_Thumbnail_Setter.php
  src/Tribe/Process/Queue.php
  src/Tribe/Process/Tester.php
  src/Tribe/Service_Providers/Processes.php
  src/functions/utils.php
  tests/_bootstrap.php
  tests/_data/classes/Dummy_Process_Handler.php
  tests/_support/Traits/Cron_Assertions.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Process/HandlerTest.php
Labels: merge

#797 Add add_simple_tax_schema_entry functionality
  src/Tribe/Repository.php
  src/Tribe/Repository/Query_Filters.php
  src/Tribe/Terms.php
  tests/wpunit/Tribe/Repository/ReadTest.php
  tests/wpunit/Tribe/TermsTest.php
Labels: merge

#798 update code to support ET and cost filters
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Read_Interface.php
  src/Tribe/Repository/Usage_Error.php
  src/Tribe/Repository/Void_Query_Exception.php
Labels: merge

#799 Do not use the network key if the plugin is not network active
  src/Tribe/PUE/Checker.php
Labels: code review, merge

#800 Add a filter to allow non-persistent cache objects to become persistent by specifying a different expiration
  src/Tribe/Cache.php
Labels: merge

#801 Fix brackets use in Processes service provider.
  src/Tribe/Service_Providers/Processes.php
Labels: merge
