Repository the-events-calendar/tribe-common, pull requests merged in 2019-09, with the labels that each got.

#1134 feat(functions/utils.php) add the tribe_get_request_vars function
  src/functions/utils.php
Labels: merge

#1135 Add modifier for for `b2--min-medium`
  src/resources/postcss/base/typography/_body.pcss
Labels: merge

#1141 B19.11 > Release tasks
  package-lock.json
  package.json
  src/Tribe/Log/Action_Logger.php
  src/Tribe/Log/Canonical_Formatter.php
  src/Tribe/Log/Monolog_Logger.php
  src/Tribe/Log/Service_Provider.php
  src/Tribe/Utils/Lazy_Events.php
  src/Tribe/Utils/Lazy_String.php
  src/Tribe/Utils/Post_Thumbnail.php
  tribe-common.php
Labels: merge

#1140 fix tooltip dependencies
  src/Tribe/Service_Providers/Tooltip.php
Labels: merge

#1138 feat(tribe-dialog): Add ability to pass button classes.
  src/Tribe/Dialog/View.php
  src/views/dialog/button.php
Labels: merge

#1137 update composer lock
  composer.lock
Labels: merge

#1145 Fix/133669 dqa bugs
  src/resources/postcss/base/_buttons.pcss
  src/resources/postcss/base/typography/_ctas.pcss
  src/resources/postcss/components/buttons/_border.pcss
  src/resources/postcss/components/buttons/_icon.pcss
  src/resources/postcss/components/buttons/_solid.pcss
Labels: merge

#1146 just 2 items should not have a comma ", and"
  src/Tribe/Admin/Notice/Plugin_Download.php
Labels: merge

#1147 add body 3 min medium class
  src/resources/postcss/base/typography/_body.pcss
Labels: merge

#1148 Fix Models and Repository issues
  src/Tribe/Models/Post_Types/Base.php
  src/Tribe/Models/Post_Types/Nothing.php
  src/Tribe/Repository.php
Labels: code review, merge

#1139 make tribe_get_install_version() handle array
  src/functions/utils.php
  tests/unit/functions/utilsTest.php
Labels: merge

#1149 Models - filter properties
  src/Tribe/Models/Post_Types/Base.php
Labels: code review

#1151 fix(Rewrite.php) allow filtering handled rewrite rules
  src/Tribe/Rewrite.php
Labels: code review, merge

#1153 Task/134057 template tests
  composer.lock
Labels: merge

#1150 Spotfix/missing space in sysinfo
  readme.txt
  src/Tribe/Languages/Locations.php
  src/Tribe/Support.php
Labels: merge

#1154 feat(Context) add locations and methods
  src/Tribe/Context.php
  src/Tribe/Context/locations.php
Labels: code review, merge

#1155 Doc/133647 pcss documentation
  src/resources/postcss/README.md
Labels: merge

#1156 Feat - void_query support
  src/Tribe/Context.php
  src/Tribe/Repository.php
  tests/wpunit/Tribe/Repository/ReadTest.php
  tests/wpunit/Tribe/RepositoryTest.php
Labels: code review

#1157 Functions - add tribe_sanitize_deep
  readme.txt
  src/Tribe/Context.php
  src/functions/utils.php
  tests/wpunit/Tribe/functions/utilsTest.php
Labels: code review

#1159 Feature/129442 implement ar fields
  package-lock.json
  src/Tribe/Dialog/View.php
  src/functions/template-tags/html.php
  src/resources/js/dialog.js
  src/resources/postcss/dialog.pcss
  src/views/dialog/alert.php
  src/views/dialog/confirm.php
  src/views/dialog/dialog.php
  src/views/dialog/modal.php
Labels: code review
