Repository the-events-calendar/tribe-common, pull requests merged in 2019-06, with the labels that each got.

#1032 Fix/update icons
  src/resources/postcss/base/_svg-icons.pcss
Labels: code review, merge

#1038 Fix/128344 more list view repairs
  src/resources/postcss/base/_all.pcss
  src/resources/postcss/base/_buttons.pcss
  src/resources/postcss/base/forms/_sliders.pcss
  src/resources/postcss/base/grid/_columns.pcss
  src/resources/postcss/components/_search.pcss
  src/resources/postcss/components/buttons/_icon.pcss
Labels: merge

#1037 Add functions and udpates required by dyn. List View
  .travis.yml
  codeception.dist.yml
  src/Tribe/Context.php
  src/Tribe/Context/locations.php
  src/Tribe/Main.php
  src/Tribe/Repository.php
  src/Tribe/Rewrite.php
  src/Tribe/Utils/Array.php
  src/functions/url.php
  tests/_support/UnitTester.php
  tests/unit.suite.dist.yml
  tests/unit/_bootstrap.php
  tests/unit/functions/urlTest.php
  tests/wpunit/Tribe/ContextTest.php
  tests/wpunit/Tribe/Utils/ArrayTest.php
  tribe-autoload.php
Labels: merge

#1040 update navigation css, remove padding from button
  src/resources/postcss/base/_buttons.pcss
  src/resources/postcss/components/_navigation.pcss
Labels: code review, merge

#1042 fix(Context): remove import of Guzzle `parse_query` function from code
  src/Tribe/Context.php
Labels: merge

#1041 More fixes to Rewrite and Context to support Pro rules
  src/Tribe/Context/locations.php
  src/Tribe/Rewrite.php
  src/Tribe/Template.php
Labels: code review

#1043 fix(Tribe__Rewrite): remove eager call to `setup`
  src/Tribe/Rewrite.php
Labels: code review

#1044 fix(context): hardcode Events-related locations strings
  readme.txt
  src/Tribe/Context/locations.php
  src/Tribe/Main.php
  tribe-common.php
Labels: merge

#1004 Generate fallback $key if AUTH_KEY is not present
  readme.txt
  src/Tribe/Promoter/Auth.php
  src/Tribe/Promoter/Connector.php
Labels: merge

#1045 fix(Context.php): remove TEC-specific locations from the locations array
  src/Tribe/Context/locations.php
Labels: merge

#1046 Set the default link color, to prevent theme overrides.
  src/resources/postcss/base/typography/_anchors.pcss
Labels: merge

#1047 Release/g19.07.1
  readme.txt
  src/Tribe/Cache_Listener.php
  src/Tribe/Context.php
  src/Tribe/Context/locations.php
  src/Tribe/Main.php
  src/Tribe/Repository.php
  src/Tribe/Repository/Interface.php
  src/Tribe/Rewrite.php
  src/Tribe/Template.php
  src/Tribe/Traits/Cache_User.php
  src/Tribe/Utils/Array.php
  src/functions/url.php
  tribe-common.php
Labels: hold

#1049 [VR] Add link color for different states
  src/resources/postcss/base/typography/_anchors.pcss
Labels: merge

#1050 [VR] fix anchor color states
  src/resources/postcss/base/typography/_anchors.pcss
Labels: merge

#1048 feat(Context.php): add the `duplicate` method
  src/Tribe/Context.php
  tests/wpunit/Tribe/ContextTest.php
Labels: merge

#1052 update codeowners
  CODEOWNERS
Labels: merge

#1054 Add postcss file for promoter.css
  composer.lock
  package-lock.json
  readme.txt
  src/Tribe/Main.php
  src/resources/postcss/promoter.pcss
  tribe-common.php
Labels: merge

#1051 Tribe Common base file can't have dependencies, it's loaded everywhere.
  composer.lock
  package-lock.json
  readme.txt
  src/Tribe/Admin/Help_Page.php
  src/Tribe/Main.php
  src/Tribe/Settings_Manager.php
  src/admin-views/tribe-options-help.php
  src/resources/js/admin/help-page.js
  src/resources/js/admin/url-fragment-scroll.js
  src/resources/js/tooltip.js
  src/resources/js/tribe-common.js
Labels: merge

#1056 Fix/129298 tab select update
  src/resources/images/icons/arrow-right.svg
  src/resources/images/icons/caret-down.svg
  src/resources/images/icons/caret-left.svg
  src/resources/images/icons/caret-right.svg
  src/resources/images/icons/caret-up.svg
  src/resources/images/icons/check.svg
  src/resources/images/icons/day.svg
  src/resources/images/icons/dropdown.svg
  src/resources/images/icons/event-mobile.svg
  src/resources/images/icons/featured-event.svg
  src/resources/images/icons/filters.svg
  src/resources/images/icons/list.svg
  src/resources/images/icons/map.svg
  src/resources/images/icons/month.svg
  src/resources/images/icons/photo.svg
  src/resources/images/icons/recurring-events.svg
  src/resources/images/icons/search.svg
  src/resources/images/icons/small-arrow.svg
  src/resources/images/icons/week.svg
  src/resources/postcss/base/_svg-icons.pcss
Labels: merge

#1034 Merge `RBE` changes
  readme.txt
  src/Tribe/Repository.php
  src/Tribe/Timezones.php
  src/Tribe/Utils/Array.php
  src/functions/template-tags/general.php
  src/functions/utils.php
  tests/unit/Tribe/Utils/ArrayTest.php
  tests/wpunit/Tribe/TimezonesTest.php
  tests/wpunit/Tribe/functions/templateTags/generalTest.php
Labels: code review

#1057 VR > List view refinements
  src/resources/postcss/base/typography/_headings.pcss
Labels: merge

#1059 Feature/128097 mobile month day updated 3
  src/resources/postcss/base/typography/_headings.pcss
Labels: merge

#1055 Release/g19.07.2
  composer.lock
  package-lock.json
  readme.txt
  src/Tribe/Main.php
  src/resources/postcss/promoter.pcss
  tribe-common.php
Labels: merge

#1062 update spacing
  src/resources/postcss/components/_navigation.pcss
Labels: merge

#1065 Fix/assets improve code and docblocks
  src/Tribe/Assets.php
  src/Tribe/Settings.php
  src/functions/template-tags/general.php
Labels: merge

#1063 Feature/129310 event date tag
  src/resources/postcss/base/grid/_rows.pcss
  src/resources/postcss/base/typography/_headings.pcss
Labels: merge

#1067 Add new filter for easier testing
  readme.txt
  src/Tribe/Editor.php
Labels: merge

#1069 Fix merge conflicts on `composer.lock`
  composer.lock
Labels: merge

#1060 Include code around PUE notice for Invalid Licenses
  readme.txt
  src/Tribe/Admin/Notice/Plugin_Download.php
  src/Tribe/Dependency.php
  src/Tribe/Main.php
  src/Tribe/PUE/Notices.php
  tests/_data/classes/Dependency/Eventbrite.php
  tests/_data/classes/Dependency/Filterbar.php
  tests/_data/classes/Dependency/Invalid.php
  tests/_data/classes/Dependency/Pro.php
  tests/wpunit/Tribe/DependencyTest.php
Labels: merge

#1068 feat(Cost_Utils.php): Add the `parse_separators` method
  readme.txt
  src/Tribe/Cost_Utils.php
  tests/wpunit/Tribe/Cost_UtilsTest.php
Labels: merge

#1064 Update catcher on Failed dependencies
  readme.txt
  src/Tribe/Dependency.php
  src/Tribe/Main.php
  src/Tribe/PUE/Notices.php
  src/Tribe/PUE/Update_Prevention.php
  src/Tribe/Service_Providers/PUE.php
Labels: merge

#1072 Modify the usage of Cache_User trait to be compatible with PHP 5.6
  readme.txt
  src/Tribe/Rewrite.php
  src/Tribe/Traits/Cache_User.php
Labels: merge

#1071 fix package lock file
  package-lock.json
Labels: merge

#1061 VR > Events Bar > Form Inputs
  src/resources/postcss/base/_svg-icons.pcss
  src/resources/postcss/base/forms/_text.pcss
  src/resources/postcss/components/_search.pcss
  src/resources/postcss/components/buttons/_solid.pcss
Labels: merge

#1066 Fix/129061 fix ctix radio checkbox labels alignment
  readme.txt
  src/admin-views/tribe-options-general.php
  src/resources/postcss/tribe-common-admin.pcss
Labels: code review

#1073 VR > Events Bar > Filters
  src/resources/postcss/base/_svg-icons.pcss
Labels: merge

#1075 Makes sure we enqueued help page values correctly
  src/Tribe/Admin/Help_Page.php
  src/Tribe/Assets.php
  src/resources/js/admin/url-fragment-scroll.js
Labels: code review

#1074 Feature/129425 search filter tab js
  src/resources/postcss/base/forms/_text.pcss
  src/resources/postcss/components/_search.pcss
Labels: merge
