Repository the-events-calendar/tribe-common, pull requests merged in 2019-04, with the labels that each got.

#973 Update release date for G19.04
  readme.txt
Labels: merge

#972 Release/g19.04
  package.json
  readme.txt
  src/Tribe/Promoter/Connector.php
  src/Tribe/Service_Providers/Promoter_Connector.php
  src/Tribe/Updater.php
  tests/integration/Updater_Test.php
Labels: merge

#976 Bail if the page has no `$download_link` to avoid console errors
  src/resources/js/admin-log-controls.js
Labels: merge

#977 Feature/123818 arf config modal
  readme.txt
  src/modules/data/forms/__tests__/reducer.test.js
  src/modules/elements/creatable-select/__tests__/__snapshots__/element.test.js.snap
  src/modules/elements/label-with-modal/element.js
  src/modules/elements/modal-button/element.js
  src/modules/elements/select/__tests__/__snapshots__/element.test.js.snap
  src/modules/hoc/__tests__/__snapshots__/with-details.test.js.snap
  src/modules/hoc/__tests__/with-details.test.js
  src/modules/hoc/__tests__/with-store.test.js
Labels: merge

#979 feat(Repository/ORM): Add action to filter the built ORM query.
  src/Tribe/Repository.php
Labels: merge

#980 Add hash method to ORM.
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Interface.php
Labels: merge

#981 Make ORM hash generation more robust.
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Interface.php
  src/Tribe/Utils/Array.php
Labels: code review

#982 Add better fetching of debug value to prevent notices
  src/Tribe/Debug_Bar/Panels/Context.php
Labels: merge

#983 Add promoter image for Add-ons screen
  src/resources/images/app-shop-promoter.jpg
Labels: code review, merge

#975 Task/promoter welcome flow
  readme.txt
  src/Tribe/Promoter/View.php
  src/views/promoter/auth.php
Labels: code review

#984 Bring over contributor code to our branch
  src/Tribe/Validate.php
Labels: merge

#985 Feature/125915 filter validate changelog
  readme.txt
  src/Tribe/Validate.php
Labels: merge

#978 feat(tribe-tooltips): Add Tooltip object and views.
  composer.lock
  package-lock.json
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Promoter/View.php
  src/Tribe/Service_Providers/Promoter_Connector.php
  src/Tribe/Service_Providers/Tooltip.php
  src/Tribe/Tooltip/View.php
  src/resources/css/tooltip.css
  src/resources/css/tooltip.min.css
  src/resources/css/tribe-common-admin.css
  src/resources/css/tribe-common-admin.min.css
  src/resources/postcss/tooltip.pcss
  src/resources/postcss/tribe-common-admin.pcss
  src/views/tooltip/tooltip.php
Labels: merge

#986 B19.04 Readme entries review
  readme.txt
Labels: code review, question

#987 Add the `where_multi` method to the ORM.
  src/Tribe/Log.php
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Interface.php
  src/Tribe/Repository/Query_Filters.php
  src/Tribe/Repository/Usage_Error.php
  tests/wpunit/Tribe/Repository/ReadMultipleFieldsTest.php
  tests/wpunit/Tribe/Repository/ReadTest.php
  tests/wpunit/Tribe/Repository/ReadTestBase.php
  tests/wpunit/_bootstrap.php
Labels: merge

#988 Adds a wrap class option to the tooltips and css to support large size
  src/Tribe/Tooltip/View.php
  src/resources/postcss/tooltip.pcss
  src/views/tooltip/tooltip.php
Labels: merge

#989 feat(Repository/ORM): Avoid query rebuilds.
  composer.json
  src/Tribe/Repository.php
  tests/wpunit.suite.dist.yml
  tests/wpunit/Tribe/Repository/ReadQueryCacheTest.php
Labels: merge

#991 Add Tribe__Repository::flush() to make it easier to reset the repository object
  src/Tribe/Repository.php
  tests/wpunit/Tribe/Repository/ReadQueryCacheTest.php
Labels: merge

#992 Release/g19.05
  composer.json
  composer.lock
  lang/tribe-common.pot
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Log.php
  src/Tribe/Main.php
  src/Tribe/Promoter/View.php
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Interface.php
  src/Tribe/Repository/Query_Filters.php
  src/Tribe/Repository/Usage_Error.php
  src/modules/data/forms/__tests__/reducer.test.js
  src/modules/elements/creatable-select/__tests__/__snapshots__/element.test.js.snap
  src/modules/elements/label-with-modal/element.js
  src/modules/elements/modal-button/element.js
  src/modules/elements/select/__tests__/__snapshots__/element.test.js.snap
  src/modules/hoc/__tests__/__snapshots__/with-details.test.js.snap
  src/modules/hoc/__tests__/with-details.test.js
  src/modules/hoc/__tests__/with-store.test.js
  src/resources/js/admin-log-controls.min.js
  src/views/promoter/auth.php
  tests/wpunit/Tribe/AdminHelpersTest.php
  tests/wpunit/Tribe/Repository/ReadMultipleFieldsTest.php
  tests/wpunit/Tribe/Repository/ReadTest.php
  tests/wpunit/Tribe/Repository/ReadTestBase.php
  tests/wpunit/Tribe/Utils/JSONTest.php
  tests/wpunit/_bootstrap.php
  tribe-common.php
  vendor/autoload.php
  vendor/autoload_52.php
  vendor/composer/autoload_commands_real.php
  vendor/composer/autoload_framework_real.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_real_52.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
Labels: merge

#994 Prevent usage of Any, since it would show private and ignored events
  src/Tribe/Log.php
  src/Tribe/Repository.php
  tests/wpunit/Tribe/Repository/ReadTest.php
  tests/wpunit/Tribe/Repository/UpdateTest.php
  tests/wpunit/_bootstrap.php
Labels: code review

#993 Changes to support Views architecture.
  src/Tribe/Context.php
  src/Tribe/Template.php
Labels: merge

#995 Add magic methods for more decorated property/method compatibility
  readme.txt
  src/Tribe/Repository/Decorator.php
Labels: merge

#996 Restore Composer autoloader
  readme.txt
  src/Tribe/Main.php
  tribe-common.php
  vendor/autoload_52.php
  vendor/composer/ClassLoader.php
  vendor/composer/LICENSE
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_real_52.php
  vendor/composer/autoload_static.php
Labels: code review

#998 Add the filter location to the Context supported locations.
  .travis.yml
  src/Tribe/Context.php
  tests/_bootstrap.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/ContextTest.php
Labels: code review

#999 Fix cron to handle EA featured image processing while importing
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Process/Handler.php
  tests/wpunit/Tribe/Process/HandlerTest.php
  tribe-common.php
Labels: merge
