Repository the-events-calendar/tribe-common, pull requests merged in 2019-12, with the labels that each got.

#1225 Fix/137526 shortcode 2019 theme
  src/resources/postcss/base/full/typography/_anchors.pcss
  src/resources/postcss/base/skeleton/grid/_rows.pcss
Labels: code review, merge

#1227 fix(Tribe__Rewrite) correctly pass the $force param down
  src/Tribe/Rewrite.php
Labels: merge

#1226 VR - Support perf. improvments step 2
  src/Tribe/Cache.php
  src/Tribe/Date_Utils.php
  src/Tribe/Models/Post_Types/Base.php
  src/Tribe/Utils/Collection_Trait.php
  src/Tribe/Utils/Lazy_Events.php
Labels: merge

#1229 feat(Date_Utils) add immutable method and tests
  src/Tribe/Date_Utils.php
  tests/wpunit/Tribe/Date_UtilsTest.php
Labels: merge

#1230 Context filter was only being triggered once
  src/Tribe/Context.php
  tests/wpunit/Tribe/ContextTest.php
Labels: code review

#1232 fix(Tribe__Context.php) cache the result of the get method
  src/Tribe/Context.php
  src/Tribe/Date_Utils.php
Labels: merge

#1234 fix(Date_Utils) correctly use timezone when building from timestamp
  src/Tribe/Date_Utils.php
  tests/wpunit/Tribe/Date_UtilsTest.php
Labels: code review

#1236 Remove old deprecated filters and actions from Customizer
  src/Tribe/Customizer.php
Labels: code review

#1239 Feature/138284 common container media queries
  src/resources/postcss/base/full/forms/_text.pcss
  src/resources/postcss/base/full/typography/_body.pcss
  src/resources/postcss/base/full/typography/_headings.pcss
  src/resources/postcss/base/skeleton/_layouts.pcss
  src/resources/postcss/base/skeleton/forms/_text.pcss
  src/resources/postcss/base/skeleton/grid/_rows.pcss
  src/resources/postcss/components/full/buttons/_border.pcss
  src/resources/postcss/components/full/buttons/_solid.pcss
  src/resources/postcss/components/skeleton/_loader.pcss
  src/resources/postcss/components/skeleton/buttons/_border.pcss
  src/resources/postcss/components/skeleton/buttons/_solid.pcss
Labels: merge

#1231 Include Translation methods to the DateTime and DateTimeImmutable
  .gitignore
  src/Tribe/Date_Utils.php
  src/Tribe/Utils/Date_I18n.php
  src/Tribe/Utils/Date_I18n_Immutable.php
  tests/wpunit/Tribe/Utils/Date_I18nTest.php
  tests/wpunit/Tribe/Utils/Date_I18n_ImmutableTest.php
Labels: code review

#1238 feat(Traits/Cache_User.php) add reset_caches method
  readme.txt
  src/Tribe/Traits/Cache_User.php
Labels: code review

#1240 Spotfix/release to container media queries
  .gitignore
  lang/tribe-common.pot
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Customizer.php
  src/Tribe/Date_Utils.php
  src/Tribe/Dialog/View.php
  src/Tribe/Main.php
  src/Tribe/Service_Providers/Dialog.php
  src/Tribe/Traits/Cache_User.php
  src/Tribe/Utils/Date_I18n.php
  src/Tribe/Utils/Date_I18n_Immutable.php
  src/functions/template-tags/html.php
  src/functions/utils.php
  src/resources/images/mascot.png
  src/resources/postcss/dialog.pcss
  src/views/dialog/alert.php
  src/views/dialog/button.php
  src/views/dialog/confirm.php
  src/views/dialog/dialog.php
  src/views/dialog/modal.php
  tests/wpunit/Tribe/Date_UtilsTest.php
  tests/wpunit/Tribe/Utils/Date_I18nTest.php
  tests/wpunit/Tribe/Utils/Date_I18n_ImmutableTest.php
  tribe-common.php
Labels: code review

#1222 feat(attendees API): Add a new function to filter by event meta keys.
  readme.txt
  src/Tribe/Repository.php
  tests/wpunit/Tribe/Repository/QuerySetTest.php
  tests/wpunit/Tribe/Repository/ReadTest.php
Labels: code review

#1237 Set the datepicker (compact) default to a more friendly setting
  readme.txt
  src/Tribe/Date_Utils.php
  src/Tribe/Utils/Date_I18n.php
  src/Tribe/Utils/Date_I18n_Immutable.php
  src/admin-views/tribe-options-display.php
  tests/wpunit/Tribe/Utils/Date_I18nTest.php
  tests/wpunit/Tribe/Utils/Date_I18n_ImmutableTest.php
Labels: code review, merge

#1241 fix(Collection_Trait.php) allow for pre (un)serialize methods
  src/Tribe/Utils/Collection_Trait.php
Labels: code review, merge

#1242 Bucket/container media queries
  src/resources/postcss/base/full/forms/_text.pcss
  src/resources/postcss/base/full/typography/_body.pcss
  src/resources/postcss/base/full/typography/_headings.pcss
  src/resources/postcss/base/skeleton/_layouts.pcss
  src/resources/postcss/base/skeleton/forms/_text.pcss
  src/resources/postcss/base/skeleton/grid/_rows.pcss
  src/resources/postcss/components/full/buttons/_border.pcss
  src/resources/postcss/components/full/buttons/_solid.pcss
  src/resources/postcss/components/skeleton/_loader.pcss
  src/resources/postcss/components/skeleton/buttons/_border.pcss
  src/resources/postcss/components/skeleton/buttons/_solid.pcss
Labels: code review, merge

#1244 If we tribe_catch_and_throw, we need to restore error handler in catch
  src/Tribe/Date_Utils.php
  tests/wpunit/Tribe/Date_UtilsTest.php
Labels: merge

#1246 Replace immutable/mutable date handling changes and resolve test issues
  src/Tribe/Utils/Date_I18n.php
  src/Tribe/Utils/Date_I18n_Immutable.php
  tests/wpunit/Tribe/Utils/Date_I18nTest.php
  tests/wpunit/Tribe/Utils/Date_I18n_ImmutableTest.php
Labels: code review

#1247 Fix/et update for rc
  src/resources/postcss/resets/skeleton/_twentyseventeen.pcss
Labels: merge
