Repository the-events-calendar/tribe-common, pull requests merged in 2019-07, with the labels that each got.

#1077 Feature/129425 search filter tab js
  src/resources/postcss/a11y/_visibility.pcss
Labels: merge

#1078 Fix/various small fixes
  src/resources/postcss/base/typography/_headings.pcss
  src/resources/postcss/components/_all.pcss
  src/resources/postcss/components/_navigation.pcss
  src/resources/postcss/components/_search.pcss
  src/resources/postcss/components/buttons/_icon.pcss
Labels: merge

#1079 Fix/72214 more correct validation error text
  readme.txt
  src/Tribe/Validate.php
Labels: merge

#1082 Updating composer.lock so that it includes tribe-common-styles
  composer.lock
Labels: code review, merge

#1083 VR > DQA Refinements
  src/resources/postcss/base/typography/_body.pcss
  src/resources/postcss/base/typography/_headings.pcss
Labels: merge

#1081 Feature/130235 theme overrides twenty nineteen
  src/resources/postcss/base/_all.pcss
  src/resources/postcss/base/_buttons.pcss
  src/resources/postcss/base/forms/_groups.pcss
  src/resources/postcss/base/forms/_selects.pcss
  src/resources/postcss/base/forms/_tabs.pcss
  src/resources/postcss/base/typography/_anchors.pcss
  src/resources/postcss/components/buttons/_border.pcss
  src/resources/postcss/components/buttons/_icon.pcss
  src/resources/postcss/components/buttons/_solid.pcss
  src/resources/postcss/resets/_twentynineteen.pcss
Labels: merge

#1080 Views v2 - Pro filters
  composer.json
  composer.lock
  src/Tribe/Template.php
Labels: merge

#1076 Add template-tag for handling element attribute class.
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Utils/Element_Classes.php
  src/functions/template-tags/html.php
  tests/wpunit/Tribe/Utils/Element_ClassesTest.php
Labels: merge

#1090 Modify Travis submodule URL replacement
  .travis.yml
Labels: code review

#1091 Use composer for PHPCS rules
  composer.json
  composer.lock
  phpcs.xml
Labels: merge

#1092 Update context class to populate at the correct time.
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Context.php
  src/Tribe/Main.php
  tribe-common.php
Labels: merge

#1094 feat(add ids to radio): Add IDs to generated radios for better target…
  readme.txt
  src/Tribe/Field.php
Labels: merge

#1096 Fix radio/check alignment for Display stylesheet
  readme.txt
  src/resources/postcss/tribe-common-admin.pcss
Labels: code review

#1097 feat(tooltip assets): Don't use the same name for two assets.
  src/Tribe/Assets.php
  src/Tribe/Main.php
  src/Tribe/Service_Providers/Tooltip.php
  src/resources/js/tooltip.js
Labels: merge

#1098 fix white links in wp-admin Plugins List
  src/resources/postcss/tribe-common-admin.pcss
Labels: merge

#1099 checkbox p on its own line
  src/resources/postcss/tribe-common-admin.pcss
Labels: merge

#1101 fix(common assets): Ensure tooltip assets get loaded on FE as well.
  src/Tribe/Main.php
  src/Tribe/Service_Providers/Tooltip.php
Labels: merge

#1087 VR Dynamic Month View - step 1
  .gitmodules
  .travis.yml
  src/Tribe/Cache.php
  src/Tribe/Cache_Listener.php
  src/Tribe/Context/locations.php
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Interface.php
  src/Tribe/Utils/Collection_Interface.php
  src/Tribe/Utils/Collection_Trait.php
  src/Tribe/Utils/Lazy_Collection.php
  src/Tribe/Utils/Post_Thumbnail.php
  tests/wpunit/Tribe/Repository/ReadTest.php
  tests/wpunit/Tribe/Utils/Lazy_CollectionTest.php
  tests/wpunit/Tribe/Utils/Post_ThumbnailTest.php
Labels: code review
