Repository the-events-calendar/tribe-common, pull requests merged in 2019-11, with the labels that each got.

#1195 Add some sanity checks
  readme.txt
  src/Tribe/Context.php
Labels: merge

#1199 VR > Recurring icon
  src/resources/postcss/base/full/_svg-icons.pcss
Labels: merge

#1200 feat(Utils/Query.php) add Query utils
  src/Tribe/Utils/Query.php
  tests/wpunit/Tribe/Utils/QueryTest.php
Labels: merge

#1202 Add month view datepicker formats
  readme.txt
  src/Tribe/Date_Utils.php
Labels: merge

#1201 Release G19.14
  package.json
  readme.txt
  src/Tribe/Context.php
  src/Tribe/Main.php
  tribe-common.php
Labels: hold

#1206 Fix/merge ar master
  package.json
Labels: code review

#1207 feat(functions) add tribe_get_query_var function
  readme.txt
  src/functions/utils.php
  tests/wpunit/Tribe/functions/utilsTest.php
Labels: code review

#1208 VR > Add TwentyTwenty compatibility
  src/resources/postcss/base/full/_buttons.pcss
  src/resources/postcss/base/full/forms/_text.pcss
  src/resources/postcss/components/full/buttons/_solid.pcss
  src/resources/postcss/resets/full/_all.pcss
  src/resources/postcss/resets/full/_twentytwenty.pcss
  src/resources/postcss/resets/skeleton/_all.pcss
  src/resources/postcss/resets/skeleton/_twentytwenty.pcss
Labels: code review

#1210 Hotfix - admin modal.
  composer.lock
  package-lock.json
  readme.txt
  src/modules/elements/modal-button/element.js
Labels: merge

#1211 Add the new functions to wrap around the_content and get_the_content
  src/Tribe/Main.php
  src/functions/template-tags/post.php
Labels: code review

#1212 Release/g19.14.1
  composer.lock
  package-lock.json
  readme.txt
  src/Tribe/Main.php
  src/modules/elements/modal-button/element.js
  tribe-common.php
Labels: hold

#1213 Add some padding at the bottom of the dialog for iOS bottom bar.
  src/resources/postcss/dialog.pcss
Labels: merge

#1214 fix(template-tags/post.php) remove blank line at start of file
  src/functions/template-tags/post.php
Labels: code review, merge

#1215 Release B19.15 into Bucket AR modal
  readme.txt
  src/functions/template-tags/post.php
Labels: code review

#1216 feat(Context) add the safe_set method
  src/Tribe/Context.php
  tests/wpunit/Tribe/ContextTest.php
Labels: code review

#1219 Perf/vr month view
  src/Tribe/Timezones.php
Labels: code review

#1220 refactor(Timezones.php) use Tribe_Cache to cache
  src/Tribe/Timezones.php
Labels: merge

#1218 Correct missing ticket block when switching
  readme.txt
  src/Tribe/Editor.php
Labels: merge

#1221 Fix readme
  readme.txt
Labels: merge

#1223 Look for Templates in the correct folder inside of themes
  src/Tribe/Template.php
Labels: code review

#1224 VR - Repository and Cache updates
  readme.txt
  src/Tribe/Cache.php
  src/Tribe/Date_Utils.php
  src/Tribe/Feature_Detection.php
  src/Tribe/Repository/Core_Read_Interface.php
  src/Tribe/Repository/Filter_Validation.php
  src/Tribe/Repository/Interface.php
  src/Tribe/Repository/Read_Interface.php
  src/Tribe/Repository/Usage_Error.php
  src/Tribe/Utils/Collection_Trait.php
Labels: merge
