Repository the-events-calendar/tribe-common, pull requests merged in 2019-03, with the labels that each got.

#955 Task/123732 promoter single event sync
  readme.txt
  src/Tribe/Promoter/Connector.php
  src/Tribe/Service_Providers/Promoter_Connector.php
Labels: merge

#956 Make sure to check for edit.php for is_editing_post
  src/Tribe/Context.php
Labels: merge

#957 Add styles for the Promoter admin icon
  src/resources/css/promoter.css
Labels: merge

#958 Merge ORM code into B19.04
  readme.txt
  src/Tribe/Context.php
  src/Tribe/Date_Utils.php
  src/Tribe/Debug_Bar/Panels/Context.php
  src/Tribe/Image/Uploader.php
  src/Tribe/Main.php
  src/Tribe/Process/Queue.php
  src/Tribe/Promise.php
  src/Tribe/Repository.php
  src/Tribe/Repository/Decorator.php
  src/Tribe/Repository/Interface.php
  src/Tribe/Repository/Query_Filters.php
  src/Tribe/Repository/Read_Interface.php
  src/Tribe/Repository/Update_Interface.php
  src/Tribe/Repository/Usage_Error.php
  src/Tribe/Repository/Void_Query_Exception.php
  src/Tribe/Service_Providers/Debug_Bar.php
  src/Tribe/Service_Providers/Processes.php
  src/Tribe/Settings_Manager.php
  src/Tribe/Terms.php
  src/Tribe/Timezones.php
  src/Tribe/Utils/Array.php
  src/Tribe/Utils/Callback.php
  src/Tribe/Utils/Collection.php
  src/Tribe/Utils/Post_Collection.php
  src/functions/query.php
  src/functions/template-tags/general.php
  src/functions/utils.php
  src/modules/elements/tooltip/style.pcss
  tests/_data/classes/TestClass.php
  tests/_data/classes/Test_Class.php
  tests/_data/test-functions.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/ContextTest.php
  tests/wpunit/Tribe/Process/QueueTest.php
  tests/wpunit/Tribe/PromiseTest.php
  tests/wpunit/Tribe/Repository/DeleteTest.php
  tests/wpunit/Tribe/Repository/ReadTest.php
  tests/wpunit/Tribe/Repository/UpdateTest.php
  tests/wpunit/Tribe/TermsTest.php
  tests/wpunit/Tribe/Utils/ArrayTest.php
  vendor/autoload_52.php
  vendor/composer/autoload_real_52.php
  vendor/composer/installed.json
  vendor/lucatume/di52/changelog.md
  vendor/lucatume/di52/src/tad/DI52/Container.php
Labels: merge

#959 Fix/121699 updater class to common
  src/Tribe/Updater.php
  tests/integration/Updater_Test.php
Labels: code review

#783 Fix `Tribe__Admin__Helpers::is_screen()` logic, with tests
  readme.txt
  src/Tribe/Admin/Helpers.php
  tests/_data/classes/WP_Screen.php
  tests/wpunit/Tribe/AdminHelpersTest.php
Labels: merge

#960 Remove background processing library dependency.
  composer.json
  composer.lock
  package-whitelist.json
  src/Tribe/Process/Handler.php
  src/Tribe/Process/Post_Thumbnail_Setter.php
  src/Tribe/Process/Queue.php
  src/Tribe/Process/Tester.php
  tests/_data/classes/Dummy_Process_Handler.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/muwpunit.suite.dist.yml
  tests/wpunit/Tribe/Process/HandlerTest.php
  tests/wpunit/Tribe/Process/QueueTest.php
  vendor/a5hleyrich/wp-background-processing/.gitignore
  vendor/a5hleyrich/wp-background-processing/README.md
  vendor/a5hleyrich/wp-background-processing/classes/wp-async-request.php
  vendor/a5hleyrich/wp-background-processing/classes/wp-background-process.php
  vendor/a5hleyrich/wp-background-processing/composer.json
  vendor/a5hleyrich/wp-background-processing/license.txt
  vendor/a5hleyrich/wp-background-processing/wp-background-processing.php
  vendor/autoload_52.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_framework_classmap.php
  vendor/composer/autoload_real_52.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
Labels: merge

#965 Fix some Repository and Promise related issues
  src/Tribe/Repository.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Repository/DeleteTest.php
  tests/wpunit/Tribe/Repository/UpdateTest.php
Labels: code review, merge

#967 Release/g19.03.3
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Main.php
  src/resources/css/accessibility.css
  src/resources/css/app-shop.css
  src/resources/css/bumpdown.css
  src/resources/css/bumpdown.min.css
  src/resources/css/buttonset.css
  src/resources/css/datatables.css
  src/resources/css/datatables.min.css
  src/resources/css/datepicker.css
  src/resources/css/datepicker.min.css
  src/resources/css/dependency.css
  src/resources/css/promoter.min.css
  src/resources/css/tribe-common-admin.css
  src/resources/css/tribe-common-admin.min.css
  src/resources/css/tribe-ui.css
  src/resources/css/tribe-ui.min.css
  src/resources/css/validation.css
  src/resources/css/validation.min.css
  src/resources/js/admin-date-preview.min.js
  src/resources/js/admin-log-controls.min.js
  src/resources/js/bumpdown.min.js
  src/resources/js/buttonset.min.js
  src/resources/js/dependency.min.js
  src/resources/js/dropdowns.min.js
  src/resources/js/notice-dismiss.min.js
  src/resources/js/pue-notices.min.js
  src/resources/js/timepicker.min.js
  src/resources/js/tribe-common.min.js
  src/resources/js/tribe-datatables.min.js
  src/resources/js/underscore-after.min.js
  src/resources/js/underscore-before.min.js
  src/resources/js/utils-camelcase.min.js
  src/resources/js/validation.min.js
  tribe-common.php
Labels: merge

#969 Add Some More Tests for JSON-Escaping Utility — #123966
  tests/wpunit/Tribe/Utils/JSONTest.php
Labels: code review, merge

#970 Keep track of whether current request is authorized by Promoter or not
  readme.txt
  src/Tribe/Promoter/Connector.php
Labels: merge

#971 Adjust priority to identify current user
  readme.txt
  src/Tribe/Service_Providers/Promoter_Connector.php
Labels: merge
