Repository the-events-calendar/tribe-common, pull requests merged in 2019-10, with the labels that each got.

#1162 Compatibility tweaks
  src/resources/postcss/dialog.pcss
Labels: merge

#1163 Added wrapper for mb_strpos
  readme.txt
  src/functions/multibyte.php
Labels: merge

#1166 feat(Context) add the get_read_key_for method
  src/Tribe/Context.php
Labels: merge

#1167 Add a default value for `tribe_ev`
  src/resources/js/dialog.js
Labels: merge

#1160 update to .env.testing.local
  .gitignore
Labels: merge

#1165 VR > Rename "Datepicker Date Format" setting.
  readme.txt
  src/admin-views/tribe-options-display.php
Labels: code review

#1171 Adding a GitHub Action to perform automated code reviews with phpcs
  .github/workflows/main.yml
Labels: merge

#1169 Define Promoter filter for Authentication early
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Promoter/Auth.php
  src/Tribe/Promoter/Connector.php
  src/Tribe/Service_Providers/Promoter.php
Labels: code review, merge

#1170 VR > Loader
  src/resources/postcss/components/_all.pcss
  src/resources/postcss/components/_loader.pcss
Labels: merge

#1175 Sync `4.9.8` into next release
  composer.lock
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Context.php
  src/Tribe/Languages/Locations.php
  src/Tribe/Main.php
  src/Tribe/Models/Post_Types/Base.php
  src/Tribe/Models/Post_Types/Nothing.php
  src/Tribe/Rewrite.php
  src/Tribe/Support.php
  src/functions/utils.php
  tribe-common.php
Labels: code review

#1176 Add eslint Workflow
  .github/workflows/eslint.yml
  .github/workflows/main.yml
  .github/workflows/phpcs.yml
Labels: merge

#1173 Update common version
  package.json
  src/Tribe/Main.php
  tribe-common.php
Labels: merge

#1181 tribe_sanitize_deep didnt handle booleans correctly
  src/functions/utils.php
Labels: code review

#1172 Release G19.13
  lang/tribe-common.pot
  package.json
  readme.txt
  src/Tribe/Main.php
  src/functions/multibyte.php
  tribe-common.php
Labels: hold

#1178 Feature/135509 common resets
  src/Tribe/Main.php
  src/resources/postcss/common-full.pcss
  src/resources/postcss/common-skeleton.pcss
  src/resources/postcss/reset.pcss
  src/resources/postcss/resets/_genesis.pcss
  src/resources/postcss/resets/full/_all.pcss
  src/resources/postcss/resets/full/_avada.pcss
  src/resources/postcss/resets/full/_divi.pcss
  src/resources/postcss/resets/full/_enfold.pcss
  src/resources/postcss/resets/full/_genesis.pcss
  src/resources/postcss/resets/full/_reset.pcss
  src/resources/postcss/resets/full/_twentynineteen.pcss
  src/resources/postcss/resets/full/_twentyseventeen.pcss
  src/resources/postcss/resets/skeleton/_all.pcss
  src/resources/postcss/resets/skeleton/_avada.pcss
  src/resources/postcss/resets/skeleton/_divi.pcss
  src/resources/postcss/resets/skeleton/_enfold.pcss
  src/resources/postcss/resets/skeleton/_genesis.pcss
  src/resources/postcss/resets/skeleton/_reset.pcss
  src/resources/postcss/resets/skeleton/_twentynineteen.pcss
  src/resources/postcss/resets/skeleton/_twentyseventeen.pcss
Labels: merge

#1182 Allow dialog buttons to be disabled.
  src/Tribe/Dialog/View.php
  src/resources/js/dialog.js
  src/views/dialog/button.php
Labels: merge

#1179 Feature/135510 common base
  src/resources/postcss/base/full/_all.pcss
  src/resources/postcss/base/full/_buttons.pcss
  src/resources/postcss/base/full/_layouts.pcss
  src/resources/postcss/base/full/_svg-icons.pcss
  src/resources/postcss/base/full/_tables.pcss
  src/resources/postcss/base/full/forms/_checkboxes-radios.pcss
  src/resources/postcss/base/full/forms/_groups.pcss
  src/resources/postcss/base/full/forms/_sliders.pcss
  src/resources/postcss/base/full/forms/_text.pcss
  src/resources/postcss/base/full/forms/_toggles.pcss
  src/resources/postcss/base/full/grid/_columns.pcss
  src/resources/postcss/base/full/grid/_rows.pcss
  src/resources/postcss/base/full/typography/_anchors.pcss
  src/resources/postcss/base/full/typography/_body.pcss
  src/resources/postcss/base/full/typography/_ctas.pcss
  src/resources/postcss/base/full/typography/_headings.pcss
  src/resources/postcss/base/full/typography/_lists.pcss
  src/resources/postcss/base/skeleton/_all.pcss
  src/resources/postcss/base/skeleton/_buttons.pcss
  src/resources/postcss/base/skeleton/_layouts.pcss
  src/resources/postcss/base/skeleton/_svg-icons.pcss
  src/resources/postcss/base/skeleton/_tables.pcss
  src/resources/postcss/base/skeleton/forms/_checkboxes-radios.pcss
  src/resources/postcss/base/skeleton/forms/_groups.pcss
  src/resources/postcss/base/skeleton/forms/_sliders.pcss
  src/resources/postcss/base/skeleton/forms/_text.pcss
  src/resources/postcss/base/skeleton/forms/_toggles.pcss
  src/resources/postcss/base/skeleton/grid/_columns.pcss
  src/resources/postcss/base/skeleton/grid/_rows.pcss
  src/resources/postcss/base/skeleton/typography/_anchors.pcss
  src/resources/postcss/base/skeleton/typography/_body.pcss
  src/resources/postcss/base/skeleton/typography/_ctas.pcss
  src/resources/postcss/base/skeleton/typography/_headings.pcss
  src/resources/postcss/base/skeleton/typography/_lists.pcss
  src/resources/postcss/common-full.pcss
  src/resources/postcss/common-skeleton.pcss
Labels: merge

#1180 Feature/135511 common components
  src/resources/postcss/common-full.pcss
  src/resources/postcss/common-skeleton.pcss
  src/resources/postcss/components/full/_all.pcss
  src/resources/postcss/components/full/_image.pcss
  src/resources/postcss/components/full/_loader.pcss
  src/resources/postcss/components/full/buttons/_border.pcss
  src/resources/postcss/components/full/buttons/_icon.pcss
  src/resources/postcss/components/full/buttons/_solid.pcss
  src/resources/postcss/components/skeleton/_all.pcss
  src/resources/postcss/components/skeleton/_image.pcss
  src/resources/postcss/components/skeleton/_loader.pcss
  src/resources/postcss/components/skeleton/buttons/_border.pcss
  src/resources/postcss/components/skeleton/buttons/_icon.pcss
  src/resources/postcss/components/skeleton/buttons/_solid.pcss
Labels: code review

#1183 Remove focus effect from close button
  composer.lock
  src/resources/postcss/dialog.pcss
Labels: merge

#1188 VR > Wild West Images > Add alt to the post thumbnail object.
  src/Tribe/Utils/Post_Thumbnail.php
Labels: merge

#1184 feat(Repository/Query_Filters.php) support after order clauses
  composer.lock
  readme.txt
  src/Tribe/Date_Utils.php
  src/Tribe/Repository.php
  src/Tribe/Repository/Query_Filters.php
  tests/wpunit/Tribe/Repository/Custom_OrderbyTest.php
  tests/wpunit/Tribe/Repository/OrderTest.php
  tests/wpunit/Tribe/Repository/Query_FiltersTest.php
Labels: code review, needs ticket

#1189 Fix/134591 list view date marker
  src/resources/postcss/base/full/typography/_anchors.pcss
Labels: code review

#1192 fix button border styles
  src/resources/postcss/components/full/buttons/_border.pcss
Labels: merge

#1191 fix(Context.php) correctly pick up not_found values
  src/Tribe/Context.php
Labels: merge

#1193 VR > Fix recurring icon.
  src/resources/postcss/base/skeleton/_svg-icons.pcss
Labels: code review

#1197 Correct name for Tribe common styles for Tooltip dep
  src/Tribe/Service_Providers/Tooltip.php
Labels: code review, merge

#1196 VR > Revert recurring icon.
  src/resources/postcss/base/skeleton/_svg-icons.pcss
Labels: merge

#1194 Feature/map view no venue
  src/resources/postcss/base/skeleton/_svg-icons.pcss
Labels: code review, merge
