Repository the-events-calendar/tribe-common, pull requests merged in 2019-08, with the labels that each got.

#1102 update hover focus active color for caret right and left
  src/resources/postcss/components/buttons/_icon.pcss
Labels: merge

#1103 feature(Repository/Query_Filters) set/unset by id
  src/Tribe/Repository/Query_Filters.php
  tests/wpunit/Tribe/Repository/Query_FiltersTest.php
Labels: merge

#1104 Feature/130237 theme overrides divi
  src/resources/postcss/base/_all.pcss
  src/resources/postcss/base/_buttons.pcss
  src/resources/postcss/base/forms/_text.pcss
  src/resources/postcss/base/forms/_toggles.pcss
  src/resources/postcss/base/typography/_anchors.pcss
  src/resources/postcss/base/typography/_ctas.pcss
  src/resources/postcss/base/typography/_lists.pcss
  src/resources/postcss/resets/_divi.pcss
Labels: merge

#1106 Feature/130233 theme overrides enfold
  src/resources/postcss/base/_all.pcss
  src/resources/postcss/base/_tables.pcss
  src/resources/postcss/base/forms/_checkboxes-radios.pcss
  src/resources/postcss/base/forms/_sliders.pcss
  src/resources/postcss/base/forms/_text.pcss
  src/resources/postcss/base/forms/_toggles.pcss
  src/resources/postcss/base/typography/_anchors.pcss
  src/resources/postcss/resets/_enfold.pcss
Labels: merge

#1105 Modify the CSS to prevent problematic mascot image to be larger.
  package-lock.json
  readme.txt
  src/Tribe/PUE/Notices.php
  src/resources/postcss/tribe-common-admin.pcss
Labels: merge

#1108 VR > Map view (premium) > Add h7--min-medium
  src/resources/postcss/base/typography/_headings.pcss
Labels: merge

#1109 Use proper mixin
  src/resources/postcss/base/typography/_headings.pcss
Labels: merge

#1107 Simple update to lodash on Common
  package.json
  readme.txt
Labels: code review, merge

#1111 Typo on a variable name, it should be results instead of
  src/Tribe/Utils/Element_Classes.php
Labels: merge

#1117 Fix incorrect ticket number
  readme.txt
Labels: merge

#1119 New mascot!
  src/resources/images/mascot.png
Labels: merge

#1120 New mascot image
  src/resources/images/mascot.png
Labels: merge

#1121 Updating package-locak.json with a fresh npm install
  package-lock.json
Labels: merge

#1113 Views v2 - dynamic Week View support
  composer.lock
  src/Tribe/Utils/Collection_Interface.php
  src/Tribe/Utils/Lazy_Collection.php
  src/Tribe/Utils/Lazy_String.php
  src/Tribe/Utils/Post_Thumbnail.php
  tests/wpunit/Tribe/Utils/Lazy_CollectionTest.php
  tests/wpunit/Tribe/Utils/Lazy_StringTest.php
  tests/wpunit/Tribe/Utils/Post_ThumbnailTest.php
Labels: code review, merge

#1100 Release/g19.10
  lang/tribe-common.pot
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Assets.php
  src/Tribe/Field.php
  src/Tribe/Main.php
  src/Tribe/Service_Providers/Tooltip.php
  src/resources/images/mascot.png
  src/resources/js/tooltip.js
  src/resources/postcss/tribe-common-admin.pcss
  tribe-common.php
Labels: hold

#1123 feat(Logger) add Monolog support and fix async handler
  composer.json
  composer.lock
  package-whitelist.json
  readme.txt
  src/Tribe/Image/Uploader.php
  src/Tribe/Log.php
  src/Tribe/Log/Action_Logger.php
  src/Tribe/Log/Canonical_Formatter.php
  src/Tribe/Log/Monolog_Logger.php
  src/Tribe/Log/README.md
  src/Tribe/Log/Service_Provider.php
  src/Tribe/Main.php
  src/Tribe/Process/Handler.php
  src/Tribe/Process/Post_Thumbnail_Setter.php
  tests/wpunit/Tribe/Log/Action_LoggerTest.php
  tests/wpunit/Tribe/Log/Canonical_FormatterTest.php
  tests/wpunit/Tribe/Log/Monolog_LoggerTest.php
  tests/wpunit/Tribe/Log/ProviderTest.php
Labels: code review

#1130 Service provider needs to be loaded earlier, it was causing fatals on EA
  src/Tribe/Main.php
Labels: code review

#1131 build(package-whitelist.json) use correct path
  package-whitelist.json
Labels: code review

#1122 feat(version checks): Add functions to test installed version of plugins.
  readme.txt
  src/functions/utils.php
Labels: merge

#1128 fix(tribe_get_event) add and use Lazy_Events
  src/Tribe/Utils/Lazy_Collection.php
  src/Tribe/Utils/Lazy_Events.php
  src/Tribe/Utils/Lazy_String.php
  src/Tribe/Utils/Post_Thumbnail.php
  tests/wpunit/Tribe/Utils/Lazy_EventsTest.php
Labels: merge

#1125 #132279 - add trigger to update modal cart when get tickets clicked
  src/Tribe/Dialog/View.php
  src/resources/js/dialog.js
Labels: merge

#1132 Spotfix/escaping causing dialog target not found
  src/Tribe/Dialog/View.php
Labels: merge
