Repository the-events-calendar/tribe-common, pull requests merged in 2020-07, with the labels that each got.

#1398 Add the tribe_normalize_orderby function
  readme.txt
  src/functions/query.php
  tests/wpunit/Tribe/functions/queryTest.php
Labels: merge

#1399 PRMTR-404: Adjust verbosity level
  readme.txt
  src/Tribe/Promoter/Connector.php
Labels: code review

#1400 Improve the Post_Collection plucking
  readme.txt
  src/Tribe/Repository.php
  src/Tribe/Traits/With_Post_Attribute_Detection.php
  src/Tribe/Utils/Post_Collection.php
  tests/wpunit/Tribe/Utils/Post_CollectionTest.php
Labels: code review

#1402 Refactor code for smaller perf. gain
  src/Tribe/Rewrite.php
  tests/wpunit/Tribe/Repository/Custom_OrderbyTest.php
Labels: merge

#1403 Fix handling of single associative and flat maps
  src/Tribe/Utils/Post_Collection.php
  tests/wpunit/Tribe/Utils/Post_CollectionTest.php
Labels: code review, merge

#1406 Fix/tec 3543 date time block timezone
  readme.txt
  src/modules/utils/globals.js
Labels: merge

#1407 Fix/tec 3531 customizer accent color
  readme.txt
  src/Tribe/Customizer.php
Labels: code review

#1401 TCMN-85: Update process to generate promoter keys
  readme.txt
  src/Tribe/Promoter/Auth.php
  src/Tribe/Promoter/Connector.php
  src/Tribe/Promoter/PUE.php
  src/Tribe/Promoter/View.php
  src/Tribe/Service_Providers/Promoter.php
Labels: merge

#1410 Fix/ecp 450 shortcode customizer styles
  readme.txt
  src/Tribe/Customizer.php
Labels: code review

#1408 Modify HelpPage to include Virtual Events
  readme.txt
  src/Tribe/Admin/Help_Page.php
Labels: merge

#1397 Make sure we return the classes on a fail.
  readme.txt
  src/Tribe/Service_Providers/Body_Classes.php
  src/Tribe/Utils/Body_Classes.php
  tests/wpunit/Tribe/Body_ClassesTest.php
Labels: code review, merge

#1404 Add template tag to force printing of tribe_assets
  readme.txt
  src/Tribe/Assets.php
  src/Tribe/Customizer.php
  src/Tribe/Main.php
  src/functions/template-tags/general.php
  tests/_data/resources/test-script-1.js
  tests/_data/resources/test-style-1.css
  tests/wpunit/Tribe/CustomizerTest.php
  tests/wpunit/Tribe/functions/templateTags/generalTest.php
Labels: code review, merge

#1412 add filter to allow customizer for shortcodes
  readme.txt
  src/Tribe/Customizer.php
Labels: code review, merge

#1413 When using tribe_register_rest_route we default to having a __return_true to the permission callback
  readme.txt
  src/functions/utils.php
Labels: code review

#1415 Passthru, do not remove, non-scalar query args
  readme.txt
  src/Tribe/Rewrite.php
Labels: code review, merge
