Repository the-events-calendar/tribe-common, pull requests merged in 2020-01, with the labels that each got.

#1248 Fix/138649 container query documentation
  src/resources/postcss/README.md
Labels: merge

#1249 Fetch checkout at a depth high enough to be able to codesniff | PDTOOLS-67
  .github/workflows/phpcs.yml
Labels: merge

#1251 In-memory cache improvements for better performing templates | TEC-3130
  src/Tribe/Template.php
  src/functions/template-tags/date.php
  src/functions/template-tags/post.php
Labels: merge

#1252 Fix/ecp 316 shortcode display genesis
  src/resources/postcss/base/skeleton/typography/_lists.pcss
  src/resources/postcss/resets/skeleton/_genesis.pcss
Labels: code review

#1250 Fix/ecp 315 shortcode display enfold
  src/resources/postcss/base/full/forms/_checkboxes-radios.pcss
  src/resources/postcss/base/full/forms/_sliders.pcss
  src/resources/postcss/base/full/forms/_text.pcss
  src/resources/postcss/base/full/forms/_toggles.pcss
  src/resources/postcss/base/skeleton/forms/_checkboxes-radios.pcss
  src/resources/postcss/base/skeleton/forms/_text.pcss
  src/resources/postcss/base/skeleton/forms/_toggles.pcss
  src/resources/postcss/resets/full/_enfold.pcss
  src/resources/postcss/resets/skeleton/_enfold.pcss
Labels: code review

#1254 Fix/add readme entries
  readme.txt
Labels: code review

#1255 VR > Template cache improvements fix.
  src/Tribe/Template.php
Labels: code review

#1253 Common performance improvements
  src/Tribe/Assets.php
  src/Tribe/Cache.php
  src/Tribe/Cache_Listener.php
  src/Tribe/Container.php
  src/Tribe/Date_Utils.php
  src/Tribe/Main.php
  src/Tribe/Repository.php
  src/Tribe/Rewrite.php
  src/Tribe/Settings_Manager.php
  src/Tribe/Template.php
  src/Tribe/Utils/Post_Thumbnail.php
  src/Tribe/View_Helpers.php
  src/functions/template-tags/date.php
  src/functions/template-tags/general.php
  tests/wpunit/Tribe/Repository/DeleteTest.php
Labels: code review

#1256 Properly offset the week when dealing with sundays as the start of the week.
  src/Tribe/Date_Utils.php
Labels: code review

#1259 Correct Namespace for `Template::template()`
  src/Tribe/Post_Transient.php
  src/Tribe/Template.php
Labels: code review, merge

#1258 Fix/tec 3009 start end time same
  readme.txt
  src/modules/utils/moment.js
Labels: merge

#1260 update readme entry
  readme.txt
Labels: merge

#1261 Adjust the week offset calculation for week start/end
  src/Tribe/Date_Utils.php
Labels: merge

#1262 Cache timezone objects by timezone AND timestamp
  src/Tribe/Date_Utils.php
Labels: merge

#1263 Properly do the priority ordering for Assets.
  src/Tribe/Assets.php
Labels: merge

#1266 fix(Utils/Post_Thumbnail.php) serialization issue
  src/Tribe/Utils/Post_Thumbnail.php
Labels: code review

#1267 Template class changes to local context resolution
  src/Tribe/Template.php
Labels: code review

#1268 Folder list with Namespacing correct
  src/Tribe/Template.php
Labels: merge

#1269 perf(Cache.php) replace in_array w/ isset(array_flip)
  src/Tribe/Cache.php
Labels: code review

#1271 fix/TEC 3172 v2 a11y improvements
  src/resources/postcss/base/full/forms/_text.pcss
Labels: merge

#1272 fix(Rewrite.php) search post types as keys too
  src/Tribe/Rewrite.php
Labels: merge

#1273 WordPress is throwing a notice for home_url() without a slash.
  src/Tribe/Rewrite.php
Labels: merge

#1275 Merge 20.01 into 20.01.1
  lang/tribe-common.pot
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Cache.php
  src/Tribe/Cache_Listener.php
  src/Tribe/Container.php
  src/Tribe/Data.php
  src/Tribe/Main.php
  src/Tribe/Repository.php
  src/Tribe/Rewrite.php
  src/Tribe/Settings_Manager.php
  src/Tribe/Template.php
  src/Tribe/Traits/Cache_User.php
  src/Tribe/Utils/Date_I18n.php
  src/Tribe/Utils/Date_I18n_Immutable.php
  src/functions/template-tags/post.php
  src/resources/images/mascot.png
  tests/_support/Data.php
  tribe-common.php
Labels: code review
