Repository the-events-calendar/tribe-common, pull requests merged in 2020-02, with the labels that each got.

#1279 Fix - avoid fatal on Context when global query var is not set
  readme.txt
  src/Tribe/Context.php
Labels: merge

#1280 Add a helper method for fetching the datepickerFormat index
  readme.txt
  src/Tribe/Date_Utils.php
Labels: code review

#1281 Avoid camelCase filters
  src/Tribe/Date_Utils.php
Labels: merge

#1285 Fix/ecp 315 shortcode display enfold 2
  src/resources/postcss/resets/skeleton/_enfold.pcss
Labels: code review

#1286 feat(Tribe__Admin__Notices) add visibility methods to API
  readme.txt
  src/Tribe/Admin/Notices.php
Labels: merge

#1292 Add `plain_permalink` to Context and rewrite.
  readme.txt
  src/Tribe/Context/locations.php
  src/Tribe/Rewrite.php
Labels: code review, enhance

#1288 test(Repository/Query_Filters.php) add tests for orderby filter
  src/Tribe/Repository/Query_Filters.php
  tests/wpunit/Tribe/Repository/Query_FiltersTest.php
Labels: hold, merge, needs release

#1278 Validation was throwing warning for empty slug on PHP 7.3
  readme.txt
  src/Tribe/Validate.php
Labels: code review

#1276 Include a better method for handling Start/End of the day
  src/Tribe/Date_Utils.php
  tests/wpunit/Tribe/Date_UtilsTest.php
Labels: code review

#1295 JSON-LD data support work
  readme.txt
  src/Tribe/Context.php
  src/Tribe/Context/locations.php
  src/Tribe/Debug_Bar/Panels/Json_Ld.php
  src/Tribe/Service_Providers/Debug_Bar.php
  src/functions/template-tags/general.php
  tests/wpunit/Tribe/ContextTest.php
Labels: merge

#1296 Add default value for the datepicker format option.
  readme.txt
  src/Tribe/Date_Utils.php
Labels: merge

#1297 fix(Rewrite) drop non-scalar query vars from the match
  src/Tribe/Rewrite.php
Labels: merge

#1289 Common > Fix JS error on dialog.
  readme.txt
  src/Tribe/Dialog/View.php
  src/resources/js/dialog.js
Labels: merge

#1287 AR Modal > Add theme compatibility for overlaps.
  readme.txt
  src/resources/postcss/dialog.pcss
Labels: code review

#1293 fix (css): correct invalid attribute.
  src/resources/postcss/tooltip.pcss
Labels: code review

#1298 fix(Debug_Bar) class name for back-compat
  src/Tribe/Debug_Bar/Panels/Json_Ld.php
  src/Tribe/Service_Providers/Debug_Bar.php
Labels: merge

#1301 Dialog > Fix z-index issues with Safari 12
  readme.txt
  src/resources/postcss/dialog.pcss
Labels: merge

#1302 Use the default `datepickerFormat` value if the option hasn't been set yet when setting up datepicker from specific format
  readme.txt
  src/Tribe/Date_Utils.php
Labels: merge

#1306 Dependency issue and test matrix
  readme.txt
  src/Tribe/Dependency.php
  tests/_data/dependency/plugins/five/plugin.php
  tests/_data/dependency/plugins/four/plugin.php
  tests/_data/dependency/plugins/one/plugin.php
  tests/_data/dependency/plugins/three/plugin.php
  tests/_data/dependency/plugins/two/plugin.php
  tests/wpunit/Tribe/DependencyTest.php
Labels: code review, merge

#1303 Release/g20.02
  package.json
  readme.txt
  src/Tribe/Date_Utils.php
  src/Tribe/Dialog/View.php
  src/Tribe/Main.php
  src/resources/js/dialog.js
  src/resources/postcss/dialog.pcss
  tribe-common.php
Labels: hold
