Repository the-events-calendar/tribe-common, pull requests merged in 2020-09, with the labels that each got.

#1436 feat(functions/utils) add the tribe_without_filters function
  package-lock.json
  readme.txt
  src/functions/utils.php
  tests/unit/Tribe/Utils/AutoloaderTest.php
  tests/unit/functions/utilsTest.php
  tests/wpunit/Tribe/functions/utilsTest.php
Labels: code review

#1434 Add support for common fallback and aliases
  readme.txt
  src/Tribe/Template.php
  tests/wpunit/Tribe/TemplateTest.php
Labels: code review

#1435 Correct checkbox/radio colors and add hover style.
  readme.txt
  src/resources/postcss/base/full/forms/_checkboxes-radios.pcss
Labels: code review

#1437 [ET-904] Implement `tribe_doing_shortcode`
  readme.txt
  src/Tribe/Service_Providers/Shortcodes.php
  src/Tribe/Shortcode/Manager.php
  src/functions/template-tags/general.php
Labels: merge

#1428 [TCMN-88] Added support for overriding individual args for group assets
  readme.txt
  src/functions/template-tags/general.php
Labels: merge

#1438 Prevent warnings from Rest Route permission callback
  readme.txt
  src/Tribe/Support.php
Labels: code review

#1439 Add the snapshots test suite and base test case
  .travis.yml
  composer.json
  composer.lock
  tests/_support/Helper/Snapshots.php
  tests/_support/SnapshotsTester.php
  tests/snapshots.suite.dist.yml
  tests/snapshots/Snapshot_Test_Case.php
  tests/snapshots/_bootstrap.php
  tests/snapshots/views/dialog/__snapshots__/alertTest__test_w_title__0.snapshot.html
  tests/snapshots/views/dialog/__snapshots__/alertTest__test_wo_title__0.snapshot.html
  tests/snapshots/views/dialog/alertTest.php
Labels: code review, merge

#1441 Task/move icons to common
  src/views/v2/components/icons/caret-left.php
  src/views/v2/components/icons/caret-right.php
  src/views/v2/components/icons/close-alt.php
  src/views/v2/components/icons/close.php
  src/views/v2/components/icons/filter.php
  src/views/v2/components/icons/minus.php
  src/views/v2/components/icons/plus.php
  src/views/v2/components/icons/reset.php
  tests/snapshots/Views/Dialog/AlertTest.php
  tests/snapshots/Views/Dialog/__snapshots__/AlertTest__test_w_title__0.snapshot.html
  tests/snapshots/Views/Dialog/__snapshots__/AlertTest__test_wo_title__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/Caret_LeftTest.php
  tests/snapshots/Views/V2/Components/Icons/Caret_RightTest.php
  tests/snapshots/Views/V2/Components/Icons/CloseTest.php
  tests/snapshots/Views/V2/Components/Icons/Close_AltTest.php
  tests/snapshots/Views/V2/Components/Icons/FilterTest.php
  tests/snapshots/Views/V2/Components/Icons/MinusTest.php
  tests/snapshots/Views/V2/Components/Icons/PlusTest.php
  tests/snapshots/Views/V2/Components/Icons/ResetTest.php
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/Caret_LeftTest__test_render_with_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/Caret_LeftTest__test_render_without_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/Caret_RightTest__test_render_with_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/Caret_RightTest__test_render_without_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/CloseTest__test_render_with_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/CloseTest__test_render_without_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/Close_AltTest__test_render_with_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/Close_AltTest__test_render_without_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/FilterTest__test_render_with_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/FilterTest__test_render_without_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/MinusTest__test_render_with_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/MinusTest__test_render_without_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/PlusTest__test_render_with_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/PlusTest__test_render_without_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/ResetTest__test_render_with_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/ResetTest__test_render_without_classes__0.snapshot.html
Labels: merge

#1442 Fix/dqa fixes 4
  src/views/v2/components/icons/filter.php
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/FilterTest__test_render_with_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/FilterTest__test_render_without_classes__0.snapshot.html
Labels: code review

#1444 Fix/fbar 139 dropdown search
  readme.txt
  src/resources/js/dropdowns.js
Labels: code review, merge

#1449 Adding Tofu as the mascot
  src/resources/images/mascot.png
Labels: code review
