Repository the-events-calendar/tribe-common, pull requests merged in 2020-11, with the labels that each got.

#1471 Modify the code to prevent SelectWoo turning Terms into groups on the Select
  readme.txt
  src/Tribe/Ajax/Dropdown.php
Labels: code review

#1470 Need to tweak where we load the common admin styles.
  src/Tribe/Main.php
Labels: merge

#1472 update globals to reflect new config vars
  src/modules/utils/globals.js
Labels: merge

#1466 Allow removing non-persistent cache data
  src/Tribe/Cache.php
  tests/wpunit/Tribe/CacheTest.php
Labels: code review

#1476 fix mixin for visually show class
  src/resources/postcss/a11y/_visibility.pcss
Labels: code review, merge

#1478 add positioning theme override for twentytwenty
  src/resources/postcss/base/skeleton/forms/_checkboxes-radios.pcss
Labels: code review

#1480 [ETP-523] Tribe dialog > Amendments for MA
  src/Tribe/Dialog/View.php
  src/views/dialog/button.php
Labels: merge

#1477 fix(Cache.php) do not try to store strings larger than packet size
  readme.txt
  src/Tribe/Cache.php
  tests/wpunit/Tribe/CacheTest.php
Labels: merge

#1474 Update Freemius to version 2.4.1
  vendor/freemius/README.md
  vendor/freemius/assets/css/admin/account.css
  vendor/freemius/assets/css/admin/add-ons.css
  vendor/freemius/config.php
  vendor/freemius/includes/class-freemius.php
  vendor/freemius/includes/class-fs-api.php
  vendor/freemius/includes/class-fs-plugin-updater.php
  vendor/freemius/includes/class-fs-storage.php
  vendor/freemius/includes/customizer/class-fs-customizer-support-section.php
  vendor/freemius/includes/entities/class-fs-payment.php
  vendor/freemius/includes/entities/class-fs-plugin-license.php
  vendor/freemius/includes/entities/class-fs-site.php
  vendor/freemius/includes/fs-essential-functions.php
  vendor/freemius/includes/fs-plugin-info-dialog.php
  vendor/freemius/includes/i18n.php
  vendor/freemius/includes/managers/class-fs-admin-menu-manager.php
  vendor/freemius/includes/sdk/FreemiusBase.php
  vendor/freemius/includes/sdk/FreemiusWordPress.php
  vendor/freemius/includes/supplements/fs-essential-functions-1.1.7.1.php
  vendor/freemius/languages/freemius-cs_CZ.mo
  vendor/freemius/languages/freemius-da_DK.mo
  vendor/freemius/languages/freemius-en.mo
  vendor/freemius/languages/freemius-es_ES.mo
  vendor/freemius/languages/freemius-fr_FR.mo
  vendor/freemius/languages/freemius-he_IL.mo
  vendor/freemius/languages/freemius-hu_HU.mo
  vendor/freemius/languages/freemius-it_IT.mo
  vendor/freemius/languages/freemius-ja.mo
  vendor/freemius/languages/freemius-nl_NL.mo
  vendor/freemius/languages/freemius-ru_RU.mo
  vendor/freemius/languages/freemius-ta.mo
  vendor/freemius/languages/freemius.pot
  vendor/freemius/package.json
  vendor/freemius/start.php
  vendor/freemius/templates/account.php
  vendor/freemius/templates/account/partials/addon.php
  vendor/freemius/templates/account/payments.php
  vendor/freemius/templates/add-ons.php
  vendor/freemius/templates/auto-installation.php
  vendor/freemius/templates/connect.php
  vendor/freemius/templates/forms/affiliation.php
  vendor/freemius/templates/forms/deactivation/form.php
  vendor/freemius/templates/forms/license-activation.php
  vendor/freemius/templates/forms/optout.php
  vendor/freemius/templates/forms/subscription-cancellation.php
  vendor/freemius/templates/forms/trial-start.php
  vendor/freemius/templates/pricing.php
  vendor/freemius/templates/secure-https-header.php
Labels: code review, in-qa

#1482 Events list widget theme overrides
  src/resources/postcss/base/full/typography/_anchors.pcss
Labels: code review, merge

#1481 Correctly handle query arguments merge
  readme.txt
  src/Tribe/Repository.php
  src/Tribe/Utils/Array.php
  tests/wpunit/Tribe/Repository/ReadTest.php
  tests/wpunit/Tribe/Utils/ArrayTest.php
Labels: code review

#1483 Do not cache and return the serialized value
  src/Tribe/Cache.php
  tests/wpunit/Tribe/CacheTest.php
Labels: code reviews, hold

#1486 Update bundled momentjs to 2.19.3
  vendor/momentjs/moment.js
  vendor/momentjs/moment.min.js
Labels: code review

#1487 build(vendor/momentjs) update bundled momentjs to 2.19.3
  readme.txt
  vendor/momentjs/moment.js
  vendor/momentjs/moment.min.js
Labels: code review

#1479 Update Freemius to version 2.4.1
  readme.txt
  src/Tribe/Main.php
  tribe-common.php
  vendor/freemius/README.md
  vendor/freemius/assets/css/admin/account.css
  vendor/freemius/assets/css/admin/add-ons.css
  vendor/freemius/config.php
  vendor/freemius/includes/class-freemius.php
  vendor/freemius/includes/class-fs-api.php
  vendor/freemius/includes/class-fs-plugin-updater.php
  vendor/freemius/includes/class-fs-storage.php
  vendor/freemius/includes/customizer/class-fs-customizer-support-section.php
  vendor/freemius/includes/entities/class-fs-payment.php
  vendor/freemius/includes/entities/class-fs-plugin-license.php
  vendor/freemius/includes/entities/class-fs-site.php
  vendor/freemius/includes/fs-essential-functions.php
  vendor/freemius/includes/fs-plugin-info-dialog.php
  vendor/freemius/includes/i18n.php
  vendor/freemius/includes/managers/class-fs-admin-menu-manager.php
  vendor/freemius/includes/sdk/FreemiusBase.php
  vendor/freemius/includes/sdk/FreemiusWordPress.php
  vendor/freemius/includes/supplements/fs-essential-functions-1.1.7.1.php
  vendor/freemius/languages/freemius-cs_CZ.mo
  vendor/freemius/languages/freemius-da_DK.mo
  vendor/freemius/languages/freemius-en.mo
  vendor/freemius/languages/freemius-es_ES.mo
  vendor/freemius/languages/freemius-fr_FR.mo
  vendor/freemius/languages/freemius-he_IL.mo
  vendor/freemius/languages/freemius-hu_HU.mo
  vendor/freemius/languages/freemius-it_IT.mo
  vendor/freemius/languages/freemius-ja.mo
  vendor/freemius/languages/freemius-nl_NL.mo
  vendor/freemius/languages/freemius-ru_RU.mo
  vendor/freemius/languages/freemius-ta.mo
  vendor/freemius/languages/freemius.pot
  vendor/freemius/package.json
  vendor/freemius/start.php
  vendor/freemius/templates/account.php
  vendor/freemius/templates/account/partials/addon.php
  vendor/freemius/templates/account/payments.php
  vendor/freemius/templates/add-ons.php
  vendor/freemius/templates/auto-installation.php
  vendor/freemius/templates/connect.php
  vendor/freemius/templates/forms/affiliation.php
  vendor/freemius/templates/forms/deactivation/form.php
  vendor/freemius/templates/forms/license-activation.php
  vendor/freemius/templates/forms/optout.php
  vendor/freemius/templates/forms/subscription-cancellation.php
  vendor/freemius/templates/forms/trial-start.php
  vendor/freemius/templates/pricing.php
  vendor/freemius/templates/secure-https-header.php
Labels: code review

#1484 [ETP-499] Add action hook to allow additional button/text in heading
  src/Tribe/Dialog/View.php
  src/admin-views/tabbed-view/tabbed-view.php
  src/views/dialog/button.php
Labels: merge

#1489 [ETP-523] Update `a11y-dialog` to its latest.
  composer.json
  composer.lock
Labels: code review

#1491 Add an auto-enabled Black Friday banner using our Notices system | TCMN-90 | ET-962 | TEC-3679
  .travis.yml
  src/Tribe/Admin/Notice/Marketing.php
  src/admin-views/notices/tribe-bf-2018-et.php
  src/admin-views/notices/tribe-bf-2018-general.php
  src/admin-views/notices/tribe-bf-2018-tec.php
  src/admin-views/notices/tribe-bf-general.php
  src/admin-views/notices/tribe-gutenberg-release.php
  src/resources/images/icons/sale-burst.svg
  src/resources/postcss/tribe-common-admin.pcss
Labels: merge

#1492 Cherry-picking the commits for the Black Friday banner message
  src/Tribe/Admin/Notice/Marketing.php
  src/admin-views/notices/tribe-bf-2018-et.php
  src/admin-views/notices/tribe-bf-2018-general.php
  src/admin-views/notices/tribe-bf-2018-tec.php
  src/admin-views/notices/tribe-bf-general.php
  src/admin-views/notices/tribe-gutenberg-release.php
  src/resources/images/icons/sale-burst.svg
  src/resources/postcss/tribe-common-admin.pcss
Labels: code review

#1496 Fix/tec 3649 theme overrides 2
  src/resources/postcss/base/full/typography/_anchors.pcss
Labels: code review

#1495 remove unused search and filter styles
  src/resources/postcss/components/skeleton/buttons/_icon.pcss
Labels: code review

#1488 Fix sub-directory handling in Rewrite component
  readme.txt
  src/Tribe/Rewrite.php
Labels: code review, merge

#1498 Prevent tribe_get_first_ever_installed_version from loading an instance just to get a prop
  src/functions/utils.php
Labels: code review

#1493 Function to add tribe-dependency attributes to admin elements
  src/Tribe/Utils/Element_Attributes.php
  src/Tribe/Widget/Widget_Abstract.php
  src/functions/template-tags/html.php
  src/resources/js/dependency.js
  tests/wpunit/Tribe/functions/templateTags/dependenciesTest.php
Labels: code review

#1499 Prevent version utilities from loading an instance just to get a prop/constant
  readme.txt
  src/Tribe/Main.php
  src/functions/utils.php
  tribe-common.php
Labels: code review

#1502 Remove deprecated code
  src/Tribe/Editor/Blocks/Abstract.php
  src/Tribe/Log/File_Logger.php
  src/Tribe/Main.php
Labels: code review

#1505 Feature / TEC - 3653 improved ui general tab
  src/Tribe/Customizer/Control.php
  src/Tribe/Customizer/Controls/Heading.php
Labels: code review

#1490 [ETP-523] Dialog button > Improve button a11y
  readme.txt
  src/views/dialog/button.php
  tests/snapshots/Views/Dialog/AlertTest.php
  tests/snapshots/Views/Dialog/__snapshots__/AlertTest__test_w_title__0.snapshot.html
  tests/snapshots/Views/Dialog/__snapshots__/AlertTest__test_wo_title__0.snapshot.html
Labels: merge

#1506 Add action before inline style print
  src/Tribe/Customizer.php
Labels: code review, merge

#1507 allow widgets to use customizer styles
  src/Tribe/Customizer.php
  src/views/v2/components/icons/plus.php
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/PlusTest__test_render_with_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/PlusTest__test_render_without_classes__0.snapshot.html
Labels: code review

#1508 Set sensible defaults for skeleton SVG icons
  src/resources/postcss/base/full/forms/_toggles.pcss
  src/resources/postcss/components/full/_svgicon.pcss
  src/resources/postcss/components/full/buttons/_icon.pcss
  src/resources/postcss/components/skeleton/_loader.pcss
  src/resources/postcss/components/skeleton/_svgicon.pcss
  src/resources/postcss/components/skeleton/buttons/_icon.pcss
Labels: code review

#1500 Clean up formatting & add ticket refs for todos.
  src/Tribe/Exception.php
  src/Tribe/Settings_Manager.php
  src/Tribe/Simple_Table.php
  src/functions/template-tags/date.php
  tests/wpunit/Tribe/DependencyTest.php
  tests/wpunit/Tribe/Process/HandlerTest.php
Labels: code review, merge
