Repository the-events-calendar/tribe-common, pull requests merged in 2020-08, with the labels that each got.

#1416 Toggle > Make the toggle compatible with IE11.
  readme.txt
  src/resources/postcss/base/full/forms/_toggles.pcss
Labels: merge

#1418 Feature/fbar 126 checkbox markup styles
  readme.txt
  src/resources/postcss/base/full/forms/_checkboxes-radios.pcss
Labels: merge

#1419 welcome page updates
  src/Tribe/Admin/Activation_Page.php
  src/admin-views/app-shop.php
  src/admin-views/tribe-options-general.php
  src/admin-views/tribe-options-help.php
  src/resources/images/header/all-solutions.jpg
  src/resources/images/header/bundles.jpg
  src/resources/images/header/extensions.jpg
  src/resources/images/header/welcome-desktop.jpg
  src/resources/images/header/welcome-mobile.jpg
  src/resources/images/logo/community-tickets.svg
  src/resources/images/logo/tec-brand.svg
  src/resources/images/mascot.png
  src/resources/images/welcome/guide-book.jpg
  src/resources/images/welcome/knowledgebase.jpg
  src/resources/images/welcome/migration.jpg
  src/resources/images/welcome/next-level.jpg
  src/resources/images/welcome/promo.jpg
  src/resources/images/welcome/translations.jpg
  src/resources/images/welcome/virtual-events.jpg
  src/resources/postcss/app-shop.pcss
  src/resources/postcss/tribe-common-admin.pcss
Labels: code review, merge

#1420 Feature/fbar 126 fbar 127 checkbox radio
  readme.txt
  src/resources/postcss/base/skeleton/forms/_checkboxes-radios.pcss
Labels: merge

#1423 Feature/fbar 129 multiselect markup styles
  readme.txt
  src/resources/js/dropdowns.js
Labels: merge

#1422 Welcome / App Shop design QA updates
  src/Tribe/App_Shop.php
  src/Tribe/Plugins_API.php
  src/admin-views/app-shop.php
  src/resources/images/welcome/migration.jpg
  src/resources/images/welcome/next-level.jpg
  src/resources/postcss/app-shop.pcss
  src/resources/postcss/tribe-common-admin.pcss
Labels: code review

#1425 Resolve WP 5.5 modal component extra props
  readme.txt
  src/Tribe/Main.php
  src/modules/elements/label-with-modal/element.js
  src/modules/elements/modal-button/element.js
  tests/wpunit/Tribe/functions/templateTags/generalTest.php
  tribe-common.php
Labels: merge

#1427 another round of design QA
  src/resources/postcss/app-shop.pcss
  src/resources/postcss/tribe-common-admin.pcss
Labels: code review

#1351 TCMN-68: Improve regular expressions
  readme.txt
  src/Tribe/Timezones.php
Labels: merge
