Repository the-events-calendar/tribe-common, pull requests merged in 2020-04, with the labels that each got.

#1330 Task/store init from window
  src/modules/utils/globals.js
Labels: code review

#1324 Task/price block split state
  src/modules/hoc/with-block-closer.js
Labels: code review, hold

#1332 Feature/tec 3385 recent past events
  readme.txt
  src/Tribe/Template.php
Labels: code review

#1329 Update our PCSS to handle with the changes made to WP 5.4
  readme.txt
  src/modules/components/plugin-block-hooks/style.pcss
Labels: code review

#1307 Sysinfo addition
  readme.txt
  src/Tribe/Support.php
Labels: code review

#1339 Task/datetime block template
  src/Tribe/Editor/Blocks/Abstract.php
  src/Tribe/Editor/Configuration.php
  src/modules/utils/globals.js
Labels: code review, hold

#1338 Fix/tcmn 58 translation loading
  readme.txt
  src/Tribe/Main.php
Labels: merge

#1336 Spotfix/unifying read more strings
  src/Tribe/Admin/Notice/Plugin_Download.php
  src/Tribe/PUE/Update_Prevention.php
Labels: merge

#1331 [TCMN-57] docblock correction
  src/Tribe/Template.php
Labels: merge

#1335 fix(translations): Clear the cache when the language setting changes.
  readme.txt
  src/Tribe/Cache_Listener.php
Labels: merge

#1341 feat(Editor.php) allow filtering the should_load_blocks function
  src/Tribe/Editor.php
Labels: code review

#1334 Helper method to determine if Blocks are being used for Events
  readme.txt
  src/Tribe/Editor.php
Labels: merge

#1340 remove withSaveData hoc
  src/modules/hoc/__tests__/with-save-data.test.js
  src/modules/hoc/index.js
  src/modules/hoc/with-save-data.js
Labels: in-qa, merge

#1344 Bucket/block editor initial state
  src/Tribe/Editor/Blocks/Abstract.php
  src/Tribe/Editor/Configuration.php
  src/modules/hoc/__tests__/with-save-data.test.js
  src/modules/hoc/index.js
  src/modules/hoc/with-block-closer.js
  src/modules/hoc/with-save-data.js
  src/modules/utils/globals.js
Labels: code review

#1343 Pull the Shortcode Management classes into Common
  package.json
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Service_Providers/Shortcodes.php
  src/Tribe/Shortcode/Manager.php
  src/Tribe/Shortcode/Shortcode_Abstract.php
  src/Tribe/Shortcode/Shortcode_Interface.php
  tribe-common.php
Labels: merge

#1345 chore(.gitignore) ignore tric files
  .gitignore
Labels: merge

#1347 Fixed curly quotes in html markup
  readme.txt
  src/functions/template-tags/html.php
Labels: code review

#1348 Feature (styles): Add missing base styles.
  src/resources/postcss/base/full/typography/_anchors.pcss
  src/resources/postcss/base/full/typography/_ctas.pcss
Labels: code review

#1349 feat(Autoloader) support flat and nested namespaced classes
  readme.txt
  src/Tribe/Autoloader.php
  tests/_data/Tribe/CCNested/CCNestedSubOne/CCNestedSubTwo/SubTwo.php
  tests/_data/Tribe/CCNested/CCNestedSubOne/CCNestedSubTwo/Sub_Two.php
  tests/_data/Tribe/CCNested/CCNestedSubOne/SubOne.php
  tests/_data/Tribe/CCNested/CCNestedSubOne/Sub_One.php
  tests/_data/Tribe/CCNested/Class_One.php
  tests/_data/Tribe/CCNested/One.php
  tests/_data/Tribe/Flat/One.php
  tests/_data/Tribe/Nested/Level_One/CamelcaseClassOne.php
  tests/_data/Tribe/Nested/Level_One/Class_One.php
  tests/_data/Tribe/Nested/Level_One/Level_Two/CamelcaseClassTwo.php
  tests/_data/Tribe/Nested/Level_One/Level_Two/Class_Two.php
  tests/_data/Tribe/Nested/Level_One/Level_Two/Level_Three/CamelcaseClassThree.php
  tests/_data/Tribe/Nested/Level_One/Level_Two/Level_Three/Class_Three.php
  tests/_data/Tribe/Nested/Root.php
  tests/_data/Tribe/README.md
  tests/unit/Tribe/Utils/AutoloaderTest.php
Labels: merge

#1350 Support namespace prefixes for PUE Helper constant usage
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Autoloader.php
  src/Tribe/PUE/Checker.php
  tests/unit/Tribe/Utils/AutoloaderTest.php
Labels: merge
