Repository the-events-calendar/tribe-common, pull requests merged in 2020-12, with the labels that each got.

#1497 formatting, typos
  src/Tribe/Editor.php
Labels: merge

#1511 Merge G20.12 into B20.12
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Customizer.php
  src/Tribe/Dialog/View.php
  src/Tribe/Editor.php
  src/Tribe/Exception.php
  src/Tribe/Main.php
  src/Tribe/Settings_Manager.php
  src/Tribe/Simple_Table.php
  src/functions/template-tags/date.php
  src/resources/postcss/base/full/forms/_toggles.pcss
  src/resources/postcss/components/full/_svgicon.pcss
  src/resources/postcss/components/full/buttons/_icon.pcss
  src/resources/postcss/components/skeleton/_loader.pcss
  src/resources/postcss/components/skeleton/_svgicon.pcss
  src/resources/postcss/components/skeleton/buttons/_icon.pcss
  src/views/dialog/button.php
  src/views/v2/components/icons/plus.php
  tests/snapshots/Views/Dialog/AlertTest.php
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/PlusTest__test_render_with_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/PlusTest__test_render_without_classes__0.snapshot.html
  tests/wpunit/Tribe/DependencyTest.php
  tests/wpunit/Tribe/Process/HandlerTest.php
  tribe-common.php
Labels: code review

#1512 [ETP-509] Common full styles > checkbox/radio `:checked:before` margin reset
  src/resources/postcss/base/full/forms/_checkboxes-radios.pcss
Labels: code review

#1509 Just print Customizer styles in the footer for Views v2
  readme.txt
  src/Tribe/Customizer.php
Labels: code review, merge

#1513 Bump a11y dialog to 5.1.1
  composer.json
  composer.lock
Labels: merge

#1514 add class to photo icon
  src/views/v2/components/icons/photo.php
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/PhotoTest__test_render_with_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/PhotoTest__test_render_without_classes__0.snapshot.html
Labels: code review

#1515 Update di52 to the latest version
  composer.json
  composer.lock
  readme.txt
Labels: code review

#1517 Use `mt-a11y-dialog` from npm.
  composer.json
  composer.lock
  package-whitelist.json
  package.json
  src/Tribe/Assets.php
  src/Tribe/Service_Providers/Dialog.php
Labels: merge

#1518 Add param for settings hook.
  src/Tribe/Customizer.php
Labels: code review

#1516 Allow easy deactivation of logging from code
  readme.txt
  src/Tribe/Log/Service_Provider.php
Labels: code review

#1519 Compatibiliy: WordPress 5.6 + jQuery 3.0
  src/resources/js/admin-log-controls.js
  src/resources/js/admin/help-page.js
  src/resources/js/dropdowns.js
Labels: code review
