Repository the-events-calendar/tribe-common, pull requests merged in 2020-05, with the labels that each got.

#1358 Modify from include to include_once, major performance boost!
  src/Tribe/Template.php
Labels: code review, merge

#1361 add events virtual plugin constant
  jest.config.json
  src/modules/data/plugins/__tests__/__snapshots__/constants.test.js.snap
  src/modules/data/plugins/__tests__/constants.test.js
  src/modules/data/plugins/constants.js
  src/modules/hoc/__tests__/__snapshots__/with-save-data.test.js.snap
Labels: code review

#1352 Make Customizer stylesheet enqueue filterable.
  readme.txt
  src/Tribe/Customizer.php
Labels: merge

#1356 Rewrites: use and support localized slugs
  src/Tribe/Rewrite.php
Labels: merge

#1359 Template Entry Points
  readme.txt
  src/Tribe/Template.php
  src/Tribe/Utils/Strings.php
  tests/_data/classes/Dummy_Plugin_Origin.php
  tests/_data/plugin-views/templates/dummy-invalid-template-01.php
  tests/_data/plugin-views/templates/dummy-invalid-template-02.php
  tests/_data/plugin-views/templates/dummy-invalid-template-03.php
  tests/_data/plugin-views/templates/dummy-invalid-template-04.php
  tests/_data/plugin-views/templates/dummy-template.php
  tests/_data/plugin-views/templates/dummy-valid-template-01.php
  tests/_data/plugin-views/templates/dummy-valid-template-02.php
  tests/_data/plugin-views/templates/dummy-valid-template-03.php
  tests/wpunit/Tribe/Support/Template_CheckerTest.php
  tests/wpunit/Tribe/TemplateTest.php
  tests/wpunit/Tribe/Utils/StringTest.php
Labels: code review

#1346 Expose one more variable and fix loading from themes problem
  src/Tribe/Template.php
Labels: merge

#1357 Resolve when Plugins load a non-full version of Select2 too early.
  readme.txt
  src/Tribe/Assets_Pipeline.php
  src/resources/js/select2-before.js
Labels: code review

#1333 Helper methods to check if specific Tribe plugins are active
  readme.txt
  src/Tribe/Plugins.php
Labels: merge

#1363 correct conditional
  src/Tribe/Service_Providers/Shortcodes.php
  src/Tribe/Shortcode/Shortcode_Abstract.php
Labels: merge

#1364 reformatting
  src/Tribe/Shortcode/Shortcode_Abstract.php
  src/Tribe/Shortcode/Shortcode_Interface.php
Labels: merge

#1368 Fix typo of the word 'occurrence'
  src/Tribe/Support.php
Labels: merge

#1366 Spotfix/shortcode alias attributes
  readme.txt
  src/Tribe/Shortcode/Shortcode_Abstract.php
  src/Tribe/Shortcode/Shortcode_Interface.php
  src/Tribe/Utils/Array.php
  tests/wpunit/Tribe/Utils/ArrayTest.php
Labels: merge

#1369 Add Context locations required by VE plugin.
  readme.txt
  src/Tribe/Context/locations.php
Labels: code review, merge

#1370 Spotfix - Filter: tribe_extension_is_disallowed
  readme.txt
  src/Tribe/Extension.php
Labels: merge

#1371 feature(tracker): Adds a method to get the change date of a key.
  src/Tribe/Tracker.php
Labels: merge

#1372 hen using Block Editor we ensure that `apply_filters` for `the_content` on `tribe_get_the_content`
  readme.txt
  src/functions/template-tags/post.php
Labels: code review

#1373 Element attributes to merge attributes into a string
  src/Tribe/Utils/Element_Attributes.php
  src/functions/template-tags/html.php
  tests/wpunit/Tribe/Utils/Element_AttributesTest.php
Labels: code review

#1367 Fix block editor tests
  __mocks__/@wordpress/components.js
  __mocks__/@wordpress/data.js
  __mocks__/@wordpress/editor.js
  __mocks__/chrono-node.js
  __mocks__/icons.js
  package-lock.json
  package.json
  src/modules/elements/creatable-select/__tests__/__snapshots__/element.test.js.snap
  src/modules/elements/select/__tests__/__snapshots__/element.test.js.snap
Labels: code review, needs release

#1375 fixed the extensions link
  src/admin-views/app-shop.php
Labels: code review

#1376 remove cache from entry point matches
  src/Tribe/Template.php
Labels: code review

#1377 Add With_Meta_Handling trait
  readme.txt
  src/Tribe/Repository.php
  src/Tribe/Traits/With_Meta_Updates_Handling.php
  tests/wpunit/Tribe/Traits/With_Meta_Updates_HandlingTest.php
Labels: code review
