Repository the-events-calendar/tribe-common, pull requests merged in 2020-10, with the labels that each got.

#1448 Updates to the date and time reference
  src/admin-views/tribe-options-display.php
Labels: code review

#1453 Dropdown search adapted for latest version of SelectWoo
  readme.txt
  src/Tribe/Ajax/Dropdown.php
Labels: code review

#1454 welcome page refresh
  src/Tribe/Admin/Activation_Page.php
  src/resources/images/header/welcome-desktop-et.jpg
  src/resources/images/header/welcome-desktop-etplus.jpg
  src/resources/images/header/welcome-mobile-et.jpg
  src/resources/images/header/welcome-mobile-etplus.jpg
  src/resources/images/icons/horns-white.svg
  src/resources/images/mascot.png
  src/resources/images/welcome/calendar.jpg
  src/resources/images/welcome/et-plus-upsell.jpg
  src/resources/images/welcome/extension-library.jpg
  src/resources/images/welcome/guide-book-green.jpg
  src/resources/images/welcome/up-sell.jpg
  src/resources/postcss/tribe-common-admin.pcss
Labels: merge

#1451 TEC-3592 - setup widget service provider, manager, interface, and abs…
  src/Tribe/Main.php
  src/Tribe/Service_Providers/Widgets.php
  src/Tribe/Widget/Manager.php
  src/Tribe/Widget/Widget_Abstract.php
  src/Tribe/Widget/Widget_Interface.php
Labels: merge

#1447 [ECP-458] Register Block Editor translations when available
  readme.txt
  src/Tribe/Assets.php
  tests/_data/lang/tribe-common-en-test-script.json
  tests/_data/lang/tribe-common-en.mo
  tests/_data/lang/tribe-common-en.po
  tests/_data/lang/tribe-common.pot
  tests/wpunit/Tribe/AssetsTest.php
Labels: code review

#1457 Add the tribe_suspending_filter function
  readme.txt
  src/functions/utils.php
  tests/wpunit/Tribe/functions/utilsTest.php
Labels: merge, question

#1461 Allow our Monolog implementation to be 1.x and 2.x compatible | TEC-3638
  src/Tribe/Log/Canonical_Formatter.php
  src/Tribe/Log/Service_Provider.php
Labels: code review

#1456 Feature/tec 3612 v2 widget form
  src/Tribe/Widget/Widget_Abstract.php
  src/Tribe/Widget/Widget_Interface.php
Labels: code review

#1459 [ETP-496] correct docblock for template’s get()
  src/Tribe/Template.php
Labels: merge

#1464 Fix typos
  src/Tribe/Assets.php
  src/functions/template-tags/general.php
Labels: code review

#1460 Feature/tec 3597 fe dynamic data
  src/Tribe/Assets.php
  src/Tribe/Widget/Widget_Abstract.php
  src/Tribe/Widget/Widget_Interface.php
  src/functions/template-tags/general.php
Labels: code review

#1465 Added a `setup_view` method to the abstract class.
  src/Tribe/Widget/Widget_Abstract.php
Labels: code review

#1463 Release B20.10
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Assets.php
  src/Tribe/Log/Canonical_Formatter.php
  src/Tribe/Log/Service_Provider.php
  src/Tribe/Main.php
  src/Tribe/Service_Providers/Widgets.php
  src/Tribe/Widget/Manager.php
  src/Tribe/Widget/Widget_Abstract.php
  src/Tribe/Widget/Widget_Interface.php
  src/admin-views/tribe-options-display.php
  src/functions/utils.php
  tests/_data/lang/tribe-common-en-test-script.json
  tests/_data/lang/tribe-common-en.mo
  tests/_data/lang/tribe-common-en.po
  tests/_data/lang/tribe-common.pot
  tests/wpunit/Tribe/AssetsTest.php
  tests/wpunit/Tribe/functions/utilsTest.php
  tribe-common.php
Labels: merge

#1468 Add styles for admin widget section(s).
  src/resources/postcss/tribe-common-admin.pcss
Labels: code review

#1469 add iac vars to globals
  src/modules/utils/globals.js
Labels: merge
