Repository the-events-calendar/tribe-common, pull requests merged in 2021-06, with the labels that each got.

#1584 New common-centric Theme Compatibility
  readme.txt
  src/Tribe/Utils/Compatibility_Classes.php
  src/Tribe/Utils/Theme_Compatibility.php
  tests/wpunit/Tribe/Utils/Theme_CompatibilityTest.php
Labels: code review, needs release

#1611 Ensure we pass an array.
  readme.txt
  src/Tribe/Cost_Utils.php
Labels: merge

#1605 Make sure cache is retrived correctly
  src/Tribe/Cache.php
  tests/wpunit/Tribe/CacheTest.php
Labels: merge

#1610 Feature/ve 352 ve 353 switch slide toggle
  readme.txt
  src/Tribe/Cache.php
  src/Tribe/Field.php
  src/admin-views/components/switch.php
  src/resources/postcss/tribe-common-admin.pcss
  tests/snapshots/Views/Admin-Views/SwitchTest.php
  tests/snapshots/Views/Admin-Views/__snapshots__/SwitchTest__should_render_with_classes_and_checked__0.snapshot.html
  tests/snapshots/Views/Admin-Views/__snapshots__/SwitchTest__should_render_without_classes_and_not_checked__0.snapshot.html
  tests/wpunit/Tribe/CacheTest.php
Labels: code review

#1613 Version bump
  src/Tribe/Main.php
Labels: merge

#1604 Feature/customizer phase 3 - Comon changes and new controls
  readme.txt
  src/Tribe/Customizer.php
  src/Tribe/Customizer/Controls/Radio.php
  src/Tribe/Customizer/Section.php
  src/Tribe/Main.php
  src/Tribe/Utils/Compatibility_Classes.php
  src/Tribe/Utils/Theme_Compatibility.php
  src/functions/template-tags/general.php
  src/resources/postcss/customizer-controls.pcss
  tests/wpunit/Tribe/CustomizerTest.php
  tests/wpunit/Tribe/Utils/Theme_CompatibilityTest.php
Labels: code review, needs release
