Repository the-events-calendar/tribe-common, pull requests merged in 2021-03, with the labels that each got.

#1554 Fix / TEC-3418 deprecated warnings
  src/modules/components/plugin-block-hooks/__tests__/plugin-block-hooks.spec.js
  src/modules/components/plugin-block-hooks/component.js
  src/modules/elements/image-upload/__tests__/element.test.js
  src/modules/elements/image-upload/element.js
  src/modules/utils/globals.js
Labels: code review, needs changelog

#1551 Context method for dangerously_repopulate_locations
  composer.lock
  readme.txt
  src/Tribe/Context.php
  tests/wpunit/Tribe/ContextTest.php
Labels: code review

#1555 Decode country names when localizing
  readme.txt
  src/Tribe/Editor/Configuration.php
  src/Tribe/Languages/Locations.php
Labels: merge

#1562 Move Taxonomy file from TEC to common, as it will aid all plugins on shortcode
  readme.txt
  src/Tribe/Utils/Taxonomy.php
  tests/wpunit/Tribe/Utils/TaxonomyTest.php
Labels: code review

#1563 Include recurring notices
  readme.txt
  src/Tribe/Admin/Notices.php
Labels: code review, merge

#1564 MT-> TEC
  readme.txt
  src/Tribe/Admin/Help_Page.php
  src/Tribe/Ajax/Dropdown.php
  src/Tribe/Customizer.php
  src/Tribe/Debug_Bar/Panels/Context.php
  src/Tribe/Debug_Bar/Panels/Json_Ld.php
  src/Tribe/Dependency.php
  src/Tribe/Extension.php
  src/Tribe/Log/README.md
  src/Tribe/PUE/Update_Prevention.php
  src/Tribe/Plugins.php
  src/Tribe/Process/Handler.php
  src/Tribe/REST/Main.php
  src/Tribe/Service_Providers/Debug_Bar.php
  src/Tribe/Support.php
  src/Tribe/Template.php
  src/Tribe/Utils/Element_Classes.php
  src/Tribe/Utils/Global_ID.php
  src/admin-views/tribe-options-general.php
  src/admin-views/tribe-options-help.php
  src/admin-views/tribe-options-network.php
  src/resources/images/logo/tec-brand.svg
  src/resources/postcss/README.md
  tests.md
Labels: merge
