Repository the-events-calendar/tribe-common, pull requests merged in 2021-05, with the labels that each got.

#1585 ECP-737: ECP > Conflict with Avada
  readme.txt
  vendor/tribe-selectWoo/dist/js/select2.full.js
  vendor/tribe-selectWoo/dist/js/select2.js
  vendor/tribe-selectWoo/dist/js/selectWoo.full.js
  vendor/tribe-selectWoo/dist/js/selectWoo.js
Labels: code review

#1586 TEC-3796: Adjust the actions used to register styles for the common
  readme.txt
  src/Tribe/Service_Providers/Tooltip.php
Labels: code review

#1590 Bump lodash from 4.17.15 to 4.17.21 | TEC-3885
  package-lock.json
  package.json
  readme.txt
Labels: code review, merge

#1592 TCMN-107: Display `draft` posts as part of the events
  readme.txt
  src/Tribe/Repository.php
Labels: code review

#1593 Relocating the summary icon to common just like all of our other icons
  src/views/v2/components/icons/summary.php
Labels: code review

#1594 ECP-737: Minify changes on the vendor for selectWoo
  vendor/tribe-selectWoo/dist/js/select2.full.js
  vendor/tribe-selectWoo/dist/js/selectWoo.full.js
  vendor/tribe-selectWoo/dist/js/selectWoo.full.min.js
Labels: code review, merge

#1598 Load Tooltip on the admin
  src/Tribe/Service_Providers/Tooltip.php
Labels: merge

#1600 [ET-1120] Split TEC/ET admin footer rating link 50/50
  readme.txt
  src/Tribe/Credits.php
Labels: merge

#1601 Revert "TCMN-107: Display `draft` posts as part of the events"
  readme.txt
  src/Tribe/Repository.php
Labels: code review, merge

#1603 Install product taskmaster from npm
  gulpfile.js
  package-lock.json
  package.json
  webpack.config.js
Labels: code review, hold
