Repository the-events-calendar/tribe-common, pull requests merged in 2021-12, with the labels that each got.

#1681 Prevent PHP 8 warnings when running extensions
  readme.txt
  src/Tribe/Plugin_Meta_Links.php
Labels: merge

#1682 Fix tests from mixed version
  composer.json
  composer.lock
Labels: code review

#1684 In app "end of year sale" promos
  readme.txt
  src/Tribe/Admin/Conditional_Content/End_Of_Year_Sale.php
  src/Tribe/Admin/Conditional_Content/Service_Provider.php
  src/Tribe/Admin/Notice/Marketing/End_Of_Year_Sale.php
  src/Tribe/Admin/Notice/Service_Provider.php
  src/admin-views/conditional_content/end-of-year-sale.php
  src/admin-views/notices/end-of-year-sale.php
  src/resources/images/marketing/eoy-sale-2021.svg
  src/resources/images/marketing/eoy-sale-promo.png
  src/resources/postcss/tribe-common-admin.pcss
Labels: merge

#1686 New Price Classes Structure
  src/Tribe/Values/Abstract_Currency.php
  src/Tribe/Values/Abstract_Value.php
  src/Tribe/Values/Currency_Interface.php
  src/Tribe/Values/Value_Calculation.php
  src/Tribe/Values/Value_Formatting.php
  src/Tribe/Values/Value_Interface.php
  src/Tribe/Values/Value_Update.php
  src/functions/template-tags/general.php
  tests/unit/Tribe/Values/PriceTest.php
Labels: code review

#1683 Update Jest testing for block editor JS files
  .github/workflows/tests-js.yml
  jest.config.js
  jest.config.json
  jest.setup.js
  package-lock.json
  package.json
  src/modules/.eslintrc
  src/modules/data/forms/__tests__/reducer.test.js
  src/modules/data/plugins/__tests__/reducer.test.js
  src/modules/elements/accordion/__tests__/element.test.js
  src/modules/elements/accordion/row/__tests__/template.test.js
  src/modules/elements/accordion/row/template.js
  src/modules/elements/button/__tests__/element.test.js
  src/modules/elements/checkbox/__tests__/element.test.js
  src/modules/elements/checkbox/element.js
  src/modules/elements/counter/__tests__/element.test.js
  src/modules/elements/image-upload/element.js
  src/modules/elements/image/__tests__/element.test.js
  src/modules/elements/labeled-item/__tests__/element.test.js
  src/modules/elements/tooltip/element.js
  src/modules/hoc/__tests__/__snapshots__/with-store.test.js.snap
  src/modules/store/middlewares/request/__tests__/actions.test.js
  src/modules/store/middlewares/request/__tests__/types.test.js
  src/modules/store/middlewares/request/__tests__/utils.test.js
  src/modules/store/middlewares/request/__tests__/wp-request.test.js
  src/modules/utils/__tests__/date.test.js
  src/modules/utils/__tests__/moment.test.js
  src/modules/utils/__tests__/time.test.js
  src/modules/utils/moment.js
Labels: merge

#1688 Fix element index files for modules
  src/modules/elements/accordion/__tests__/element.test.js
  src/modules/elements/accordion/element.js
  src/modules/elements/accordion/index.js
  src/modules/elements/accordion/row/index.js
  src/modules/elements/accordion/row/template.js
  src/modules/elements/button/__tests__/element.test.js
  src/modules/elements/button/index.js
  src/modules/elements/checkbox-input/element.js
  src/modules/elements/checkbox-input/index.js
  src/modules/elements/checkbox/__tests__/element.test.js
  src/modules/elements/checkbox/element.js
  src/modules/elements/checkbox/index.js
  src/modules/elements/counter/__tests__/element.test.js
  src/modules/elements/counter/index.js
  src/modules/elements/creatable-select/index.js
  src/modules/elements/day-picker-input/index.js
  src/modules/elements/heading/index.js
  src/modules/elements/image-upload/__tests__/element.test.js
  src/modules/elements/image-upload/element.js
  src/modules/elements/image-upload/index.js
  src/modules/elements/image/__tests__/element.test.js
  src/modules/elements/image/index.js
  src/modules/elements/index.js
  src/modules/elements/input/index.js
  src/modules/elements/label-with-link/element.js
  src/modules/elements/label-with-link/index.js
  src/modules/elements/label-with-modal/__tests__/element.test.js
  src/modules/elements/label-with-modal/element.js
  src/modules/elements/label-with-modal/index.js
  src/modules/elements/labeled-item/__tests__/element.test.js
  src/modules/elements/labeled-item/index.js
  src/modules/elements/link/index.js
  src/modules/elements/modal-button/__tests__/element.test.js
  src/modules/elements/modal-button/element.js
  src/modules/elements/modal-button/index.js
  src/modules/elements/number-input/element.js
  src/modules/elements/number-input/index.js
  src/modules/elements/paragraph/index.js
  src/modules/elements/placeholder/index.js
  src/modules/elements/radio-input/element.js
  src/modules/elements/radio-input/index.js
  src/modules/elements/radio/index.js
  src/modules/elements/select/index.js
  src/modules/elements/textarea/index.js
  src/modules/elements/time-picker/element.js
  src/modules/elements/time-picker/index.js
  src/modules/elements/tooltip/__tests__/element.test.js
  src/modules/elements/tooltip/element.js
  src/modules/elements/tooltip/index.js
  src/modules/elements/url-input/element.js
  src/modules/elements/url-input/index.js
Labels: code review

#1685 Load `Event Countdown` widget assets on post type pages. [ECP-1016]
  readme.txt
  src/Tribe/Main.php
Labels: code review, needs release

#1690 PHP 8.1 Compatibility
  composer.json
  composer.lock
  readme.txt
  src/Tribe/Cache.php
  src/Tribe/Utils/Date_I18n.php
  src/Tribe/Utils/Date_I18n_Immutable.php
  src/functions/utils.php
Labels: code review
