Repository the-events-calendar/tribe-common, pull requests merged in 2021-09, with the labels that each got.

#1649 Fix the tribe_systeminfo_optin checkbox so it reflects the database correctly.
  src/Tribe/Support.php
  src/admin-views/troubleshooting/system-information.php
  src/resources/js/admin/help-page.js
Labels: code review

#1650 Tweak some of the Troubleshooting page optin code.
  readme.txt
  src/Tribe/Admin/Help_Page.php
  src/Tribe/Support.php
  src/admin-views/troubleshooting/system-information.php
  src/resources/js/admin/help-page.js
Labels: code review

#1651 Use _x() rather than __() when describing translations
  src/Tribe/Admin/Help_Page.php
Labels: code review

#1653 Add delete_option to the php handling the optin.
  src/Tribe/Support.php
Labels: code review

#1652 Update the dependency to point to an existing repo
  composer.json
  composer.lock
Labels: code review, hold

#1656 [CE-130] Dropdown not unescaping ampersand - revised for anon submission
  src/Tribe/Ajax/Dropdown.php
Labels: code review, merge

#1659 Updated code to use `wp_kses` to escape user content
  src/Tribe/Ajax/Dropdown.php
Labels: code review

#1574 [Innovation] Onboarding: Tours & Hints
  package-lock.json
  package-whitelist.json
  package.json
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Onboarding/Hints_Abstract.php
  src/Tribe/Onboarding/Main.php
  src/Tribe/Onboarding/README.md
  src/Tribe/Onboarding/Tour_Abstract.php
  src/Tribe/Service_Providers/Onboarding.php
  src/resources/js/.eslintrc
  src/resources/js/onboarding.js
  src/resources/postcss/onboarding.pcss
Labels: code review, innovation
