Repository the-events-calendar/tribe-common, pull requests merged in 2021-04, with the labels that each got.

#1568 [TEC-3833] Remove setup call in Widget Abstract class
  readme.txt
  src/Tribe/Widget/Widget_Abstract.php
Labels: code review

#1570 [ET-1047] TwentyTwentyOne compatibility
  readme.txt
  src/resources/postcss/base/full/_buttons.pcss
  src/resources/postcss/base/skeleton/forms/_checkboxes-radios.pcss
  src/resources/postcss/components/full/buttons/_solid.pcss
Labels: code review

#1569 VE-299 - add hybrid icon
  readme.txt
  src/resources/postcss/components/skeleton/_svgicon.pcss
  src/views/v2/components/icons/hybrid.php
  tests/snapshots/Views/V2/Components/Icons/HybridTest.php
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/HybridTest__test_render_with_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/HybridTest__test_render_without_classes__0.snapshot.html
Labels: code review

#1573 Select2 Third-Party conflict resolution
  readme.txt
  src/Tribe/Assets_Pipeline.php
  src/resources/js/dropdowns.js
  src/resources/js/select2-after.js
Labels: code review, in-qa

#1567 Feature/widget mini calendar and week
  src/functions/utils.php
  src/resources/postcss/resets/full/_all.pcss
  src/resources/postcss/resets/full/_twentytwentyone.pcss
  src/resources/postcss/resets/skeleton/_all.pcss
  src/resources/postcss/resets/skeleton/_twentytwentyone.pcss
Labels: code review

#1576 Modify where the AMD define/require is called from
  src/resources/js/dropdowns.js
Labels: code review, merge

#1575 VE-315 - update to icon based on DQA
  src/views/v2/components/icons/hybrid.php
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/HybridTest__test_render_with_classes__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/HybridTest__test_render_without_classes__0.snapshot.html
Labels: merge

#1577 Add visual notice for number inputs that are out of range.
  src/resources/postcss/tribe-common-admin.pcss
Labels: code review

#1578 Add changelog and Cache listener hooks
  readme.txt
  src/Tribe/Cache_Listener.php
Labels: code review
