Repository the-events-calendar/tribe-common, pull requests merged in 2021-01, with the labels that each got.

#1529 Correctly handle falsy directory names
  readme.txt
  src/Tribe/Utils/Paths.php
  tests/unit/Tribe/Utils/Paths_Test.php
Labels: code review

#1522 Move TribeDb to common.
  tests/_support/Helper/TECDb.php
Labels: merge

#1527 Compatibility with PHP 8+
  readme.txt
  src/Tribe/Extension.php
  src/Tribe/Extension_Loader.php
  src/Tribe/Repository/Query_Filters.php
  src/functions/utils.php
  vendor/freemius/includes/class-fs-logger.php
Labels: code review, needs artifact, needs release

#1520 Bucket / customizer dqa adjustments
  src/Tribe/Customizer/Controls/Heading.php
Labels: code review

#1526 Tweaks for the countdown widget.
  src/Tribe/Ajax/Dropdown.php
  src/functions/template-tags/date.php
  src/functions/template-tags/html.php
  src/resources/js/dependency.js
  tests/wpunit/Tribe/functions/templateTags/dependenciesTest.php
Labels: code review

#1539 Fix a logic inversion that breaks asset loading.
  src/functions/utils.php
Labels: code review

#1540 Resolve ordering problem because of Virtual Events
  readme.txt
  src/Tribe/Repository.php
  src/Tribe/Repository/Core_Read_Interface.php
  tests/wpunit/Tribe/Repository/OrderTest.php
Labels: code review

#1538 Include notice about WP 5.7
  src/Tribe/Admin/Notice/WP_Version.php
  src/Tribe/Main.php
Labels: code review

#1542 Modify Dropdown AJAX to allow external formatting
  src/Tribe/Ajax/Dropdown.php
Labels: code review
