Repository the-events-calendar/tribe-common, pull requests merged in 2022-11, with the labels that each got.

#1826 Cast all returns to string.
  readme.txt
  src/Tribe/Assets.php
  tests/wpunit/Tribe/functions/templateTags/generalTest.php
Labels: code review

#1828 Prevent Warnings from `Lazy_String` on PHP 8.1
  readme.txt
  src/Tribe/Utils/Lazy_String.php
Labels: code review

#1829 Reorganize settings fields
  package-lock.json
  readme.txt
  src/Tribe/Settings_Tab.php
  src/admin-views/tribe-options-display.php
  src/admin-views/tribe-options-general.php
  src/modules/utils/recurrence.js
  src/resources/js/dropdowns.js
  src/resources/postcss/tribe-common-admin/_main.pcss
Labels: merge

#1831 ECP View upsells/teasers
  readme.txt
  src/resources/postcss/tribe-common-admin/_main.pcss
Labels: code review, hold

#1832 Update some styling for the new TEC setting headers.
  src/resources/postcss/tribe-common-admin/_main.pcss
Labels: code review

#1836 Bring settings phase 1 into wagashi
  package-lock.json
  readme.txt
  src/Tribe/Settings_Tab.php
  src/admin-views/tribe-options-display.php
  src/admin-views/tribe-options-general.php
  src/modules/utils/recurrence.js
  src/resources/js/dropdowns.js
  src/resources/postcss/tribe-common-admin/_main.pcss
  tests/wpunit/Tribe/Notices/Stellar_SaleTest.php
Labels: merge, needs tests

#1841 Don't overwrite the intro, append to it.
  src/Tribe/Admin/Conditional_Content/Black_Friday.php
  src/Tribe/Admin/Conditional_Content/End_Of_Year_Sale.php
Labels: code review, merge

#1842 Comment out EOY Sale initialization for 2022
  src/Tribe/Admin/Conditional_Content/Service_Provider.php
  src/Tribe/Admin/Notice/Service_Provider.php
Labels: code review
