Repository the-events-calendar/tribe-common, pull requests merged in 2022-07, with the labels that each got.

#1774 Release/b22.pampushka
  lang/tribe-common.pot
  package.json
  readme.txt
  src/Tribe/Admin/Notice/Date_Based.php
  src/Tribe/Admin/Notice/Marketing.php
  src/Tribe/Admin/Notice/WP_Version.php
  src/Tribe/Main.php
  src/admin-views/troubleshooting/ea-status.php
  tribe-common.php
Labels: code review, hold

#1776 Static stellar sale banner.
  readme.txt
  src/Tribe/Admin/Notice/Date_Based.php
  src/Tribe/Admin/Notice/Marketing/Stellar_Sale.php
  src/admin-views/notices/tribe-stellar-sale.php
  src/resources/images/marketing/stellar-sale-text.svg
  src/resources/postcss/tribe-common-admin/_main.pcss
  src/views/v2/components/icons/stellar-icon.php
Labels: code review

#1779 Ensure the sale notice shows on help, troubleshooting, and ticket pages.
  src/Tribe/Admin/Notice/Date_Based.php
Labels: code review

#1781 Hotfix: Freemius update
  readme.txt
  src/Tribe/Main.php
  tribe-common.php
  vendor/freemius/assets/img/advanced-nocaptcha-and-invisible-captcha-pro.png
  vendor/freemius/assets/img/advanced-nocaptcha-recaptcha.jpg
  vendor/freemius/includes/class-freemius.php
  vendor/freemius/includes/managers/class-fs-key-value-storage.php
  vendor/freemius/package.json
  vendor/freemius/start.php
Labels: merge

#1758 Avoid loops caused by meta update tracker.
  src/Tribe/Tracker.php
Labels: merge

#1784 Include a way to print Before and After scripts.
  src/Tribe/Assets.php
Labels: code review

#1787 [ET-1539] Add Tickets Commerce Graphic to Resource Image Folder
  src/resources/images/welcome/tickets-commerce.png
Labels: code review
