Repository the-events-calendar/tribe-common, pull requests merged in 2022-04, with the labels that each got.

#1734 TEC-4338 completely load on activation
  codeception.dist.yml
  readme.txt
  src/Tribe/Main.php
  src/functions/conditionals.php
  tests/_data/empty.sql
  tests/_data/empty_cleanup.sql
  tests/_support/ActivationTester.php
  tests/_support/Helper/Activation.php
  tests/activation.suite.dist.yml
  tests/activation/ActionsCest.php
  tests/activation/_bootstrap.php
Labels: merge

#1737 Do not autoload batched data
  readme.txt
  src/Tribe/Process/Queue.php
  tests/wpunit/Tribe/Process/QueueTest.php
Labels: merge

#1738 Don't run the pipeline in the admin
  src/Tribe/Assets_Pipeline.php
  src/Tribe/Widget/Widget_Abstract.php
Labels: code review

#1739 Ensure the classic "forget" param overrides all else.
  readme.txt
  src/Tribe/Editor/Compatibility/Classic_Editor.php
Labels: merge

#1740 Don't apply "remember" to new posts.
  src/Tribe/Editor/Compatibility/Classic_Editor.php
Labels: code review, merge

#1741 [ETP-792] Fix admin links with target and rel attributes
  src/Tribe/Field.php
  src/admin-views/tribe-options-general.php
Labels: code review

#1691 Events/Tickets Menus
  src/Tribe/Admin/Activation_Page.php
  src/Tribe/Admin/Help_Page.php
  src/Tribe/Admin/Helpers.php
  src/Tribe/Admin/Pages.php
  src/Tribe/Admin/Troubleshooting.php
  src/Tribe/Credits.php
  src/Tribe/Main.php
  src/Tribe/Onboarding/Main.php
  src/Tribe/Service_Providers/Onboarding.php
  src/Tribe/Settings.php
  src/Tribe/Settings_Manager.php
  src/admin-views/tribe-options-network.php
  src/resources/postcss/tribe-common-admin.pcss
Labels: code review

#1742 Update PUE to provide a license key failover from transient to option
  src/Tribe/PUE/Checker.php
Labels: code review

#1728 Full site editor phase one
  composer.json
  package-lock.json
  package-whitelist.json
  readme.txt
  src/Common/Editor/Full_Site/Template_Utils.php
  src/Tribe/Customizer.php
  src/Tribe/Main.php
  src/Tribe/Settings_Manager.php
  src/Tribe/Widget/Widget_Abstract.php
  src/functions/editor.php
Labels: code review

#1743 [Events/Tickets menu] Set version number, dependencies, readme.
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Main.php
Labels: code review
