Repository the-events-calendar/tribe-common, pull requests merged in 2022-08, with the labels that each got.

#1785 [ET-1541] Common Settings Image Field
  readme.txt
  src/Tribe/Admin/Settings.php
  src/Tribe/Field.php
  src/Tribe/Main.php
  src/resources/js/admin-image-field.js
  src/resources/postcss/tribe-common-admin/_all.pcss
  src/resources/postcss/tribe-common-admin/_fields.pcss
Labels: code review

#1786 [ET-1540] Common Settings Color Field
  readme.txt
  src/Tribe/Admin/Settings.php
  src/Tribe/Field.php
  src/Tribe/Main.php
  src/Tribe/Validate.php
  src/resources/js/admin-color-field.js
  src/resources/postcss/tribe-common-admin/_fields.pcss
Labels: code review

#1792 Release/b22.remonce
  readme.txt
  src/Tribe/Tracker.php
Labels: hold

#1788 Improved Notices to allow Dismiss and Inline to be callables
  src/Tribe/Admin/Notices.php
Labels: code review

#1798 Update Activation page to avoid Freemius problems
  src/Tribe/Admin/Activation_Page.php
Labels: code review

#1767 Use shortened link
  src/Tribe/App_Shop.php
Labels: code review, merge

#1802 Deprecated the `Tribe__Settings_Manager::add_help_admin_menu_item()` method in favour of `Settings::add_admin_pages()` [TEC-4443]
  readme.txt
  src/Tribe/Settings_Manager.php
Labels: code review
