Repository the-events-calendar/tribe-common, pull requests merged in 2022-12, with the labels that each got.

#1837 Modify the way we handle Async Testing to use a newly created Timed Options
  readme.txt
  src/Common/Storage/Timed_Option.php
  src/Tribe/Feature_Detection.php
  src/Tribe/Main.php
  src/Tribe/Process/Tester.php
  src/functions/transient.php
  tests/wpunit/Common/Storage/Timed_OptionTest.php
Labels: code review, needs artifact

#1844 Manual minification of the `selectWoo.full` js file.
  vendor/tribe-selectWoo/dist/js/selectWoo.full.min.js
Labels: code review

#1846 fix(Notice) do not build on empty value
  src/Tribe/Admin/Notice/Date_Based.php
Labels: merge

#1824 Handle user and site locale correctly in rewrite rule generation context
  readme.txt
  src/Common/Translations_Loader.php
  src/Tribe/Main.php
  src/Tribe/Rewrite.php
  tests/wpunit/TEC/Common/Translations_LoaderTest.php
  tests/wpunit/TEC/Common/__text-domain-plugin/.gitignore
  tests/wpunit/TEC/Common/__text-domain-plugin/README.md
  tests/wpunit/TEC/Common/__text-domain-plugin/test-text-domain-it_IT.mo
  tests/wpunit/TEC/Common/__text-domain-plugin/test-text-domain.php
Labels: code review, hold, needs release

#1853 Adding more uopz support
  tests/_support/Traits/With_Uopz.php
Labels: needs release
