Repository the-events-calendar/tribe-common, pull requests merged in 2022-05, with the labels that each got.

#1746 Fixing merge conflict.
  src/resources/postcss/tribe-common-admin/_main.pcss
Labels: code review

#1747 Fix/include help js troubleshooting
  src/Tribe/Admin/Troubleshooting.php
Labels: merge

#1745 Fix/ea 123 import multi select
  readme.txt
  src/resources/js/admin/help-page.js
  src/resources/js/tribe-datatables.js
  src/resources/postcss/tribe-common-admin.pcss
  src/resources/postcss/tribe-common-admin/_upsell.pcss
Labels: merge

#1749 Events/Tickets menus > QA Repairs
  src/Tribe/Log/Admin.php
Labels: code review

#1752 Fix/admin menu qa repairs
  src/Tribe/Admin/Activation_Page.php
  src/Tribe/Admin/Pages.php
Labels: merge

#1753 Options for saving should come from form if submitted.
  src/Tribe/Settings_Manager.php
Labels: code review, merge

#1754 Fix troubleshooting link for ET as standalone.
  src/admin-views/help.php
Labels: code review

#1755 Make help page link work for ET as standalone.
  src/admin-views/troubleshooting/notice.php
Labels: code review

#1756 Safe check for the `tab` GET var
  src/Tribe/Settings.php
  src/Tribe/Settings_Manager.php
Labels: code review

#1757 Remove comma from parameters.
  src/Tribe/Admin/Pages.php
Labels: code review

#1751 Add Calendar Export Icon Template
  readme.txt
  src/views/v2/components/icons/cal-export.php
  tests/snapshots/Views/V2/Components/Icons/CalExportTest.php
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/CalExportTest__test_render_with_classes_no_label__0.snapshot.html
  tests/snapshots/Views/V2/Components/Icons/__snapshots__/CalExportTest__test_render_without_classes_or_label__0.snapshot.html
Labels: code review

#1759 Admin Pages > Determine current page fix
  readme.txt
  src/Tribe/Admin/Pages.php
Labels: code review

#1762 Improve HTML Class handling for templating
  src/Tribe/Utils/Element_Classes.php
Labels: code review

#1761 Fix/et 1517 ea tickets standalone
  readme.txt
  src/admin-views/troubleshooting/ea-status.php
Labels: code review
