Repository the-events-calendar/tribe-common, pull requests merged in 2022-09, with the labels that each got.

#1807 Prevent E_ERROR on the context usage of is_main_query() too early
  readme.txt
  src/Tribe/Context/locations.php
  tests/wpunit/Tribe/Context_LocationsTest.php
Labels: merge

#1806 Run PHP Tests on GitHub Actions
  .env.testing.slic
  .github/workflows/tests-php.yml
  .gitignore
  codeception.slic.yml
  composer.json
  composer.lock
  src/functions/utils.php
  tests/_bootstrap.php
  tests/_data/dependency-dump.sql
  tests/_data/empty.sql
  tests/_data/empty_cleanup.sql
  tests/integration/File_Logging_Test.php
  tests/snapshots/Views/Admin-Views/SwitchTest.php
  tests/unit/Tribe/Values/PriceTest.php
  tests/wpunit/Tribe/ContextTest.php
  tests/wpunit/Tribe/DependencyTest.php
  tests/wpunit/Tribe/Editor/Compatibility/Classic_Editor/Classic_EditorTest.php
  tests/wpunit/Tribe/Editor/EditorTest.php
  tests/wpunit/Tribe/TimezonesTest.php
Labels: merge

#1803 [ET-1560] Fixed invoking unwanted callable method from passed data.
  readme.txt
  src/Tribe/Repository.php
  tests/wpunit/Tribe/Repository/UpdateTest.php
Labels: code review

#1794 Ensure all strings are using the common text domain.
  src/Tribe/Cost_Utils.php
  src/Tribe/Customizer.php
  src/Tribe/Main.php
Labels: code review, merge

#1799 Fixes two things that have been bugging me.
  readme.txt
  src/Tribe/Context.php
  src/Tribe/Utils/Array.php
  src/functions/utils.php
  tests/wpunit/Tribe/ContextTest.php
Labels: merge

#1809 Common - Fix moment.js
  vendor/momentjs/moment.js
Labels: code review, needs changelog
