Repository the-events-calendar/tribe-common, pull requests merged in 2022-02, with the labels that each got.

#1695 Simplify block checks
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Editor.php
  src/Tribe/Editor/Blocks/Abstract.php
  src/Tribe/Editor/Compatibility.php
  src/Tribe/Editor/Compatibility/Classic_Editor.php
  src/Tribe/Editor/Provider.php
  src/Tribe/REST/Main.php
  src/Tribe/Settings_Manager.php
  src/functions/template-tags/date.php
  src/functions/template-tags/general.php
  tests/_support/Traits/With_Uopz.php
  tests/wpunit/Tribe/Editor/Compatibility/Classic_Editor/Classic_EditorTest.php
  tests/wpunit/Tribe/Editor/Compatibility/Classic_Editor/_bootstrap.php
  tests/wpunit/Tribe/Editor/EditorTest.php
Labels: merge

#1698 [ET-1382] Fixed troubleshooting page fatal error and assets for ET.
  readme.txt
  src/Tribe/Admin/Helpers.php
  src/admin-views/troubleshooting/ea-status/license-key.php
Labels: code review, merge

#1703 Don't test current_screen - it's not always available
  src/Tribe/Editor/Compatibility/Classic_Editor.php
Labels: merge

#1706 Don't deprecate functions we use in ET for now.
  src/Tribe/Editor.php
Labels: merge

#1708 Peformance Improvements
  readme.txt
  src/Tribe/Admin/Notices.php
  src/Tribe/Assets.php
  src/Tribe/Cache.php
  src/Tribe/Date_Utils.php
  src/Tribe/Editor/Blocks/Abstract.php
  src/Tribe/Service_Providers/Tooltip.php
  src/Tribe/Timezones.php
  src/functions/template-tags/general.php
Labels: question, code review

#1711 Fix enqueue of customizer control styles.
  src/Tribe/Main.php
Labels: code review, merge

#1713 Fixes block issue except the event single FE
  src/Tribe/Editor.php
  src/Tribe/Editor/Compatibility/Classic_Editor.php
  src/Tribe/Editor/Provider.php
Labels: code review, merge

#1717 use the precision getter to make sure filters are run
  src/Tribe/Values/Value_Calculation.php
Labels: merge

#1720 add precision setter to the Abstract_Value class
  src/Tribe/Values/Abstract_Value.php
  src/Tribe/Values/Value_Interface.php
Labels: code review
