Repository the-events-calendar/tribe-common, pull requests merged in 2023-04, with the labels that each got.

#1904 Don't use `tec_sanitize_string` on arrays.
  .github/workflows/tests-php.yml
  package-lock.json
  src/functions/utils.php
  tests/_support/ea-server-mocker/src/Cleaner.php
  tests/activation/ActionsCest.php
  tests/wpunit/Tribe/functions/templateTags/generalTest.php
Labels: code review

#1909 Fix edge case bug, with multiple actions being cached and not expirin…
  readme.txt
  src/Tribe/Cache.php
  tests/wpunit/Tribe/CacheTest.php
Labels: code review

#1910 Some button hardening
  readme.txt
  src/resources/postcss/components/full/buttons/_solid.pcss
  src/resources/postcss/tribe-common-admin/_fields.pcss
Labels: merge

#1911 feat(src/Provider) add the base Controller class and test case
  readme.txt
  src/Common/Provider/Controller.php
  tests/_support/Provider/Controller_Test_Case.php
Labels: code review

#1913 Move the code for Integrations from TEC to Common
  readme.txt
  src/Common/Integrations/Integration_Abstract.php
  src/Common/Integrations/Provider.php
  src/Common/Integrations/Traits/Module_Integration.php
  src/Common/Integrations/Traits/Plugin_Integration.php
  src/Common/Integrations/Traits/Server_Integration.php
  src/Common/Integrations/Traits/Theme_Integration.php
  src/Tribe/Main.php
  tests/_data/classes/Integrations/Dummy_Module.php
  tests/_data/classes/Integrations/Dummy_Plugin.php
  tests/_data/classes/Integrations/Dummy_Server.php
  tests/_data/classes/Integrations/Dummy_Theme.php
  tests/wpunit/Common/Integration/Integration_AbstractTests.php
  tests/wpunit/_bootstrap.php
Labels: code review

#1915 Fallback for JWT classes.
  src/Tribe/Service_Providers/Promoter.php
Labels: code review

#1916 Passing null to `strpos()` is deprecated in PHP 8.1
  src/Tribe/Repository.php
Labels: code review, needs release
