Repository the-events-calendar/tribe-common, pull requests merged in 2023-11, with the labels that each got.

#2006 ETWP DQA: Add size param to image ID field
  src/Tribe/Field.php
Labels: code review

#1995 Feature/site editor compatibility level 2 a
  readme.txt
  src/Common/Editor/Full_Site/Template_Utils.php
  src/Tribe/Editor/Blocks/Abstract.php
  src/Tribe/Main.php
  tests/_data/classes/Http_API/Http_API_Mock.php
  tests/wpunit/TEC/Common/Editor/Full_Site/Template_UtilsTest.php
Labels: code review, in-qa

#2010 Update Telemetry library in composer.json and update composer.lock
  composer.json
  composer.lock
Labels: code review

#2011 Forgotten TBDs from older version.
  src/Tribe/Admin/Help_Page.php
Labels: code review

#2016 [ET-1931] Add ETWP to the list of products under Help->Ticketing & RSVP
  readme.txt
  src/Tribe/Admin/Help_Page.php
  src/Tribe/Plugins_API.php
  src/resources/images/logo/wallet-plus.svg
  src/resources/images/shop/wallet-plus.svg
Labels: code review

#2018 Ensure JSON_LD is set for non logged-in users.
  readme.txt
  src/Tribe/JSON_LD/Abstract.php
Labels: merge

#2024 Change ETWP Event Add-Ons image
  src/resources/images/shop/wallet-plus.jpg
Labels: code review
