Repository the-events-calendar/tribe-common, pull requests merged in 2023-06, with the labels that each got.

#1933 Fix deprecation issues with php 8.1.18
  src/Tribe/Admin/Conditional_Content/Datetime_Conditional_Abstract.php
  src/Tribe/Field.php
Labels: needs release, needs changelog

#1940 Do some cleanup of the saved telemetry data if ET has created an "empty" tec entry.
  src/Common/Telemetry/Migration.php
  src/Common/Telemetry/Provider.php
  src/Common/Telemetry/Telemetry.php
  src/Tribe/Main.php
Labels: code review

#1941 Tweak the logic for showing the modal
  src/Common/Telemetry/Telemetry.php
Labels: merge

#1921 Removing GC slowness
  readme.txt
  src/Tribe/Repository/Query_Filters.php
Labels: code review

#1942 Get method to throw a specific Expection that extends RunTimeException
  readme.txt
  src/Common/Contracts/Container.php
  src/Common/Exceptions/Container_Exception.php
  src/Common/Exceptions/Not_Bound_Exception.php
Labels: code review

#1923 Fix/ecp 1505 speed memoize
  readme.txt
  src/Common/Configuration/Configuration.php
  src/Common/Configuration/Configuration_Loader.php
  src/Common/Configuration/Configuration_Provider_Interface.php
  src/Common/Configuration/Constants_Provider.php
  src/Common/Configuration/readme.md
  tests/wpunit/Common/Configuration/ConfigurationTest.php
Labels: code review

#1943 Rename to use the correct provider contract.
  src/Common/Contracts/Container.php
  src/Common/Integrations/Provider.php
  src/Tribe/Main.php
  src/functions/aliases.php
Labels: code review

#1944 Only init Telemetry if it has been properly loaded and booted.
  readme.txt
  src/Common/Telemetry/Provider.php
  tests/wpunit/Tribe/functions/templateTags/generalTest.php
Labels: code review

#1945 Fix PHP 8.1 deprecation warnings.
  composer.lock
Labels: code review
