Repository the-events-calendar/tribe-common, pull requests merged in 2023-10, with the labels that each got.

#1979 Changing scope of property for extending namespace.
  readme.txt
  src/Tribe/Editor/Blocks/Abstract.php
  tests/_data/classes/Http_API/Http_API_Mock.php
Labels: code review

#1986 Feat/tec 4793 single event block template
  src/Common/Editor/Full_Site/Template_Utils.php
  src/Tribe/Editor/Blocks/Abstract.php
  tests/wpunit/TEC/Common/Editor/Full_Site/Template_UtilsTest.php
Labels: merge

#1990 This removes a stray closing div in the new Banner template.
  src/admin-views/notices/tribe-bf-general.php
  src/resources/postcss/tribe-common-admin/_main.pcss
Labels: code review

#1993 Add a new field type to settings called `image_id`
  src/Tribe/Field.php
  src/resources/js/admin-image-field.js
Labels: code review

#1994 Fix AM/PM time format for French locale in the `tribe_format_date()` function.
  readme.txt
  src/functions/template-tags/date.php
  tests/wpunit/Template_Tags/DateTest.php
Labels: code review

#1996 This checks notice transients for serialized classes
  readme.txt
  src/Tribe/Admin/Notices.php
Labels: code review, merge

#2001 In-App - Stellar branding updates.
  src/Tribe/App_Shop.php
  src/resources/images/shop/stellar-learndash-logo.png
  src/resources/images/shop/stellar-rcp-logo.png
  src/resources/images/shop/stellar-solidwp-logo.png
Labels: code review

#2000 Facebook community group CTA in welcome page.
  src/resources/images/welcome/tec-facebook.png
Labels: code review

#2003 Defining dynamic props.
  readme.txt
  src/Tribe/Field.php
  src/Tribe/Settings_Tab.php
Labels: code review
