Repository the-events-calendar/tribe-common, pull requests merged in 2023-05, with the labels that each got.

#1918 Fix/tec 4794 harden common button
  readme.txt
  src/resources/postcss/components/full/buttons/_solid.pcss
Labels: code review, merge

#1919 [ET-1734] Make fields mobile friendly
  readme.txt
  src/resources/postcss/tribe-common-admin/_main.pcss
Labels: code review

#1812 Notice docblock corrections.
  src/Tribe/Admin/Conditional_Content/Black_Friday.php
  src/Tribe/Admin/Conditional_Content/Datetime_Conditional_Abstract.php
  src/Tribe/Admin/Conditional_Content/End_Of_Year_Sale.php
  src/Tribe/Admin/Notice/Date_Based.php
  src/Tribe/Admin/Notice/Marketing/Black_Friday.php
  src/Tribe/Admin/Notice/Marketing/End_Of_Year_Sale.php
  src/admin-views/notices/tribe-stellar-sale.php
Labels: code review

#1922 Fix Image Field Dimensions and Chagelog
  readme.txt
  src/resources/postcss/tribe-common-admin/_fields.pcss
Labels: merge

#1907 Feature - Telemetry
  composer.json
  composer.lock
  package-lock.json
  package-safelist.json
  package.json
  readme.txt
  src/Common/Contracts/Container.php
  src/Common/Contracts/Provider/Controller.php
  src/Common/Contracts/Service_Provider.php
  src/Common/Libraries/Installer/Provider.php
  src/Common/Libraries/Provider.php
  src/Common/Site_Health/Factory.php
  src/Common/Site_Health/Fields/Generic_Info_Field.php
  src/Common/Site_Health/Fields/Post_Status_Count_Field.php
  src/Common/Site_Health/Info_Field_Abstract.php
  src/Common/Site_Health/Info_Field_Interface.php
  src/Common/Site_Health/Info_Section_Abstract.php
  src/Common/Site_Health/Info_Section_Interface.php
  src/Common/Site_Health/Provider.php
  src/Common/Telemetry/Migration.php
  src/Common/Telemetry/Provider.php
  src/Common/Telemetry/Telemetry.php
  src/Tribe/Admin/Conditional_Content/Service_Provider.php
  src/Tribe/Admin/Notice/Service_Provider.php
  src/Tribe/Container.php
  src/Tribe/Editor/Compatibility.php
  src/Tribe/Editor/Provider.php
  src/Tribe/Log/Service_Provider.php
  src/Tribe/Main.php
  src/Tribe/Repository/Core_Read_Interface.php
  src/Tribe/Service_Providers/Body_Classes.php
  src/Tribe/Service_Providers/Crons.php
  src/Tribe/Service_Providers/Debug_Bar.php
  src/Tribe/Service_Providers/Dialog.php
  src/Tribe/Service_Providers/Onboarding.php
  src/Tribe/Service_Providers/PUE.php
  src/Tribe/Service_Providers/Processes.php
  src/Tribe/Service_Providers/Promoter.php
  src/Tribe/Service_Providers/Shortcodes.php
  src/Tribe/Service_Providers/Tooltip.php
  src/Tribe/Service_Providers/Widgets.php
  src/Tribe/Settings.php
  src/Tribe/Settings_Tab.php
  src/admin-views/troubleshooting.php
  src/functions/aliases.php
  src/functions/utils.php
  tests/_data/Tribe/Telemetry/connected.txt
  tests/_data/Tribe/Telemetry/disconnected.txt
  tests/_data/Tribe/Telemetry/mixed.txt
  tests/wpunit/Common/Telemetry/MigrationTest.php
  tests/wpunit/Tribe/functions/templateTags/Boolean_TransformationTest.php
Labels: merge

#1924 Update Version Number
  package.json
  src/Tribe/Main.php
  tribe-common.php
Labels: code review

#1927 Fix Field Container Width on Medium (and Higher) Screens
  src/resources/postcss/tribe-common-admin/_main.pcss
Labels: merge

#1928 Remove code to show modal - delegate to the plugins themselves.
  src/Common/Telemetry/Telemetry.php
  src/Tribe/Settings_Tab.php
Labels: merge

#1929 Fix issue with checkbox in TEC admin
  composer.lock
  src/Common/Telemetry/Provider.php
  src/Common/Telemetry/Telemetry.php
Labels: code review

#1925 use an array for paths so we can be more deterministic
  package-safelist.json
  src/Tribe/Main.php
  tests/snapshots/Views/Admin-Views/__snapshots__/SwitchTest__should_render_loader__0.snapshot.html
  tests/snapshots/Views/Admin-Views/__snapshots__/SwitchTest__should_render_loader_with_custom_text__0.snapshot.html
Labels: code review

#1930 [ET-1766] Set Max Width/Height to Image, not Container
  src/resources/postcss/tribe-common-admin/_fields.pcss
Labels: code review
