Repository the-events-calendar/tribe-common, pull requests merged in 2023-02, with the labels that each got.

#1874 Cast terms to an array before using `array_filter` on them.
  package-lock.json
  src/Tribe/Utils/Taxonomy.php
Labels: merge

#1877 Safeguard around rewrite_filter_array hook params.
  readme.txt
  src/Tribe/Rewrite.php
  tests/wpunit/Tribe/RewriteTest.php
Labels: merge

#1881 Fix the pagination styling on the Aggregator import preview data table.
  readme.txt
  src/Tribe/Main.php
Labels: code review, merge

#1875 Fixing cache check logic.
  readme.txt
  src/Tribe/Cache.php
  tests/wpunit/Tribe/CacheTest.php
Labels: code review

#1878 feat(Context) add the is_editing_posts_list method
  readme.txt
  src/Tribe/Context.php
  tests/_support/Traits/With_Uopz.php
  tests/wpunit/Tribe/ContextTest.php
Labels: question, code review

#1882 Revert updates made via pr id `1881`
  readme.txt
  src/Tribe/Main.php
Labels: code review, merge

#1885 Some cleanup and add_fn()
  tests/_support/Traits/With_Uopz.php
Labels: code review, merge

#1889 [ET-1564] Common > Add Toggle Settings Field
  readme.txt
  src/Tribe/Field.php
  src/resources/postcss/tribe-common-admin/_fields.pcss
Labels: code review

#1888 [ET-1565] Common > Create Customizable WYSIWYG Editor
  readme.txt
  src/Tribe/Admin/Wysiwyg.php
  src/Tribe/Field.php
Labels: code review
