Repository the-events-calendar/tribe-common, pull requests merged in 2024-07, with the labels that each got.

#2128 Abstract for handling merge logic.
  src/Common/Integrations/Plugin_Merge_Provider_Abstract.php
  tests/wpunit/Tribe/functions/templateTags/generalTest.php
Labels: code review

#2132 Added logic for bulk update and single slug for updated notice.
  src/Common/Integrations/Plugin_Merge_Provider_Abstract.php
Labels: code review, merge

#2133 [TEC-5118] Modify notice id so it is unique per plugin
  src/Common/Integrations/Plugin_Merge_Provider_Abstract.php
Labels: code review

#2134 Updated logic with concat of plugins for update notice.
  src/Common/Integrations/Plugin_Merge_Provider_Abstract.php
Labels: code review

#2136 Moved the render to a deferred inline html render, instead of a callb…
  src/Common/Integrations/Plugin_Merge_Provider_Abstract.php
Labels: code review

#2138 `get_plugin_real_path` check if plugin exists
  src/Common/Integrations/Plugin_Merge_Provider_Abstract.php
Labels: code review

#2141 Accidentally added a message in a cleanup commit. Removed.
  src/Common/Integrations/Plugin_Merge_Provider_Abstract.php
Labels: code review

#2140 Resolve `Uncaught ReferenceError: regeneratorRuntime is not defined`
  src/modules/store/index.js
Labels: code review, in-qa, needs release, needs changelog, needs artifact

#2142 Scenario where memoized path was storing an unlocated path because it…
  src/Common/Integrations/Plugin_Merge_Provider_Abstract.php
Labels: code review

#2151 Moving wp-cli requirement to dev
  composer.json
  composer.lock
Labels: code review

#2158 Reverting stellar sale banner changes
  changelog/fix-stellar-sale-banner
  src/Tribe/Admin/Notice/Marketing/Stellar_Sale.php
  src/Tribe/Main.php
  src/admin-views/notices/tribe-stellar-sale.php
  tribe-common.php
Labels: code review
