Repository the-events-calendar/tribe-common, pull requests merged in 2024-06, with the labels that each got.

#2093 Feature/stellarwp assets
  .gitignore
  .puprc
  composer.json
  composer.lock
  package-lock.json
  readme.txt
  src/Common/Libraries/Provider.php
  src/Tribe/Assets.php
  src/Tribe/Main.php
  src/functions/template-tags/general.php
  tests/wpunit/Tribe/AssetsTest.php
  tests/wpunit/Tribe/Repository/ReadMultipleFieldsTest.php
  tests/wpunit/Tribe/functions/templateTags/generalTest.php
Labels: code review

#2094 Undefined funcs, reference this scope directly instead.
  tests/_support/Provider/Controller_Test_Case.php
Labels: code review

#2095 Update Stellar Sale Banner and Logic
  readme.txt
  src/Tribe/Admin/Notice/Marketing/Stellar_Sale.php
  src/admin-views/notices/tribe-stellar-sale.php
  src/resources/postcss/tribe-common-admin/_main.pcss
  tests/wpunit/Tribe/Notices/Stellar_SaleTest.php
Labels: code review

#2097 [ET-2115] Update steallarwp/assets
  composer.json
  composer.lock
Labels: code review

#2098 Updating the memoized transient notice, and test validating.
  readme.txt
  src/Tribe/Admin/Notices.php
  tests/wpunit/Tribe/Notices/NoticesTest.php
Labels: code review

#2099 Update Stellar Sale URLs
  src/Tribe/Admin/Notice/Marketing/Stellar_Sale.php
Labels: code review

#2102 Moving Zapier endpoints to the respective plugins.
  readme.txt
  src/Common/Event_Automator/Zapier/Zapier_Provider.php
Labels: merge

#2104 Common (ET or TEC) throws a fatal when activated alongside EVA
  src/Common/Event_Automator/Plugin.php
Labels: code review

#2103 Ensure the whole path is passed to Stellar Assets
  composer.json
  composer.lock
  src/Tribe/Assets.php
  src/Tribe/Main.php
  tribe-common.php
Labels: code review

#2115 Updating logic to retain dismissable notices until dismissed.
  readme.txt
  src/Tribe/Admin/Notices.php
Labels: code review, needs changelog, needs tests

#2123 Change copy of tooltips for disabled endpoints
  src/admin-views/dashboard/components/missing-dependency.php
  src/admin-views/zapier/dashboard/components/missing-dependency.php
Labels: merge

#2125 Missing dependencies for EVA.
  src/Common/Event_Automator/Integrations/Assets.php
  src/Common/Event_Automator/Zapier/Assets.php
Labels: code review

#2127 Moving plugin path defin up.
  src/Common/Event_Automator/Plugin.php
Labels: code review

#2085 App Shop: Remove VE, EVA, and ETW+ from the app-shop and bundles pages.
  .github/workflows/tests-php.yml
  src/Tribe/App_Shop.php
Labels: code review, hold
