Repository the-events-calendar/tribe-common, pull requests merged in 2024-04, with the labels that each got.

#2066 Feature > Attendees page
  readme.txt
  src/Tribe/Admin/Pages.php
Labels: needs changelog

#2071 Readme change and updated version numbers
  readme.txt
Labels: code review

#2072 Updated QS, added changelog.
  readme.txt
  src/resources/js/utils/query-string.js
Labels: code review

#2077 Replace calls to select2 with select2TEC in dependency.js to prevent conflicts.
  readme.txt
  src/resources/js/dependency.js
Labels: code review, merge
