Repository the-events-calendar/tribe-common, pull requests merged in 2024-03, with the labels that each got.

#2060 Fix php 8.2 deprecation error with date_only, test, changelog.
  readme.txt
  src/Tribe/Date_Utils.php
  tests/wpunit/Tribe/Date_UtilsTest.php
Labels: code review

#2063 Compare: Release/b24.cardinal
  .github/workflows/link-project.yml
  composer.lock
  package-lock.json
  package.json
  phpcs.xml
  readme.txt
  src/Tribe/Date_Utils.php
  src/Tribe/Main.php
  src/Tribe/Template.php
  tests/_data/plugin-views/templates/etc/dummy-template.php
  tests/wpunit/Tribe/Date_UtilsTest.php
  tests/wpunit/Tribe/Support/Template_CheckerTest.php
  tests/wpunit/Tribe/TemplateTest.php
  tribe-common.php
Labels: hold

#1719 Include more styles to reset theme bleeding color
  composer.json
  composer.lock
  phpcs.xml
  src/resources/postcss/components/full/_all.pcss
  src/resources/postcss/components/full/buttons/_clear.pcss
Labels: code review, merge
