Repository the-events-calendar/tribe-common, pull requests merged in 2024-01, with the labels that each got.

#2009 Fix/tec 4935 tribe events delete
  readme.txt
  src/Tribe/Repository.php
  tests/wpunit/Tribe/Repository/DeleteTest.php
Labels: code review

#2034 Enable auto-updates for premium plugins | TCMN-169
  readme.txt
  src/Tribe/PUE/Checker.php
Labels: hold, merge

#2017 Fix the `Tribe__Data` class
  readme.txt
  src/Tribe/Data.php
Labels: code review

#2036 Deprecations around return values that were missed in the first fix PR.
  src/Tribe/Data.php
Labels: code review

#2037 Fix object/array assignation issue
  src/Tribe/PUE/Checker.php
Labels: code review

#2043 Cast to int for str_split
  src/Tribe/Cache.php
Labels: code review

#2012 Add phpstan to tribe-common
  .github/workflows/phpstan.yml
  CONTRIBUTING.md
  composer.json
  composer.lock
  phpstan.neon
  src/Common/Integrations/Integration_Abstract.php
  src/Common/Storage/Timed_Option.php
  src/Common/Telemetry/Telemetry.php
  src/Tribe/Admin/Activation_Page.php
  src/Tribe/Admin/Conditional_Content/Datetime_Conditional_Abstract.php
  src/Tribe/Admin/Help_Page.php
  src/Tribe/Admin/Helpers.php
  src/Tribe/Admin/Notice/Date_Based.php
  src/Tribe/Admin/Notice/Marketing.php
  src/Tribe/Admin/Notice/Php_Version.php
  src/Tribe/Admin/Notice/Plugin_Upgrade_Notice.php
  src/Tribe/App_Shop.php
  src/Tribe/Credits.php
  src/Tribe/Data.php
  src/Tribe/Main.php
  src/Tribe/Plugins.php
  src/Tribe/View_Helpers.php
  src/Tribe/Widget/Widget_Abstract.php
  src/admin-views/troubleshooting/ea-status/eventbrite.php
  src/admin-views/troubleshooting/ea-status/meetup.php
  src/functions/template-tags/general.php
  src/functions/utils.php
  src/views/dialog/button.php
  tribe-common.php
Labels: code review

#2044 Backporting a fix that came in to the uplink library
  src/Tribe/PUE/Checker.php
Labels: code review

#2048 Notice code updated to adhere to more modern Standards
  readme.txt
  src/Tribe/Admin/Notices.php
  src/resources/js/notice-dismiss.js
Labels: code review

#2052 Correct modal arg filtering to not overwrite indiscriminately
  src/Common/Telemetry/Provider.php
  src/Common/Telemetry/Telemetry.php
Labels: merge
