Repository the-events-calendar/tribe-common, pull requests merged in 2025-03, with the labels that each got.

#2423 Hide Install Event Tickets button if step has been completed
  changelog/fix-TEC-5410-hide-install-ET-button
  src/resources/postcss/tribe-common-admin/tec_baseline_admin/_step-list.pcss
Labels: code review

#2433 Feat/calendar embeds
  changelog/feat-calendar-embeds
  src/Common/Controller.php
  src/Common/Template.php
  src/Tribe/Main.php
  src/functions/template-tags/html.php
  src/views/embed/footer.php
  src/views/embed/header.php
Labels: code review

#2440 tiny style tweak for simple header.
  src/resources/postcss/tribe-common-admin/tec_baseline_admin/_header.pcss
Labels: code review

#2441 Make sure we flush permalinks on updates
  changelog/fix-flush-permalinkson-update
  src/Common/Updater.php
Labels: code review

#2447 Updating release branch with ECE
  changelog/feat-calendar-embeds
  changelog/fix-flush-permalinkson-update
  src/Common/Controller.php
  src/Common/Template.php
  src/Common/Updater.php
  src/Tribe/Main.php
  src/functions/template-tags/html.php
  src/views/embed/footer.php
  src/views/embed/header.php
Labels: merge

#2452 Fixes restv1_et test suite
  tests/_data/restv1_et-dump.sql
  tests/_support/Traits/Create_Attendees.php
Labels: code review

#2439 External Calendar embeds - Sanity check
  changelog/feat-calendar-embeds
  changelog/fix-flush-permalinkson-update
  src/Common/Controller.php
  src/Common/Template.php
  src/Common/Updater.php
  src/Tribe/Main.php
  src/functions/template-tags/html.php
  src/views/embed/footer.php
  src/views/embed/header.php
Labels: hold
